docs(mesh) Formatting and image name fixes for installation
Kong/docs.konghq.com pull request #2290
Opened 2020-09-02 21:23 UTC by lena-larionova

* Adjusting formatting, language, grammar
* For Docker install: fixing Docker image name to point to Kong Mesh instead of Kuma (tested pulling them, they should be correct now)
* Adding tabs to installation pages that were missing them to match other installation pages
* Removing link to Helm and Helm chart tab, as Helm install doesn't exist yet. Will re-add when that changes.

2020-09-03 13:27 UTC, tlblessing requested changes
"With" is a preposition and should not be capitalized (global suggested edit; e.g. Kong Mesh with Ubuntu). https://www.grammarly.com/blog/capitalization-in-the-titles/

A few commas missing. Suggested an edit and screenshot here since the text not in PR:
![image](https://user-images.githubusercontent.com/3756245/92120779-19773280-edbf-11ea-9e6b-7435143e24cc.png)

2020-09-03 13:27 UTC, tlblessing commented on app/mesh/1.0.x/install.md
> +On this page you will find access to the official {{site.mesh_product_name}}
```suggestion
On this page, you will find access to the official {{site.mesh_product_name}}
```

2020-09-03 21:36 UTC, lena-larionova commented
> "With" is a preposition and should not be capitalized (global suggested edit; e.g. Kong Mesh with Ubuntu). https://www.grammarly.com/blog/capitalization-in-the-titles/

You're right - I missed looking at the titles completely. 

> A few commas missing.

Chalk it up to editing fatigue. Will look over the install topics again.

2020-09-04 14:27 UTC, tlblessing approved these changes
LGTM

2020-09-04 16:00 UTC, merged