Add UDP points
Kong/docs.konghq.com pull request #2341
Opened 2020-09-29 05:51 UTC by javierguerragiraldez

2020-09-30 08:53 UTC, dndx approved these changes

2020-10-01 13:10 UTC, dndx commented
Hello @tlblessing, could you please take a look at this change so it can be ready for the 2.2 release? Thank you!

2020-10-02 12:48 UTC, kikito approved these changes

2020-10-20 20:34 UTC, tlblessing requested changes
Suggested edits that I'll incorporate. @javierguerragiraldez apologies for the delay. I assume the plugins included in this PR also need a version bump?

2020-10-20 20:34 UTC, tlblessing commented on app/2.2.x/plugin-development/custom-logic.md
> +Note that UDP streams don't have real "connections".  Kong will consider all
```suggestion
Note that UDP streams don't have real connections.  Kong will consider all
```

2020-10-20 20:34 UTC, tlblessing commented on app/2.2.x/plugin-development/custom-logic.md
> +"connection".  After a configurable time without any packet, the connection is
```suggestion
connection.  After a configurable time without any packet, the connection is
```

2020-10-20 20:34 UTC, tlblessing commented on app/2.2.x/plugin-development/custom-logic.md
> +considered "closed" and the `:log()` function is executed.
```suggestion
considered closed and the `:log()` function is executed. 
```

2020-10-20 21:06 UTC, tlblessing approved these changes
Approving and merging for 2.2 release but the plugin versions need updating and version files as appropriate for historical updates. We are tracking discrepancies in a spreadsheet.

2020-10-20 21:07 UTC, merged