docs(ee-license) Clarify and update license and Bintray doc
Kong/docs.konghq.com pull request #2376
Opened 2020-10-13 22:08 UTC by lena-larionova

Based on https://konghq.atlassian.net/browse/DOCS-1252.

Trying to settle some of the confusion about where to find your license. The main culprit was the mention of Bintray and licenses with no context in the installation steps (people tend to ignore the prereqs). 

* Turned license prereq into an include file that's now reused for every installation doc.
* Updated "Accessing your License" with a prereq section and a link to trial/demo info.
* Updated trial section of the Introduction to Kong Enterprise topic.
* Some cleanup to installation docs - typos, formatting of the license and Bintray sections, turning URLs into actual links, turning notes into note-formatted content. 

Will backport into 1.5.x (and maybe into 1.3.x) once phrasing is reviewed and finalized.

2020-10-14 14:45 UTC, tlblessing requested changes
Suggested edits. Any comments apply globally to the content. I didn't mark every occurrence.

2020-10-14 14:45 UTC, tlblessing commented on app/_includes/md/2.1.x/bintray-and-license.md
> + For more detail, see [Accessing Your License](/enterprise/latest/deployment/access-license).
```suggestion
 For more details, see [Accessing Your License](/enterprise/latest/deployment/access-license).
```

2020-10-14 14:45 UTC, tlblessing commented on app/enterprise/2.1.x/deployment/access-license.md
> +2. You will notice that along with Kong Enterprise, there is a new
```suggestion
2. Notice that along with Kong Enterprise, there is a new
```

2020-10-14 14:45 UTC, tlblessing commented on app/enterprise/2.1.x/deployment/access-license.md
> +5. Click any file you would like to download.
```suggestion
5. Click any file you want to download.
```

2020-10-14 14:45 UTC, tlblessing commented on app/enterprise/2.1.x/deployment/access-license.md
> + - Username (was provided by email by your CSE)
```suggestion
 - Username (was provided through email by your CSE)
```

2020-10-14 14:45 UTC, tlblessing commented on app/enterprise/2.1.x/deployment/installation/amazon-linux-2.md
> +6. Save the RPM file available. For example, `kong-enterprise-edition-{{page.kong_latest.version}}.aws.rpm`.
```suggestion
6. Save the available RPM file. For example, `kong-enterprise-edition-{{page.kong_latest.version}}.aws.rpm`.
```

2020-10-14 21:12 UTC, GayleNeumann approved these changes
LGTM

2020-10-15 19:16 UTC, tlblessing approved these changes
LGTM

2020-10-16 17:04 UTC, merged