docs(vitals) add link to InfluxDB topic
Kong/docs.konghq.com pull request #2414
Opened 2020-10-23 22:54 UTC by GayleNeumann

-- added link in prerequisites section to Vitals with InfluxDB topic.

2020-10-26 14:39 UTC, tlblessing requested changes
suggested edits. at least start with For more info clause and remove extraneous verbiage "topic".

2020-10-26 14:39 UTC, tlblessing commented on app/enterprise/2.1.x/vitals/vitals-reports.md
> +   * InfluxDB database. See the [Vitals with InfluxDB](https://docs.konghq.com/enterprise/{{page.kong_version}}/vitals/vitals-influx-strategy/) topic for more information.
```suggestion
   * InfluxDB database installed and configured. For more information, see [Vitals with InfluxDB](https://docs.konghq.com/enterprise/{{page.kong_version}}/vitals/vitals-influx-strategy/).  
```

2020-10-26 20:51 UTC, lena-larionova commented
@tlblessing taking over this from Gayle for the week. Can you give the PR a quick re-look?

2020-11-03 18:00 UTC, tlblessing approved these changes

2020-11-03 18:21 UTC, merged