Specified that kong host names are case-sensitive.
Kong/docs.konghq.com pull request #2458
Opened 2020-11-18 04:28 UTC by sreeharisj23

## Description

Specified that kong host names are case-sensitive.

## Related Issues

addresses #586

2020-11-18 17:00 UTC, tlblessing requested changes

2020-11-18 17:00 UTC, tlblessing commented on app/0.10.x/admin-api.md
> +When matching a request against an api's hosts field, the match is case sensitive
```suggestion
When matching a request against an api's hosts field, the match is case-sensitive.
```

2020-11-18 17:00 UTC, tlblessing commented on app/0.10.x/getting-started/adding-your-api.md
> +    When matching a request against an api's hosts field, the match is case sensitive
```suggestion
    When matching a request against an api's hosts field, the match is case-sensitive.
```

2020-11-18 17:21 UTC, sreeharisj23 commented
I've made the changes you suggested @tlblessing

2020-11-20 17:44 UTC, tlblessing approved these changes
LGTM thank you Sreehari for the PR!

2020-12-06 18:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/docs.konghq.com?pullRequest=2458) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/docs.konghq.com?pullRequest=2458) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/docs.konghq.com?pullRequest=2458) it.</sub>

2021-06-17 20:33 UTC, falondarville commented
This endpoint is deprecated. We are going to update the current documentation noting that `host` is case sensitive.

2021-06-17 20:33 UTC, closed without merging