doc(support-policy) update to new support policy
Kong/docs.konghq.com pull request #2476
Opened 2020-11-24 21:38 UTC by GayleNeumann

-- Updated content to new Support Policy, per Shane's doc: https://docs.google.com/document/d/1mCe3gX-3r3QaSLLMhj_vZU1Bn-Yu6SUVXQPwAbvhFp4/edit#
-- This update to be released on Monday, Nov 30, 2020, per Tom in Legal. 
-- Coordinate this doc with Jimmy/Customer Support.

2020-11-30 20:40 UTC, eskibars requested changes
Left 2 small comments/revision requests.  Other than that LGTM

2020-11-30 20:40 UTC, eskibars commented on app/enterprise/2.2.x/support-policy.md
> +For customers with an active enterprise support agreement, beginning with Kong Enterprise release version 2.1.3.x<sup>*</sup>. Kong provides support for each Major Version release of Kong Enterprise
The last sentence here should read "Kong provides support for each Major Version release of Kong Enterprise for 24 months from the release date of the Minor Version."

2020-11-30 20:40 UTC, eskibars commented on app/enterprise/2.2.x/support-policy.md
> +* Serious security vulnerabilities are treated with the utmost priority. See here for our security vulnerability reporting and remedy process, including how to report a vulnerability.
"here" should have a link to /VERSION/kong-security-update-process/

2020-11-30 20:42 UTC, eskibars commented
Oh, 1 more request, the bottom says `The above is a summary only and is qualified by Kong’s Support and Maintenance Policy.`.  Let's link that `Support and Maintenance Policy` to https://konghq.com/supportandmaintenancepolicy/

2020-11-30 23:24 UTC, lena-larionova commented on app/enterprise/2.2.x/support-policy.md
>  toc: false
```suggestion
```

2020-11-30 23:37 UTC, lena-larionova approved these changes
LGTM

2020-12-01 00:39 UTC, eskibars commented
Thanks @GayleNeumann this LGTM!

2020-12-01 00:56 UTC, eskibars approved these changes

2020-12-01 01:53 UTC, merged