plugins(acme) add document for external account binding
Kong/docs.konghq.com pull request #2491
Opened 2020-12-07 16:40 UTC by fffonion

2020-12-07 17:06 UTC, tlblessing requested changes
Thanks for the PR @fffonion. Suggested corrections. It looks like the versions file needs to be updated, as current docs only show 0.2.7. 

![image](https://user-images.githubusercontent.com/3756245/101381362-46365c80-387c-11eb-8f7c-c874ae80b0b8.png)

2020-12-07 17:06 UTC, tlblessing commented on app/_hub/kong-inc/acme/index.md
> +        External account binding (EAB) key id. User usually doesn't need to set this unless explictly required by CA.
```suggestion
        External account binding (EAB) key id. You usually don't need to set this unless it is explicitly required by the CA.
```

2020-12-07 17:06 UTC, tlblessing commented on app/_hub/kong-inc/acme/index.md
> +        External account binding (EAB) base64 encoded URL string of the HMAC key. User usually doesn't need to set this unless explictly required by CA.
```suggestion
        External account binding (EAB) base64-encoded URL string of the HMAC key. You usually don't need to set this unless it is explicitly required by the CA.
```

2020-12-07 17:06 UTC, tlblessing commented on app/_hub/kong-inc/acme/index.md
> +The following CA provider's external account can be registered automatically and user doesn't need
```suggestion
The following CA provider's external account can be registered automatically, without specifying
```

2020-12-07 17:06 UTC, tlblessing commented on app/_hub/kong-inc/acme/index.md
> +to specify `eab_kid` or `eab_hmac_key`:
```suggestion
the `eab_kid` or `eab_hmac_key`:
```

2020-12-07 17:06 UTC, tlblessing commented on app/_hub/kong-inc/acme/index.md
> +Externel account binding (EAB) is supported as long as `eab_kid` and `eab_hmac_key` is provided.
Not sure if this is both or either (or)?

```suggestion
Externel account binding (EAB) is supported as long as `eab_kid` and `eab_hmac_key` are provided.
```

2020-12-07 17:41 UTC, tlblessing requested changes
We also need version 0.2.13 in versions file. The plugin is not displaying in the staged doc.

2020-12-07 18:03 UTC, tlblessing requested changes

2020-12-07 18:03 UTC, tlblessing commented on app/_data/extensions/kong-inc/acme/versions.yml
> +- release: 0.2.11
```suggestion
- release: 0.2.13
- release: 0.2.11
```

2020-12-07 18:55 UTC, tlblessing commented
Need to troubleshoot why the plugin won't appear in the staging hub. Already added in versions.

2020-12-07 19:42 UTC, tlblessing commented
Tested all versions from hub, docs now display ACME https://deploy-preview-2491--kongdocs.netlify.app/hub/kong-inc/acme/

2020-12-07 19:43 UTC, tlblessing approved these changes
@fffonion please review my edits, and if all looks good to you, merge the PR.

2020-12-08 14:57 UTC, tlblessing commented
Merging so this doesn't sit.

2020-12-08 14:57 UTC, merged

2020-12-08 14:59 UTC, fffonion commented
I missed the notification, thanks @tlblessing !