[DOCS-1582] updated titles, version numbers, and minor formatting issues for 2.3.x
Kong/docs.konghq.com pull request #2652
Opened 2021-03-02 13:53 UTC by HCloward

### Review
@reviewer - TBD

### Summary
The upgrade guides for upgrading from 2.2.x to 2.3.x and 2.3.x OSS to 2.3.x Enterprise need updating after the 2.3.x release.

### Reason
[DOCS-1582](https://konghq.atlassian.net/browse/DOCS-1582?focusedCommentId=38123&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38123)

### Testing
Will post link when it is ready.

2021-03-05 17:06 UTC, rainest requested changes

2021-03-05 17:06 UTC, rainest commented on app/enterprise/2.3.x/deployment/upgrades/migrations.md
> +### Kong for kubernetes considerations
```suggestion
### Kong for Kubernetes considerations
```

2021-03-05 17:06 UTC, rainest commented on app/enterprise/2.3.x/deployment/upgrades/migrations.md
> +`init-migrations` jobs will clear it.
Should be okay to clear this out. 1.5 is ancient and new installs should not use it.
```suggestion
```

2021-03-05 17:06 UTC, rainest commented on app/enterprise/2.3.x/deployment/upgrades/migrations.md
> +For specific Kong for kubernetes version upgrade considerations, see
```suggestion
For specific Kong for Kubernetes version upgrade considerations, see 
```

2021-03-05 18:32 UTC, rainest approved these changes

2021-03-11 21:50 UTC, lena-larionova approved these changes

2021-03-11 21:51 UTC, lena-larionova commented
@HCloward merging this in, as it was requested that this go live before the long weekend.

2021-03-11 22:28 UTC, merged