WIP feat(pdk) add documents for Javascript and Python PDK
Kong/docs.konghq.com pull request #2690
Opened 2021-03-16 15:59 UTC by fffonion

### Review

@reviewer

### Summary

### Reason

### Testing

TODO:
copy to app/enterprise/2.3.x/external-plugins.md as well

2021-03-16 17:23 UTC, tlblessing commented
@fffonion thank you for the PR. I see your comment:

> TODO: copy to app/enterprise/2.3.x/external-plugins.md as well

We can set this up as includes. I'll edit what is present, and find a spot in the TOC. The External plugins section (Go) needs some relocating as well; I have tickets for that to create a cohesive plugin PDK section.

2021-03-16 17:40 UTC, tlblessing commented
> Also, is this a 2.4 feature rather than 2.3? That was my impression from @PaulFischer-Kong from a meeting we had recently.

Paul has confirmed this is a 2.4.x feature, so this PR needs to be retargeted:

> hi! :wave: yes that is correct
> 
> 2.4 feature

2021-03-17 06:08 UTC, fffonion commented
@tlblessing This is indeed a 2.4 feature, but specially the feature doesn't occur inside Kong itself, so it's also supported on  Kong Gateway/Enterprise 2.3. So I'm thinking backporting it to 2.3 docs is also helpful. How do you think?

2021-03-22 16:09 UTC, tlblessing requested changes
Thank you for the PR @fffonion. When we have a 2.4.x branch, we can retarget this PR, and I can set up includes to use between OSS and Enterprise. Update: Per @lena-larionova, no includes at this time. 

I did an initial review for now with suggested minor edits for typos.

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +- [kong-js-pdk] includes type definitions for PDK functions that allows type checking
```suggestion
- [kong-js-pdk] includes type definitions for PDK functions that allow type checking
```

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +- Plugin written in TypeScript can be loaded directly and transpiled on-the-fly.
```suggestion
- Plugin written in TypeScript can be loaded directly and transpiled on the fly.
```

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +[kong-js-pdk] can be installed via `npm`. To install the plugin server binary globally, use:
```suggestion
[kong-js-pdk] can be installed using `npm`. To install the plugin server binary globally:
```

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +To use it in your local development directory, use:
```suggestion
To install it in your local development directory:
```

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +A valid JavaScript plugin implementation should export following object:
```suggestion
A valid JavaScript plugin implementation should export the following object:
```

2021-03-22 16:09 UTC, tlblessing commented on app/gateway-oss/2.3.x/external-plugins.md
> +instance; it's convient to use `async`/`await` keywords in phase handlers for better readibility.
```suggestion
instance; it's convenient to use `async`/`await` keywords in phase handlers for better readability.
```

2021-03-22 16:17 UTC, tlblessing commented
> @tlblessing This is indeed a 2.4 feature, but specially the feature doesn't occur inside Kong itself, so it's also supported on Kong Gateway/Enterprise 2.3. So I'm thinking backporting it to 2.3 docs is also helpful. How do you think?

@fffonion I'm not sure since @PaulFischer-Kong siad above this is 2.4 feature. We do have docs for external plugins as you know, and this PR needs to 

> @tlblessing This is indeed a 2.4 feature, but specially the feature doesn't occur inside Kong itself, so it's also supported on Kong Gateway/Enterprise 2.3. So I'm thinking backporting it to 2.3 docs is also helpful. How do you think?

@fffonion I'm not sure since @PaulFischer-Kong said above this is a 2.4 feature?

2021-03-31 17:50 UTC, kikito approved these changes

2021-04-05 21:39 UTC, tlblessing commented
@fffonion there is another PR by @javierguerragiraldez updating this file for Python PDK in PR https://github.com/Kong/docs.konghq.com/pull/2741.

2021-04-05 23:23 UTC, tlblessing commented
Direct review link:

https://deploy-preview-2690--kongdocs.netlify.app/gateway-oss/2.4.x/external-plugins/

(Had to update redirects)

2021-04-05 23:50 UTC, tlblessing approved these changes

2021-04-06 20:43 UTC, merged