[DOCS-1650] Konnect runtime manager: Helm config instructions
Kong/docs.konghq.com pull request #2698
Opened 2021-03-18 21:27 UTC by lena-larionova

### Review

@nikirago, @rainest 

### Summary
Adding Helm option when setting up a Konnect runtime through Runtime Manager's advanced config.

Questions for reviewers:
* The [sample values.yaml](https://github.com/Kong/charts/blob/main/charts/kong/example-values/minimal-kong-hybrid-data.yaml) file I based this on has `postgres: enabled` for the data plane, which can't be right - and in fact, I couldn't get it to launch until I set it to `postgres: disabled`. Was I missing something, or does the sample file need correcting? Or is it just different for `pki` mode?
* How do you add/specify the CA cert? In the doc for kubernetes tls secrets, I couldn't find any info on adding anything beyond one cert and key: https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
* Any other steps or instructions missing?

### Reason
Helm/YAML config is a common use case:
https://konghq.atlassian.net/browse/DOCS-1650

### Testing
Netlify link TBA

2021-03-19 18:00 UTC, rainest requested changes
Yeah, that example had bad copy pasta from elsewhere. Spawning Postgres shouldn't actually prevent startup, though it's pointless. https://github.com/Kong/charts/pull/321 will remove it from upstream.

2021-03-19 18:00 UTC, rainest commented on app/konnect/runtime-manager/kong-gateway-runtime.md
> +      --key=/tmp/cluster.key
The dedicated `tls` Secret type only supports cert/key pairs, so CA certificates where you only have the certificate need to go into a generic certificate instead:

```suggestion
    $ kubectl create secret tls kong-cluster-cert \
      --cert=/tmp/cluster.crt \
      --key=/tmp/cluster.key

    $ kubectl create secret generic kong-cluster-ca \
      --from-file=ca.crt=/tmp/ca.crt
```
Technically speaking they could go into a ConfigMap instead, but our mount mechanism doesn't support those yet.

2021-03-19 18:00 UTC, rainest commented on app/konnect/runtime-manager/kong-gateway-runtime.md
> +      cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
```suggestion
      cluster_ca_cert: /etc/secrets/kong-cluster-ca/ca.crt
      cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
```

2021-03-19 18:00 UTC, rainest commented on app/konnect/runtime-manager/kong-gateway-runtime.md
> +    - kong-cluster-cert
```suggestion
    - kong-cluster-cert
    - kong-cluster-ca
```

2021-03-22 17:32 UTC, lena-larionova commented
@rainest Does it make sense now to set `lua_ssl_trusted_certificate: system,/etc/secrets/kong-cluster-ca/ca.crt`? I.e, does it still make sense to use `system` here? (Here's the [reference doc](https://docs.konghq.com/enterprise/2.3.x/property-reference/#lua_ssl_trusted_certificate))

2021-03-22 17:37 UTC, rainest approved these changes
AFAIK `lua_ssl_trusted_certificate` is used for other trust checks, but not for this at all. https://docs.konghq.com/gateway-oss/2.3.x/hybrid-mode/#pki-mode doesn't indicate that it needs to be set, so this doc doesn't need to modify it either.

2021-03-22 17:51 UTC, lena-larionova commented
Not sure if the PKI mode doc is entirely correct - that, or it's slightly different for Konnect. The auto-generated chunk of code you get in the Konnect UI includes this parameter (but no `cluster_ca_cert`, which is necessary here):

![Screen Shot 2021-03-22 at 10 46 28 AM](https://user-images.githubusercontent.com/54370747/112035095-75579d80-8afc-11eb-9026-8ebba28a41ca.png)

2021-03-22 18:14 UTC, rainest commented
The generated Konnect config seems wrong but I'm unsure who's the best person to contact about it. PKI mode [enforces a hard requirement on the dedicated setting](https://github.com/Kong/kong/blob/2.3.3/kong/conf_loader/init.lua#L1024-L1026), so I wouldn't expect a DP node to start in PKI mode without it.

2021-03-22 18:18 UTC, lena-larionova commented
> The generated Konnect config seems wrong but I'm unsure who's the best person to contact about it. PKI mode [enforces a hard requirement on the dedicated setting](https://github.com/Kong/kong/blob/2.3.3/kong/conf_loader/init.lua#L1024-L1026), so I wouldn't expect a DP node to start in PKI mode without it.

@artomal can you take a look?

2021-03-22 19:34 UTC, lena-larionova commented
Never mind - I vaguely remembered a similar discussion on an earlier ticket: https://github.com/Kong/docs.konghq.com/pull/2575#discussion_r575564875

The specific info to note:
> If this is for bring-your-own-data-plane then cluster_ca_cert is not needed, cluster_cert is the client cert DP present to CP, and cluster_ca_cert is the CA for CP to verify DP.

Since Konnect config is managed by Kong, generally this setting isn't needed on the DP side?

2021-03-23 16:41 UTC, HCloward approved these changes

2021-03-23 16:44 UTC, merged