[DOCU-679] Session plugin add datatypes
Kong/docs.konghq.com pull request #2746
Opened 2021-04-06 18:17 UTC by tlblessing

https://konghq.atlassian.net/browse/DOCU-679

2021-04-07 20:09 UTC, murillopaula requested changes

2021-04-07 20:09 UTC, murillopaula commented on app/_hub/kong-inc/session/index.md
> +      datatype:
```suggestion
      datatype: string
```

2021-04-07 20:09 UTC, murillopaula commented on app/_hub/kong-inc/session/index.md
> +      datatype: array of strings
```suggestion
      datatype: array of string elements
```

2021-04-08 11:28 UTC, murillopaula approved these changes

2021-04-08 14:16 UTC, HCloward approved these changes

2021-04-08 14:48 UTC, merged