[DOCU-670][DOCU-481]  GraphQL proxy adv plugin datatypes, menu fix
Kong/docs.konghq.com pull request #2747
Opened 2021-04-06 19:55 UTC by tlblessing

2021-04-07 20:11 UTC, murillopaula requested changes

2021-04-07 20:11 UTC, murillopaula commented on app/_hub/kong-inc/graphql-proxy-cache-advanced/index.md
> +      datatype: array of strings
```suggestion
      datatype: array of string elements
```

2021-04-08 11:28 UTC, murillopaula approved these changes

2021-04-08 14:22 UTC, HCloward approved these changes

2021-04-08 14:47 UTC, merged