fix(go) update doc to use go mod when installing go-pluginserver
Kong/docs.konghq.com pull request #2787
Opened 2021-04-14 13:43 UTC by fffonion

### Review

@reviewer

### Summary

### Reason
From https://github.com/Kong/docker-kong/issues/458

### Testing

2021-04-14 13:45 UTC, fffonion commented
This doesn't look right, will rewrite.

2021-04-14 13:46 UTC, HCloward approved these changes
LGTM - thanks @fffonion !

2021-04-14 13:48 UTC, fffonion commented
I updated the PR as the context is not accurate before, would you take another review @HCloward ?

2021-04-14 13:53 UTC, tlblessing requested changes
Global edit comments

2021-04-14 13:53 UTC, tlblessing commented on app/enterprise/2.1.x/go.md
> +Note: when installing go-pluginserver binary globally user will need to
```suggestion
Note: When installing the `go-pluginserver` binary globally, you  need to
```

2021-04-14 13:53 UTC, tlblessing commented on app/enterprise/2.1.x/go.md
> +enable go.mod support by using:
```suggestion
enable `go.mod` support:
```

2021-04-14 17:29 UTC, tlblessing requested changes
made comments to other versions in this PR, need to check on 2.3.x and 2.4.x now. File is no longer go.md in those versions but is now external. Also this information needs to be ported to the enterprise side. Will add this PR to my pending ticket.

2021-04-14 17:29 UTC, tlblessing commented on app/enterprise/2.2.x/go.md
> +Note: when installing go-pluginserver binary globally user will need to
```suggestion
Note: When installing the `go-pluginserver` binary globally, you  need to
```

2021-04-14 17:29 UTC, tlblessing commented on app/gateway-oss/2.1.x/go.md
> +Note: when installing go-pluginserver binary globally user will need to
```suggestion
Note: When installing the `go-pluginserver` binary globally, you  need to
```

2021-04-14 17:29 UTC, tlblessing commented on app/gateway-oss/2.1.x/go.md
> +enable go.mod support by using:
```suggestion
enable `go.mod` support:
```

2021-04-14 17:29 UTC, tlblessing commented on app/gateway-oss/2.2.x/go.md
> +Note: when installing go-pluginserver binary globally user will need to
```suggestion
Note: When installing the `go-pluginserver` binary globally, you  need to
```

2021-04-14 17:29 UTC, tlblessing commented on app/gateway-oss/2.2.x/go.md
> +enable go.mod support by using:
```suggestion
enable `go.mod` support:
```

2021-04-14 17:56 UTC, fffonion commented
The section on "how to build go-pluginserver" is removed in the external-plugins.md in 2.3/2.4, as now the preferred way to develop and build Go plugins is using the embedded server, which doesn't need the standalone go-pluginserver to built. @tlblessing

2021-04-14 20:54 UTC, tlblessing approved these changes

2021-04-14 20:58 UTC, tlblessing commented
There is a broken redirect that was fixed in other versions yesterday. Will fix.

> The section on "how to build go-pluginserver" is removed in the external-plugins.md in 2.3/2.4, as now the preferred way to develop and build Go plugins is using the embedded server, which doesn't need the standalone go-pluginserver to built. @tlblessing

@fffonion I should've remembered that.

2021-04-14 21:54 UTC, tlblessing commented
@fffonion can you rebase your PR so it will pick up the redirect fix? Then you can go ahead and merge after a successful build. Thank you for the PR!

2021-04-15 06:28 UTC, fffonion commented
@tlblessing  Sure just rebased : )

2021-04-15 15:17 UTC, merged