[DOCU-1408] Extending cert validity period in Konnect
Kong/docs.konghq.com pull request #2798
Opened 2021-04-16 21:44 UTC by lena-larionova

### Review
Doc team reviewers: this may or may not go out this week. Please sync with Jason to find out for sure.
You may also need to change the date. 

### Summary
Updating cert validity period/expiration time.

### Reason
https://konghq.atlassian.net/browse/DOCU-1408

### Testing
TBA

2021-04-16 21:45 UTC, artomal approved these changes

2021-04-19 14:36 UTC, tlblessing requested changes
minor suggested style edits

2021-04-19 14:36 UTC, tlblessing commented on app/konnect/runtime-manager/renew-certificates.md
> +* The runtime will stop receiving configuration updates from
```suggestion
* The runtime stops receiving configuration updates from
```

use present not future tense whenever possible

2021-04-19 14:36 UTC, tlblessing commented on app/konnect/runtime-manager/renew-certificates.md
> +* The runtime will stop sending Vitals and usage data to the control plane
```suggestion
* The runtime stops sending Vitals and usage data to the control plane
```

2021-04-19 14:37 UTC, tlblessing approved these changes

2021-05-12 22:11 UTC, merged