Expand example content for extended markdown usage
Kong/docs.konghq.com pull request #2819
Opened 2021-04-28 16:43 UTC by ksubburayalu

Expand example content for extended markdown usage for clarity.

### Review

@reviewer

### Summary

### Reason

### Testing

2021-04-29 15:23 UTC, tlblessing requested changes
Thanks for the PR @ksubburayalu. Some suggested edits for correct grammar.

2021-04-29 15:23 UTC, tlblessing commented on app/enterprise/2.3.x/developer-portal/theme-customization/markdown-extended.md
> +1. Create a markdown file for your Dev Portal documentation. The markdown file, for example `markdown-example.md` needs to be added under `content` folder. Add your markdown content, refer [Markdown
```suggestion
1. Create a markdown file for your Dev Portal documentation. The markdown file, for example `markdown-example.md`, needs to be added under the `content` folder. Add your markdown content. Refer to the [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/). The example below shows some basic markdown syntax.
```

2021-04-29 17:17 UTC, Bradamant3 commented
Hey folks, please hold off on approving/merging. The actual markdown example changes need fixing up too, I'll get to them after I'm done with bintray migration for Mesh. Thanks for the English fixes, @tlblessing !

2021-04-29 20:21 UTC, Bradamant3 commented
@tlblessing I edited the English a little differently bc I needed to pull the branch down to fix up the markdown, too. PTAL!

2021-04-29 22:02 UTC, ksubburayalu commented
Yes, this was done based on a customer issue. Refer the ticket 21753 that I have adde as part of the branch name as well. 
Thanks

2021-05-03 19:55 UTC, ksubburayalu commented
Docs team, can this be merged? Any other open items to be addressed? Thanks

2021-05-06 14:50 UTC, Bradamant3 approved these changes
LGTM but I pushed a commit so can I do this?

2021-05-06 14:50 UTC, merged