feat(external-plugins) add guide on testing with js plugins
Kong/docs.konghq.com pull request #2868
Opened 2021-05-19 08:30 UTC by fffonion

### Review

@reviewer

### Summary

### Reason

### Testing

2021-05-19 12:27 UTC, tlblessing requested changes
Thank you for the PR @fffonion. Will you be updating the OSS side as well?

2021-05-19 12:27 UTC, tlblessing commented on app/enterprise/2.4.x/external-plugins.md
> +User will first install `jest` as a development dependency, and add `test` script in package.json:
```suggestion
Install `jest` as a development dependency, and add  the `test` script in `package.json`:
```

2021-05-19 12:27 UTC, tlblessing commented on app/enterprise/2.4.x/external-plugins.md
> +package.json will have a content similar to following:
```suggestion
The `package.json` has content similar to the following:
```

2021-05-19 12:27 UTC, tlblessing commented on app/enterprise/2.4.x/external-plugins.md
> +for example on how to write test using `jest`.
```suggestion
for examples on how to write test using `jest`.
```

2021-05-19 13:27 UTC, fffonion commented
@tlblessing Yes that will apply on both sides, I will copy paste the change to OSS.

2021-05-27 16:23 UTC, tlblessing commented
Direct review links:

https://deploy-preview-2868--kongdocs.netlify.app/enterprise/2.4.x/external-plugins/#testing

2021-05-27 16:24 UTC, tlblessing approved these changes
Thank you @fffonion !

2021-05-27 16:24 UTC, merged