[DOCU-2079] Gateway request count report
Kong/docs.konghq.com pull request #3459
Opened 2021-12-04 00:59 UTC by lena-larionova

### Summary

Documentation for the `/license/report` endpoint.
* Adding entries into the existing Admin API `/licenses/` doc: reference entry with breakdown of the fields and what they mean, and an entry in the example doc.
  * The example doc entry seems arbitrary - it's the exact same information, just formatted differently. I don't know that it provides much value, but don't want to address that in this PR - it's a bigger problem.
  * Switched the order of a couple of other entries to place the two "List" actions together.

### Reason
Documentation for https://github.com/Kong/kong-ee/pull/2761.

### Testing
TBA

2021-12-04 01:06 UTC, lena-larionova commented
@locao I've added a doc draft for your request count feature for 2.7, but I'm concerned: I added the doc to the existing [Licenses Admin API page](https://deploy-preview-3459--kongdocs.netlify.app/gateway/2.7.x/admin-api/licenses/reference/), but the endpoint you've added is off of `/license/`, not `/licenses/`. Does it need to have its own doc page? Is the similarity of those endpoint names going to be confusing?

2021-12-06 12:17 UTC, locao commented
> Does it need to have its own doc page? 

It does have its own doc page: https://deploy-preview-3459--kongdocs.netlify.app/gateway/2.7.x/plan-and-deploy/licenses/report/. I will add the changes to this page, sorry for overlooking it.

2021-12-06 17:59 UTC, lena-larionova commented
@locao it seems odd that we didn't previously have a page for this endpoint in the Admin API doc. I think we should still keep it where I added, if you agree? As well as the page that you updated.

2021-12-06 18:17 UTC, locao requested changes

2021-12-06 18:17 UTC, locao commented on app/gateway/2.7.x/admin-api/licenses/reference.md
> +<div class="endpoint get">/licenses/report</div>
```suggestion
<div class="endpoint get">/license/report</div>
```

2021-12-06 18:17 UTC, locao commented on app/gateway/2.7.x/admin-api/licenses/reference.md
> +<div class="endpoint get">/licenses/report</div>
I think it is not super-odd to not have this documented before, this endpoint was used only when Kong representatives asked customers to send their usage report if I understood correctly. But as this is available we should document it and I agree with you, let's keep it with the other license manipulation docs (with this small fix).

2021-12-06 18:28 UTC, locao approved these changes

2021-12-06 22:27 UTC, GayleNeumann approved these changes
LGTM

2021-12-07 21:50 UTC, merged