[DOCU-2121] Add Alternate OpenAPI Renderer page
Kong/docs.konghq.com pull request #3700
Opened 2022-02-22 21:33 UTC by falondarville

### Summary

Add instructions for how to render Stoplight and Redoc from OpenAPI spec docs in Dev Portal. 

### Reason

Addresses [DOCU-2121](https://konghq.atlassian.net/browse/DOCU-2121)

### Testing

Link TBA.

2022-02-23 19:04 UTC, lena-larionova reviewed
Re: the linking to the spec - it looks like we don't generate /latest/ URLs for files that aren't `.md`. That's not great. I just checked with the `statsd.rules.yaml` file: 

* This URL is broken: https://docs.konghq.com/gateway/latest/statsd.rules.yaml 
* This URL works: https://docs.konghq.com/gateway/2.7.x/statsd.rules.yaml

Tl;dr, this is a bigger issue that you don't need to fix here, but obviously we still need a working link. 

My suggestion is to create a separate folder in the `/app` directory instead and call it `examples` (so your path will be `/app/examples/<filename>.html`). Or maybe `code-snippets` instead of `examples`? What do you think?

2022-03-03 21:21 UTC, falondarville commented
I updated the following:
1. Create `code-snippets` folder in `/app`
2. Move `spec-renderer.html` and `statsd.rules.yaml` to `code-snippets` folder
3. Update the links to the two aforementioned files 
4. Add the same content to 2.8.x

2022-03-03 21:57 UTC, lena-larionova requested changes

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.7.x/developer-portal/theme-customization/alternate-openapi-renderer.md
> +1. In `spec.renderer.html`, replace all of the current content with the content from this [spec-renderer.html](../../../code-snippets/spec-renderer.html) file. Doing so adds options for [Stoplight](h
```suggestion
1. In `spec.renderer.html`, replace all of the current content with the content from this [spec-renderer.html](/code-snippets/spec-renderer.html) file. Doing so adds options for [Stoplight](https://meta.stoplight.io/docs/platform/ZG9jOjIwNjk2MQ-welcome-to-the-stoplight-docs) and [Redoc](https://github.com/Redocly/redoc) layouts.
```
The URL is relative to the `app` folder, so you just need this.

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
> +[statsd.rules.yaml](../../../code-snippets/statsd.rules.yaml/statsd.rules.yaml).
```suggestion
[statsd.rules.yaml](/code-snippets/statsd.rules.yaml).
```

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.8.x/developer-portal/theme-customization/alternative-openapi-renderer.md
> +1. In `spec.renderer.html`, replace all of the current content with the content from this [spec-renderer.html](../../../code-snippets/spec-renderer.html) file. Doing so adds options for [Stoplight](h
```suggestion
1. In `spec.renderer.html`, replace all of the current content with the content from this [spec-renderer.html](/code-snippets/spec-renderer.html) file. Doing so adds options for [Stoplight](https://meta.stoplight.io/docs/platform/ZG9jOjIwNjk2MQ-welcome-to-the-stoplight-docs) and [Redoc](https://github.com/Redocly/redoc) layouts.
```

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.7.x/developer-portal/theme-customization/alternate-openapi-renderer.md
> +Through Kong Manager, use the Dev Portal [Editor](/gateway/latest/developer-portal/using-the-editor) to customize how your API specs render in your Dev Portal.
```suggestion
Through Kong Manager, use the Dev Portal [Editor](/gateway/{{page.kong_version}}/developer-portal/using-the-editor) to customize how your API specs render in your Dev Portal.
```

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.8.x/developer-portal/theme-customization/alternative-openapi-renderer.md
> +Through Kong Manager, use the Dev Portal [Editor](/gateway/latest/developer-portal/using-the-editor) to customize how your API specs render in your Dev Portal.
```suggestion
Through Kong Manager, use the Dev Portal [Editor](/gateway/{{page.kong_version}}/developer-portal/using-the-editor) to customize how your API specs render in your Dev Portal.
```

2022-03-03 21:57 UTC, lena-larionova commented on app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
> +[statsd.rules.yaml](../../../code-snippets/statsd.rules.yaml/statsd.rules.yaml).
Can you make this change to the 2.8 version also?

2022-03-03 22:29 UTC, lena-larionova reviewed
Looks like the filename isn't quite right in 2.8.x: `alternative-openapi-renderer.md`

All the links are looking for `alternate-openapi-renderer.md`

2022-03-04 00:13 UTC, lena-larionova approved these changes
LGTM!

2022-03-04 17:26 UTC, merged