fix(mesh): add CORS header to /mesh/latest_version
Kong/docs.konghq.com pull request #3714
Opened 2022-02-25 08:24 UTC by lahabana

### Summary

Mesh tooling relies on this file to figure out the latest released version.
This is used in multiple places including the UI.
add the netlify header needed to be able to do CROSS ORIGIN on this file

### Testing
TODO once preview is there

2022-02-25 11:10 UTC, lahabana commented
Ok I'm so dumb at Ruby I'd love some help to make my rspec work

2022-02-25 13:59 UTC, michaelbeaumont reviewed
The "you have an update" display is universally broken without this change?

2022-03-04 16:35 UTC, mheap requested changes
Could you remove the changes in the `spec` directory? I'll test in the review app and add a playwright test once #3744 is merged

2022-03-04 21:09 UTC, mheap approved these changes

2022-03-04 21:09 UTC, merged