Update Portal Auth flow
Kong/docs.konghq.com pull request #3791
Opened 2022-03-28 16:10 UTC by mheap

### Summary
Update Portal Auth flow with the following changes:

* Setting a password now occurs after email validation
* Add more information about manual/automatic approval of developers
* Update screenshots to the new design
* Note that if you try to register multiple times, you'll get an email confirming the status of your account

There are copy changes I'd make to this section, but in the interests of small PRs I've left as much of the existing content as I could as-is. Once this PR is merged we can discuss reworking the text as a standalone PR.

### Reason
New release

### Testing

2022-03-28 17:28 UTC, lena-larionova requested changes

2022-03-28 17:28 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
> +    You’ll receive an email to confirm your email address and to set a password via the link inside the email. After you have confirmed your email address and set a password, you’ll be able to log in
```suggestion
    After you have confirmed your email address and set a password, you’ll be able to log into the Dev Portal once your account admin has approved your request. 
```
Moving this sentence to previous step, as it sounds out of order.
Normally I'd shy away from future tense, but I think in this case it makes sense, as you might be waiting for approval.

2022-03-28 17:28 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
>  4. Check your email for registration confirmation.
```suggestion
4. You should receive an email to confirm your email address and set a password via the link inside the email. Click the verification link in the email.
```
Moved from step 5.

2022-03-28 17:28 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
> +If your admin has auto-approve enabled, you’ll be immediately able to log into the Dev Portal. Learn how to [set up auto-approval for developer access as an admin](/konnect/dev-portal/access-and-appr
```suggestion
If your admin has auto-approve enabled, you can log into the Dev Portal immediately after setting a password. Learn how to [set up auto-approval for developer access as an admin](/konnect/dev-portal/access-and-approval/auto-approve-devs-apps/).
```

2022-03-28 17:28 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
> +All manually approved developers will be notified via email upon gaining access to the Dev Portal. Learn how to [manually approve developer access as an admin](/konnect/dev-portal/access-and-approval
```suggestion
If auto-approve is not enabled, an admin has to review and approve your request manually. All manually approved developers are notified via email upon gaining access to the Dev Portal. Learn how to [manually approve developer access as an admin](/konnect/dev-portal/access-and-approval/manage-devs/#approve-dev-reg).
```

2022-03-29 21:03 UTC, lena-larionova requested changes

2022-03-29 21:03 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
> +You should receive an email to confirm your email address. Click the verification link in the email.
```suggestion
   You should receive an email to confirm your email address. Click the verification link in the email.
```

2022-03-29 21:03 UTC, lena-larionova commented on app/konnect/dev-portal/access-and-approval/dev-reg.md
> +5. After you have confirmed your email, you will be asked to set a password for your account.
```suggestion
5. Set a password for your account.
```
Missed this. It's implied that it's after approval, since it's the next step.

2022-03-30 15:52 UTC, lena-larionova approved these changes

2022-03-30 15:54 UTC, lena-larionova commented
@mheap I can't believe I just noticed this - this PR is open against `main`, but it should be targeting `konnect`. Can you please rebase and retarget?

2022-03-30 18:25 UTC, mheap commented
@lena-larionova Now targeting `konnect`

Once @sichvoge reviews I'll hit merge

2022-04-01 09:10 UTC, sichvoge commented
Only a small request to fix, but otherwise LGTM. We also found a potential bug as I went through the docs, trying out whats written there :) So thanks! :D

2022-04-01 09:10 UTC, sichvoge requested changes

2022-04-01 09:28 UTC, mheap commented on app/konnect/dev-portal/access-and-approval/manage-devs.md
> +* **Approved**
```suggestion
**Approved**
```

2022-04-01 10:11 UTC, merged