[FT-1816] new enterprise Validation plugin
Kong/docs.konghq.com pull request #3902
Opened 2022-05-03 20:35 UTC by KongSteve

### Summary
New Validation plugin documentation

### Reason
https://konghq.atlassian.net/browse/FT-1816

2022-06-01 11:09 UTC, mheap requested changes

2022-06-01 11:09 UTC, mheap commented on app/_hub/kong-inc/oas-validation/index.md
> +{% navtab HTTPie %}
We can remove HTTPie if we want to simplify

2022-06-07 12:15 UTC, mheap commented
Moving back to draft as it's targeted for 3.1

2022-09-28 23:12 UTC, KongSteve commented on app/_hub/kong-inc/oas-validation/index.md
> +---
@lena-larionova - this plugin is targeted for 3.1. Tried the link above re icon but doesn't work. Can you let me know how we kick off the icon thing?

2022-09-29 08:18 UTC, vm-001 commented on app/_hub/kong-inc/oas-validation/index.md
> +desc: Validate HTTP requests and responses based on an OpenApi 3.0 or Swagger API Specification
typo issue might be aware.

2022-11-04 17:00 UTC, lena-larionova commented on app/_hub/kong-inc/oas-validation/index.md
> +---
Gang Guo is working with the UX team on plugin icons now. We'll get a process in place for this going forward.

2022-11-10 07:02 UTC, windmgc commented
The OAS validation plugin document looks good to me, but I don't know why the 3.1 navigation page and mocking plugin related change are also in this PR.

@lena-larionova Can I change this PR from draft to "Ready for review"?

2022-11-10 21:56 UTC, lena-larionova commented
> The OAS validation plugin document looks good to me, but I don't know why the 3.1 navigation page and mocking plugin related change are also in this PR.

Had a rebase issue that's now resolved, they're gone now.

> Can I change this PR from draft to "Ready for review"?

Please do.

2022-11-16 21:56 UTC, lena-larionova approved these changes

2022-11-16 21:57 UTC, merged