Add Ruby Debug instructions
Kong/docs.konghq.com pull request #3920
Opened 2022-05-10 08:55 UTC by mheap

### Summary
Add instructions how to start a debug session for Jekyll with vscode

### Reason
It took a little while to work out, and we'll need it on multiple machines

### Testing
Follow the instructions locally

2022-05-13 20:49 UTC, Guaris commented
I can't get this to work. I get two errors at the same time. I have debug-1.5.0 installed globally. 
* `Couldn't start debug session (wait for 3034 ms). Please install debug.gem.` 
 
  if I `gem info debug` I get

```

docs % gem info debug

*** LOCAL GEMS ***

debug (1.5.0)
    Author: Koichi Sasada
    Homepage: https://github.com/ruby/debug
    Licenses: Ruby, BSD-2-Clause
    Installed at: /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0

    Debugging functionality for Ruby
```
 * `unix': too long unix socket path (111 bytes given but 104 bytes max) (ArgumentError)`
 
 ```
b:1116:in `unix': too long unix socket path (111 bytes given but 104 bytes max) (ArgumentError)
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.5.0/lib/debug/server.rb:470:in `accept'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.5.0/lib/debug/server.rb:49:in `block in activate'
```

I edited the launch.json file to point to my jekyll install at /usr/local/bin

2022-05-13 20:49 UTC, Guaris commented
I can't get this to work. I get two errors at the same time. I have debug-1.5.0 installed globally. 
* `Couldn't start debug session (wait for 3034 ms). Please install debug.gem.` 
 
  if I `gem info debug` I get

```

docs % gem info debug

*** LOCAL GEMS ***

debug (1.5.0)
    Author: Koichi Sasada
    Homepage: https://github.com/ruby/debug
    Licenses: Ruby, BSD-2-Clause
    Installed at: /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0

    Debugging functionality for Ruby
```
 * `unix': too long unix socket path (111 bytes given but 104 bytes max) (ArgumentError)`
 
 ```
b:1116:in `unix': too long unix socket path (111 bytes given but 104 bytes max) (ArgumentError)
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1116:in `unix_server_socket'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.5.0/lib/debug/server.rb:470:in `accept'
        from /Users/angel.guarisma@konghq.com/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.5.0/lib/debug/server.rb:49:in `block in activate'
```

I edited the launch.json file to point to my jekyll install at /usr/local/bin

2022-05-13 21:09 UTC, lena-larionova commented
I get the same error where it doesn't find the `debug` gem, but with `gem info debug`, it finds the gem no problem. 

The other issue I run into is that it can't find `bin/jekyll`:

<img width="1082" alt="Screen Shot 2022-05-13 at 1 59 09 PM" src="https://user-images.githubusercontent.com/54370747/168389797-921d76d9-bb74-472d-bd40-e0009793dc85.png">

2022-05-16 20:10 UTC, Guaris requested changes
comments above

2022-05-24 11:20 UTC, mheap commented
I've added some missing info around which plugin to install and how to make `bin/jekyll` appear. Could you try again, and if it's still not working we can pair + screenshare as it works on my machine after running `gem install debug`

2022-06-06 16:34 UTC, mheap commented
This was an issue with the unix socket path being too long. Setting `XDG_RUNTIME_DIR` resolves the issue (we could also set the `debugPort` value as an alternative)

2022-06-07 08:26 UTC, Guaris approved these changes

2022-06-07 09:08 UTC, merged