Adding New fields + fields from Kong OSS PR  8841
Kong/docs.konghq.com pull request #3965
Opened 2022-05-23 09:01 UTC by jeremyjpj0916

Related: https://github.com/Kong/kong/pull/8841

2022-06-02 14:55 UTC, Guaris requested changes

2022-06-02 14:55 UTC, Guaris commented on app/_hub/kong-inc/request-termination/2.0.x.md
> +Addition of the avert option, which prevents plugin execution when matched. Opposite from the trigger option
```suggestion
Added the `avert` option, this prevents plugin execution when matched. `avert` is like the opposite of the `trigger` option 
```

2022-06-02 15:04 UTC, jeremyjpj0916 commented
Agree on the word smithing.

2022-06-02 15:16 UTC, Guaris commented
> Agree on the word smithing.

This PR depends on this one right? https://github.com/Kong/kong/pull/8841

2022-06-02 15:32 UTC, jeremyjpj0916 commented
@Guaris Correct. Unit tests failing for odd reason, one error was an unrelated postgres and the other error idk how my SRC changes could have even caused that failure after studying it a few times.

2022-06-02 18:44 UTC, Guaris commented
If you could ping me when that other PR gets merged. I'll merge this one then.

2022-11-14 20:21 UTC, Guaris commented
I'm closing this PR on account of the other PR being closed 
https://github.com/Kong/kong/pull/8841

please reopen this PR when you are ready!

2022-11-14 20:21 UTC, closed without merging