add https_verify to control if OPA certificate is verified
Kong/docs.konghq.com pull request #3977
Opened 2022-05-27 08:15 UTC by outsinre

### Summary

Add `https_verify` parameter to the `opa` plugin.

### Reason

The `opa` plugin now supports secure connection. Related Kong EE PR: https://github.com/Kong/kong-ee/pull/3271

`https_verify` parameter controls if the OPA certificate is verified.

2022-05-27 16:48 UTC, Guaris requested changes

2022-05-27 16:48 UTC, Guaris commented on app/_hub/kong-inc/opa/_index.md
> +        Whether the OPA certificate will be verified according to the CA certificates specified in [lua_ssl_trusted_certificate](https://docs.konghq.com/gateway/latest/reference/configuration).
```suggestion
       If set to true, the OPA certificate will be verified according to the CA certificates specified in [lua_ssl_trusted_certificate](https://docs.konghq.com/gateway/latest/reference/configuration).
```

2022-06-01 10:58 UTC, mheap commented
@outsinre Could you rebase on `release/gateway-3.0`?

2022-06-01 11:08 UTC, outsinre commented
> @outsinre Could you rebase on `release/gateway-3.0`?

Sure, will do

2022-06-22 15:24 UTC, Guaris commented
This will need to be rebased

2022-06-30 13:33 UTC, Guaris commented
Any update on this? Do you need any help?

2022-06-30 13:35 UTC, outsinre commented
> Any update on this? Do you need any help?

@Guaris, thanks for the notice. Just rebased!

2022-06-30 17:27 UTC, Guaris commented
Is this still a draft?

2022-06-30 17:33 UTC, Guaris commented
We can't merge this into the Gateway 3.0 branch because it would cause conflicts in that branch. Could I ask you to reset the head of this branch to the tip of Gateway-3.0, and cherry-pick your commits onto that. Essentially undoing the step where you rebased over the main branch. Alternatively, you could close this PR, create a new branch from the Gateway 3.0 branch, and add your docs again. I'm happy to help you with this on Slack if you need it.

2022-07-12 13:57 UTC, Guaris commented
I fixed all of the branch issues for you :)

2022-08-09 08:36 UTC, mayocream commented
@outsinre please rebase and clean up this PR.

2022-08-10 06:17 UTC, mayocream approved these changes

2022-08-10 06:40 UTC, mayocream commented
@Guaris Could you help on merging this one? Thanks!

2022-08-10 06:50 UTC, mayocream approved these changes

2022-08-18 02:23 UTC, outsinre commented
The Kong PR is already merged. Waiting for release.

2022-08-18 21:38 UTC, merged