Update data.lua
Kong/docs.konghq.com pull request #3982
Opened 2022-05-27 19:03 UTC by Guaris

### Summary
Fixes an issue with links in `reference/configuration` rendering like this. 
![image](https://user-images.githubusercontent.com/23319190/170774320-5f791d78-a5bd-4151-9e8c-60d29b98072a.png)

### Testing
Adding soon

2022-05-27 21:19 UTC, lena-larionova requested changes

2022-05-27 21:19 UTC, lena-larionova commented on app/gateway/2.8.x/reference/configuration.md
> +directives, see the [official documentation](https://nginx.org/en/docs/beginners_guide.html#conf_structure).
```suggestion
directives, see the [Nginx reference](https://nginx.org/en/docs/beginners_guide.html#conf_structure).
```
Slightly more descriptive text. Ideally, you want the link text to tell the reader what they're clicking on - especially important for accessibility/someone tabbing through the page. I think it's useful for SEO also.

2022-05-27 21:19 UTC, lena-larionova commented on app/gateway/2.8.x/reference/configuration.md
> +For a list of Nginx directives, see the [official documentation](https://nginx.org/en/docs/dirindex.html).
```suggestion
For a list of Nginx directives, see the [Nginx directives index](https://nginx.org/en/docs/dirindex.html).
```

2022-05-27 21:19 UTC, lena-larionova commented on autodoc-conf-ee/data.lua
> +directives, see the [official documentation](https://nginx.org/en/docs/beginners_guide.html#conf_structure).
```suggestion
directives, see the [Nginx reference](https://nginx.org/en/docs/beginners_guide.html#conf_structure).
```

2022-05-27 21:19 UTC, lena-larionova commented on autodoc-conf-ee/data.lua
> +For a list of Nginx directives, see the [official documentation](https://nginx.org/en/docs/dirindex.html).
```suggestion
For a list of Nginx directives, see the [Nginx directives index](https://nginx.org/en/docs/dirindex.html).
```

2022-05-30 16:35 UTC, mheap approved these changes

2022-05-31 13:17 UTC, merged