Update: Kong Moesif Plugin versions and docs
Kong/docs.konghq.com pull request #4004
Opened 2022-06-09 01:44 UTC by dgilling

### Summary
Updates to Kong Moesif plugin docs
Add: Compatible versions
Update: How to install steps
Add: Missing Config options

### Reason
Was out of date

### Testing
Markdown tested 

 review:copyedit

2022-06-09 15:35 UTC, Guaris requested changes

2022-06-09 15:35 UTC, Guaris commented on app/_hub/moesif/kong-plugin-moesif/_index.md
> +      description: Request or response header to use to identify the User in Moesif.
```suggestion
      description: Request or response header used to identify the User in Moesif.
```

2022-06-09 15:35 UTC, Guaris commented on app/_hub/moesif/kong-plugin-moesif/_index.md
> +      description: Request or response header to use to identify the Company (Account) in Moesif.
```suggestion
      description: Request or response header used to identify the Company (Account) in Moesif.
```

2022-06-09 15:35 UTC, Guaris commented on app/_hub/moesif/kong-plugin-moesif/_index.md
> +### 1. Install the Moesif plugin
```suggestion
### Install the Moesif plugin
```

2022-06-10 02:11 UTC, dgilling commented
Thanks for the feedback @Guaris . Accepted the suggested changes.

2022-06-10 15:56 UTC, Guaris commented
I'm closing this in favor of #4007 so I can address some of the changes without pushing directly up to your fork.

2022-06-10 16:08 UTC, Guaris requested changes
I can't push to your fork otherwise I would have done this for you. Could you please also add the word `Moesif` to `dictionary.txt` so that it resembles between `Mockbin` and `MongoDB`?
```
Luarocks
minikube
Mockbin
Moesif
MongoDB
namespace
```

2022-06-10 16:08 UTC, Guaris commented on app/_hub/moesif/kong-plugin-moesif/_index.md
>  If the luarocks utility is installed in your system (this is likely the case if you used one of the official installation packages), you can install the 'rock' in your LuaRocks tree (a directory in w
```suggestion
If the LuaRocks utility is installed in your system (this is likely the case if you used one of the official installation packages), you can install the 'rock' in your LuaRocks tree (a directory in which LuaRocks installs Lua modules).
```

2022-06-10 16:08 UTC, Guaris commented on app/_hub/moesif/kong-plugin-moesif/_index.md
> +After the luarock is installed, restart Kong before enabling the plugin
```suggestion
After LuaRocks is installed, restart Kong before enabling the plugin
```

2022-06-10 19:37 UTC, dgilling commented
@Guaris , we accepted the changes but were confused on the suggestion around `dictionary.txt`. We don't see any `dictionary.txt` file in this repo. What should we be updating?

2022-06-10 20:18 UTC, Guaris commented
> @Guaris , we accepted the changes but were confused on the suggestion around `dictionary.txt`. We don't see any `dictionary.txt` file in this repo. What should we be updating?

The dictionary file is at: 
`.github/styles/kong/dictionary.txt`

Here is a link to the file in your branch: 
https://github.com/Moesif/docs.konghq.com/blob/main/.github/styles/kong/dictionary.txt

2022-06-10 20:26 UTC, dgilling commented
@Guaris . Thank you. Just added.

2022-06-10 20:44 UTC, Guaris commented
Okay, sorry for the confusion and thank you for your patience, I'm closing this PR in favor of: https://github.com/Kong/docs.konghq.com/pull/4008  which is passing and ready to be merged. This will go in first thing Monday morning.

2022-06-10 20:45 UTC, closed without merging