Vitals page changes
Kong/docs.konghq.com pull request #4018
Opened 2022-06-14 20:42 UTC by Guaris

### Summary
Changes the upper bound to 30 days, and adds the time interval chart. 

### Reason
https://konghq.atlassian.net/browse/DOCU-2227
### Testing
coming soon

2022-06-14 20:43 UTC, Guaris commented on app/konnect/vitals/index.md
> +To see historical data for a range greater than 30 days, or to customize the
Is this still true? Can the range be greater than 30 days?

2022-06-16 14:14 UTC, sichvoge approved these changes

2022-06-22 00:03 UTC, lena-larionova commented on app/konnect/vitals/index.md
> +Last 15 minutes | Data is aggregated in ten seconds increments.
```suggestion
Last 15 minutes | Data is aggregated in ten second increments.
```

2022-06-30 14:26 UTC, cloudjumpercat requested changes

2022-06-30 14:26 UTC, cloudjumpercat commented on app/konnect/vitals/analyze.md
> +    last 5 minutes to the last 30 days.
```suggestion
    last five minutes to the last 30 days.
```

2022-06-30 14:26 UTC, cloudjumpercat commented on app/konnect/vitals/index.md
> +title: Introduction to Monitoring Health with Vitals
```suggestion
title: Introduction to monitoring health with Vitals
```

2022-06-30 14:26 UTC, cloudjumpercat commented on app/konnect/vitals/index.md
> +Last 3 hours | Data is aggregated in one minute increments.
```suggestion
Last three hours | Data is aggregated in one minute increments.
```

2022-06-30 14:26 UTC, cloudjumpercat commented on app/konnect/vitals/index.md
> +Last 6 hours | Data is aggregated in ten minute increments.
```suggestion
Last six hours | Data is aggregated in ten minute increments.
```

2022-06-30 14:26 UTC, cloudjumpercat commented on app/konnect/vitals/index.md
> +Last 7 days | Data is aggregated in one hour increments.
```suggestion
Last seven days | Data is aggregated in one hour increments. 
```

2022-06-30 17:25 UTC, Guaris commented on app/konnect/vitals/index.md
> +title: Introduction to monitoring health with Vitals
```suggestion
title: Introduction to Monitoring Health with Vitals
```

2022-06-30 20:14 UTC, cloudjumpercat approved these changes

2022-07-01 13:14 UTC, merged