Update plugin template file
Kong/docs.konghq.com pull request #4045
Opened 2022-06-22 23:34 UTC by lena-larionova

### Summary
Added the following possible settings:

* Tiers: Enterprise or Plus
* Konnect compatibility
* Ability to disable Konnect UI and Kong Manager UI examples
* Minimum and maximum version (for single-sourcing)

Also added a changelog section and a renamed the first heading to "Usage" for consistency with most plugins.

### Reason
We've had a few new plugin settings added to our templates, and the compatibility filter no longer works in the same way for new plugins. I'm working on some new plugins now and realized this template was very out of date.

### Testing
Check the file on the branch. This file doesn't appear in the netlify preview.

2022-06-23 14:34 UTC, cloudjumpercat requested changes

2022-06-23 14:34 UTC, cloudjumpercat commented on app/_hub/_init/my-extension/_index.md
>    k8s_examples:
Should this (and all boolean examples) be like this to match what we have for cloud, enterprise, and plus? 
```suggestion
  k8s_examples: # Boolean.
```

2022-06-24 16:58 UTC, lena-larionova commented
@cloudjumpercat could you take another look?

2022-06-24 17:21 UTC, cloudjumpercat approved these changes

2022-06-24 17:48 UTC, merged