Tweaks KIC install
Kong/docs.konghq.com pull request #4061
Opened 2022-06-27 15:04 UTC by rspurgeon

### Summary

Moves the NOTE warning up to the proper section related to the instruction
Adds code formatting to guidance as well

### Reason
When following this guide the first time, I got tripped up by what the "NOTE" in this
docs page is telling me. But I didn't notice it because it was located at the bottom of the
doc and not in proximity to the instruction I was runnig.

### Testing
Built docs locally and verified local version of the page

2022-06-28 14:00 UTC, cloudjumpercat requested changes

2022-06-28 14:00 UTC, cloudjumpercat commented on app/gateway/2.8.x/install-and-run/kubernetes.md
> +1. Finally, invoke a test request:
```suggestion
1. Invoke a test request:
```

2022-06-29 18:54 UTC, rspurgeon commented
Thanks @cloudjumpercat , suggestions accepted and committed 👍

2022-06-29 20:00 UTC, cloudjumpercat approved these changes

2022-06-29 20:04 UTC, merged