DOCU-2377: Removes prompts from instruction commands
Kong/docs.konghq.com pull request #4074
Opened 2022-06-30 16:25 UTC by rspurgeon

Additionally:
* attempts to standardize some of the layout of command -> expected results to
match what was started in https://github.com/Kong/docs.konghq.com/pull/4064
* Adds a CTA at the bottom of the guide
* updates command expected output to more modern responses

### Summary

### Reason
Removes the command prompts from the instruction commands, allows a user to more easily copy and paste the instructions

### Testing
Locally built and viewed the changed page

2022-06-30 17:26 UTC, rspurgeon commented
Incorrectly reference DOCU-2377, instead this is related to DOCU-2369

2022-07-01 14:41 UTC, cloudjumpercat requested changes

2022-07-01 14:41 UTC, cloudjumpercat commented on src/kubernetes-ingress-controller/guides/getting-started.md
>  a HTTP 404 Not Found.
```suggestion
a HTTP `404 Not Found` status code.
```

2022-07-01 14:41 UTC, cloudjumpercat commented on src/kubernetes-ingress-controller/guides/getting-started.md
> +* To learn how to secure proxied routes, check out the [ACL and JWT Plugins Guide](/kubernetes-ingress-controller/{{page.kong_version}}/guides/configure-acl-plugin/)
```suggestion
* To learn how to secure proxied routes, see the [ACL and JWT Plugins Guide](/kubernetes-ingress-controller/{{page.kong_version}}/guides/configure-acl-plugin/).
```

2022-07-01 14:41 UTC, cloudjumpercat commented on src/kubernetes-ingress-controller/guides/getting-started.md
> +* The [External Services Guide](/kubernetes-ingress-controller/{{page.kong_version}}/guides/using-external-service/) explains how to proxy services outside of your Kubernetes cluster
```suggestion
* The [External Services Guide](/kubernetes-ingress-controller/{{page.kong_version}}/guides/using-external-service/) explains how to proxy services outside of your Kubernetes cluster.
```

2022-07-01 14:55 UTC, merged