docs(acl) fix an Admin API usage error
Kong/docs.konghq.com pull request #4078
Opened 2022-07-01 08:14 UTC by outsinre

### Summary

The Admin API call to associate a customer with the ACL plugin is incorrect. Misleading users.

### Reason

Wrong Admin API usage.

2022-07-01 14:46 UTC, cloudjumpercat requested changes

2022-07-01 14:46 UTC, cloudjumpercat commented on app/_hub/kong-inc/acl/_index.md
>  `CONSUMER`: The `username` property of the Consumer entity to associate the credentials to.
```suggestion
`CONSUMER`: The `username` property of the consumer entity to associate the credentials with.
```

2022-07-06 20:03 UTC, Guaris approved these changes

2022-07-06 20:04 UTC, Guaris approved these changes

2022-07-06 20:06 UTC, merged