Add UBI install instructions to the correct doc
Kong/docs.konghq.com pull request #4081
Opened 2022-07-01 21:06 UTC by lena-larionova

### Summary
Original PR added changes to a doc that's not in use anymore: https://github.com/Kong/docs.konghq.com/pull/4024

Moving it into the latest documentation.

@curiositycasualty I had to split the commands out and add some placeholder values that'll pick up the correct latest version of the gateway. Let me know if it looks right.

Also - are there UBI-minimal packages for `kong-enterprise-edition`? I'm working off of the assumption that there is, but I'm not entirely sure if that's correct.

### Reason
Doc is in the wrong place.

### Testing
Tested locally. Netlify preview TBA.

Will need some help checking accuracy. In the preview, you can switch to the open-source version by clicking the toggle in the top right:
![Screen Shot 2022-07-01 at 2 05 59 PM](https://user-images.githubusercontent.com/54370747/176967869-9c83fb26-319c-4cfd-9436-a4195ab4375d.png)

Output looks like this:
![Screen Shot 2022-07-01 at 1 54 59 PM](https://user-images.githubusercontent.com/54370747/176967796-a65034f3-e89a-4bce-8c90-aa91731b3502.png)

2022-07-01 21:32 UTC, curiositycasualty commented on app/_includes/md/rpm.md
> +<!-- DO NOT UPDATE THIS FILE, IT'S FOR ARCHIVED CONTENT ONLY -->
This is helpful!

2022-07-01 21:34 UTC, curiositycasualty approved these changes

2022-07-01 21:35 UTC, lena-larionova commented on app/_includes/md/rpm.md
> +<!-- DO NOT UPDATE THIS FILE, IT'S FOR ARCHIVED CONTENT ONLY -->
Lesson learned for the future! 😬

2022-07-04 20:33 UTC, hutchic commented
@lena-larionova 

> are there UBI-minimal packages for kong-enterprise-edition

There are not but there's going to be as of 3.x is the goal. The direction we're going as of 3.x is minimal docker images that do not include utilities such as git / curl etc, based on minimal base images, with accompanying documentation for (re)building our images

2022-07-05 13:44 UTC, cloudjumpercat requested changes
Just a small branding update, other than that, LGTM!

2022-07-05 13:44 UTC, cloudjumpercat commented on app/gateway/2.8.x/install-and-run/rhel.md
> +    Installing directly using `rpm` is suitable for RedHat's [Universal Base Image](https://developers.redhat.com/blog/2020/03/24/red-hat-universal-base-images-for-docker-users) "minimal" variant. Yo
```suggestion
    Installing directly using `rpm` is suitable for Red Hat's [Universal Base Image](https://developers.redhat.com/blog/2020/03/24/red-hat-universal-base-images-for-docker-users) "minimal" variant. You will need to install Kong's dependencies separately via `microdnf`.
```

2022-07-06 21:02 UTC, merged