doc(keyring) reorder the structure, mention new options for Data Plane
Kong/docs.konghq.com pull request #4097
Opened 2022-07-07 04:59 UTC by fffonion

### Summary

### Reason

### Testing

2022-07-07 07:18 UTC, mayocream approved these changes
LGTM

2022-07-07 18:59 UTC, Guaris requested changes

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +This key pair will be provided to Kong in order to faciliate recovering, exporting and re-importing the keyring. The public `cert.pem` and private `key.pem` should be stored securely in accordance wi
```suggestion
This key pair will be provided to Kong in order to facilitate recovering, exporting, and re-importing the keyring. The public `cert.pem` and private `key.pem` should be stored securely in accordance with your existing secrets management policies. Details on secure storage of RSA key pairs are outside the scope of this documentation.
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +The generated private key `key.pem` is not required in Kong configuration and is not required to start Kong; please refer to [Disaster recovery](#disaster-recovery) for more information on how to use
```suggestion
The generated private key `key.pem` is not required to configure Kong, or to start Kong. Please refer to the [disaster recovery](#disaster-recovery) section for more information on how to use private keys in keyring management.
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +To use automatic backup of keyring materials, one need to configure `keyring_recovery_public_key`:
```suggestion
To use automatic backups for keyring materials, configure `keyring_recovery_public_key`:
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +`cluster` strategy supports the two disaster recovery strategies.
```suggestion
`cluster` strategy supports two disaster recovery strategies.
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +The keyring material is then encrypted with the public RSA key defined via the `keyring_recovery_public_key`
```suggestion
The keyring material is then encrypted with the public RSA key defined with the `keyring_recovery_public_key`
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +Kong configuration value in the database. The corresponding private key can be used to decrypt the Keyring material in the database:
```suggestion
Kong configuration value in the database. The corresponding private key can be used to decrypt the keyring material in the database:
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +The response contains a list of keys that were successfully recovered and that could not be recovered. Kong error log will contain the detailed reason on why those keys could not be recovered.
```suggestion
The response contains a list of keys that were successfully recovered and that could not be recovered. The Kong error log will contain the detailed reason why the keys could not be recovered.
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +Note that the user under which Kong worker processes run must have read access to the public and private keys in order to be able to perform keyring export and import operations. This user is defined
```suggestion
The user that the Kong worker process is running under must have read access to the public and private keys in order to be able to import and export keyrings. This user is defined with the `nginx_user` Kong configuration option. We recommend restricting access to these files, for example:
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +When testing, you can also set `keyring_blob_path` in kong.conf or `KONG_KEYRING_BLOB_PATH`
```suggestion
When testing, you can set `keyring_blob_path` in kong.conf or `KONG_KEYRING_BLOB_PATH`
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +Before going further, export the keyring. The exported material can be re-imported to the cluster in the event of an outage, or to restore a previously-deleted key:
```suggestion
Export the keyring. The exported material can be re-imported to the cluster in the event of an outage or to restore a previously-deleted key:
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +The response generated is an opaque blob containing the keyring, encrypted with
```suggestion
The response generated is an opaque blob containing the keyring. This blob is encrypted with
```

2022-07-07 18:59 UTC, Guaris commented on src/gateway/plan-and-deploy/security/db-encryption.md
> +a randomly-generated symmetric key. This random key is encrypted with the public
```suggestion
a randomly-generated symmetric key, which is encrypted with the public
```

2022-07-08 13:48 UTC, Guaris commented
thank you!

2022-07-08 13:48 UTC, merged