Feat/fti 4100 gcp vault
Kong/docs.konghq.com pull request #4144
Opened 2022-07-21 10:49 UTC by lokesh-chechani

### Summary

Added documentation for GCP Vault to Secret Management section in Kong Gateway 

### Reason
[FTI-4100](https://konghq.atlassian.net/browse/FTI-4100). In discussion with the product engineering team to ship this feature as part of gateway release v2.8.1.3. 

Slack discussion: https://kongstrong.slack.com/archives/C0223LNEQCB/p1658393569090289?thread_ts=1658213496.854579&cid=C0223LNEQCB

### Testing
Minor document update.

2022-07-25 14:02 UTC, Guaris submitted a review, later dismissed

2022-07-28 10:55 UTC, mayocream commented
Please hold, we are having a discussion about whether or not to put this feature into 2.8.x.

2022-07-28 15:27 UTC, Guaris commented
Okay

2022-07-29 01:44 UTC, khaikong commented
Can we get this reviewed too @Guaris 
https://github.com/Kong/docs.konghq.com/pull/4165

2022-07-29 06:43 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +{vault://gcp/my-secret-name/snap}
```suggestion
{vault://gcp/my-secret-name/foo?project_id=my_project_id}
{vault://gcp/my-secret-name/snap?project_id=my_project_id}
```

2022-07-29 06:43 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +{vault://gcp/my-secret-name/snap}
`?project_id` can also be ignored if `GCP_PROJECT_ID` env is set.

2022-07-29 06:43 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +  config.region="my_project_id" \
```suggestion
  config.project_id="my_project_id" \
```

2022-07-29 06:43 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +        "project_id": "project-last-hope"
```suggestion
        "project_id": "my_project_id"
```

2022-07-29 06:43 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +With the Vault entity in place, you can now reference the secrets. This allows you to drop the `KONG_VAULT_GCP_PROJECT_ID`
```suggestion
With the Vault entity in place, you can now reference the secrets. This allows you to drop the `GCP_PROJECT_ID`
```

2022-07-29 16:40 UTC, cloudjumpercat commented
Can someone tag me when all your changes are complete so I can review them? Thanks!

2022-07-29 19:29 UTC, hanshuebner commented
@kikito Please tag Diana when these changes are complete.

2022-07-29 20:01 UTC, kikito commented
I had to rebase this branch over `main`, otherwise reviews were too confusing. If you had a local copy, you might have to delete your local branch (`git checkout main && git branch -D feat/fti_4100_gcp_vault`) and re-clone (`git fetch --all && git switch feat/fti_4100_gcp_vault )

2022-07-29 20:02 UTC, kikito approved these changes

2022-07-29 20:03 UTC, kikito commented
I think the docs are good enough now, I have approved the PR. Tagging @cloudjumpercat as requested.

2022-07-29 20:43 UTC, cloudjumpercat requested changes

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md
> +> Kong Manager has currently no supports for configuring vault entities.
```suggestion
> Kong Manager currently doesn't support configuring vault entities.
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md
> +$ curl -i -X PUT http://<hostname>:8001/vaults/my-env-vault-1  \
```suggestion
$ curl -i -X PUT http://HOSTNAME:8001/vaults/my-env-vault-1  \
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/aws-sm.md
> +curl -i -X PUT http://<hostname>:8001/vaults/my-aws-sm-vault  \
```suggestion
curl -i -X PUT http://HOSTNAME:8001/vaults/my-aws-sm-vault  \
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/env.md
> +curl -i -X PUT http://<hostname>:8001/vaults/my-env-vault \
```suggestion
curl -i -X PUT http://HOSTNAME:8001/vaults/my-env-vault \
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +{{site.base_gateway}} will use the key to automatically authenticate
```suggestion
{{site.base_gateway}} uses the key to automatically authenticate
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +[documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to).
```suggestion
attached to the pod. For configuration information, read the [Workload
Identity configuration
documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to).
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +> With Workload Identity, setting the `GCP_SERVICE_ACCOUNT` is not necessary.
```suggestion
> With Workload Identity, setting the `GCP_SERVICE_ACCOUNT` isn't necessary.
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +To configure GCP secrets manager, the `GCP_SERVICE_ACCOUNT`
```suggestion
To configure GCP Secrets Manager, the `GCP_SERVICE_ACCOUNT`
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +Once the database has been initialized, a Vault entity can be created
```suggestion
Once the database is initialized, a Vault entity can be created
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +curl -i -X PUT http://<hostname>:8001/vaults/my-gcp-sm-vault \
```suggestion
curl -i -X PUT http://HOSTNAME:8001/vaults/my-gcp-sm-vault \
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +http -f PUT http://<hostname>:8001/vaults/my-gcp-sm-vault \
```suggestion
http -f PUT http://HOSTNAME:8001/vaults/my-gcp-sm-vault \
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
> +specified to access the secrets.
```suggestion
When you use the Vault entity, you no longer need to specify the GCP project ID to access the secrets.
```

2022-07-29 20:43 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md
> +curl -i -X PUT http://<hostname>:8001/vaults/my-hashicorp-vault \
```suggestion
curl -i -X PUT http://HOSTNAME:8001/vaults/my-hashicorp-vault \
```

2022-07-29 20:47 UTC, cloudjumpercat approved these changes

2022-08-01 03:14 UTC, mayocream commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md
> +`vaults=bundled` and `vaults_use_new_style_api=on`set in `kong.conf`.
```suggestion
In the GA release of the Secrets Management feature in
{{site.base_gateway}}, this feature is enabled by default.
Due to conflicts with previous releases of {{site.base_gateway}},
the endpoints for secrets management in the
Admin API will be moved from the previous `/vaults-beta` prefix to
`/vaults` with `vaults_use_new_style_api=on` set in `kong.conf`.
```

2022-08-01 03:53 UTC, mayocream approved these changes

2022-08-01 03:55 UTC, mayocream commented
@cloudjumpercat Please take another look, and the autodoc Admin API and configuration need re-generation when 2.8.1.3 is released.

2022-08-01 14:22 UTC, cloudjumpercat requested changes

2022-08-01 14:22 UTC, cloudjumpercat commented on app/_hub/kong-inc/vault-auth/0.4.0.md
> +        **Note:** This value must refer to the Consumer `id` attribute that is internal to {{site.base_gateway}}, and **not** its `custom_id`.
```suggestion
        **Note:** This value must refer to the Consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-08-01 14:22 UTC, cloudjumpercat commented on app/_hub/kong-inc/vault-auth/_index.md
> +        **Note:** This value must refer to the Consumer `id` attribute that is internal to {{site.base_gateway}}, and **not** its `custom_id`.
```suggestion
        **Note:** This value must refer to the Consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-08-01 14:23 UTC, cloudjumpercat commented on app/_hub/kong-inc/vault-auth/0.4.0.md
> +        **Note:** This value must refer to the Consumer `id` attribute that is internal to {{site.base_gateway}}, and **not** its `custom_id`.
```suggestion
        **Note:** This value must refer to the Consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-08-04 18:36 UTC, tyler-ball commented
I added https://github.com/Kong/docs.konghq.com/pull/4144/commits/63f59e38496bb6f78d380f30094b10fb946918ab - @cloudjumpercat @mayocream can y'all review that?

2022-08-04 18:49 UTC, cloudjumpercat requested changes

2022-08-04 18:49 UTC, cloudjumpercat commented on app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md
> +> When running in Hybrid or DBLess mode, Secrets Management is only supported in {{site.base_gateway}} version 2.8.1.3 and greater.
```suggestion
> When running {{site.base_gateway}} in hybrid or DB-less mode, secrets management is only supported in {{site.base_gateway}} 2.8.1.3 or later.
```

2022-08-04 18:49 UTC, cloudjumpercat approved these changes

2022-08-05 12:26 UTC, merged