[chore] Gateway 2.8.3.1 support for Lambda plugin
Kong/docs.konghq.com pull request #4149
Opened 2022-07-22 20:36 UTC by Guaris

### Summary
#4142

2022-07-22 20:43 UTC, cloudjumpercat requested changes

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +[EC2 Instance Metadata service(IMDSv1)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html);
```suggestion
[EC2 Instance Metadata service(IMDSv1)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> + if you're running Kong in an ECS container, the task IAM role will be used, and Kong will fetch the credentials from
```suggestion
If you're running Kong in an ECS container, the task IAM role will be used, and Kong will fetch the credentials from
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +Note that the plugin will firstly try to fetch from ECS metadata to get the role, and if no ECS metadata related environment
```suggestion
Note that the plugin will first try to fetch from ECS metadata to get the role, and if no ECS metadata related environment
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +variables is available, the plugin falls back on EC2 metadata.
```suggestion
variables are available, the plugin falls back on EC2 metadata.
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +action(which requires the Kong process to make HTTPS request to AWS STS service API) after
```suggestion
action, which requires the Kong process to make HTTPS request to AWS STS service API, after
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +configuring AWS access key/secret or fetching credentials automatically from EC2/ECS IAM roles,
```suggestion
configuring AWS access key/secret or fetching credentials automatically from EC2/ECS IAM roles.
```

2022-07-22 20:43 UTC, cloudjumpercat commented on app/_hub/kong-inc/aws-lambda/_index.md
> +and if succeeded, the plugin will fetch a temporary security credentials which represents
```suggestion
If it succeeds, the plugin will fetch a temporary security credentials that represents
```

2022-07-25 13:15 UTC, cloudjumpercat approved these changes

2022-08-04 23:20 UTC, tyler-ball approved these changes

2022-08-04 23:20 UTC, tyler-ball commented
@Guaris Is this supposed to still be `do not review`?

2022-08-05 12:27 UTC, merged