Add OpenTelemetry plugin for gateway 3.0
Kong/docs.konghq.com pull request #4154
Opened 2022-07-25 09:05 UTC by mayocream

### Summary

Add OpenTelemetry plugin for gateway 3.0.

2022-07-26 16:57 UTC, mheap commented
Pushed a commit that fixes Plugin Hub rendering for maps in the examples.

Old: 
![image](https://user-images.githubusercontent.com/59130/181065819-7586238b-c9da-45d2-b0eb-cd63db10be29.png)

New (tested working):
![image](https://user-images.githubusercontent.com/59130/181065871-ab3e54dc-477a-4587-9420-130e6f9f2be4.png)

2022-07-26 19:16 UTC, cloudjumpercat requested changes

2022-07-26 19:37 UTC, cloudjumpercat requested changes

2022-07-26 19:37 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/versions.yml
> +- release: 0.1.0
```suggestion
strategy: gateway
releases:
  - 3.0.x
overrides:
  3.0.x: 0.1.0
```

2022-07-27 04:07 UTC, mayocream commented on app/_data/docs_nav_gateway_3.0.x.yml
> +      - text: OpenTelemetry plugin
Thanks, Added!

2022-07-27 04:11 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +Enable the OpenTelemetry tracing capability in Kong's configuration:
basicly two requirements:
1. set the kong.conf `opentelemetry_tracing`
2. enable the `opentelemetry` plugin

2022-07-27 04:14 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +- `opentelemetry_tracing = all`, Valid values can be found in the [Kong's configuration](/gateway/latest/reference/configuration/#opentelemetry_tracing).
The configuration is exist on the https://github.com/Kong/kong-ee/blob/master/kong.conf.default#L106 file, but I don't know how to generate the docs.
So do the tracing pdk, need to run the `autodoc` to generate new sections for pdk changes in 3.0.

2022-07-27 04:16 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +The `4318` port is the OTLP/HTTP port, and the `4317` port is the OTLP/GRPC port which OpenTelemetry plugin not supported yet.
Can we use `the `4317` port is the OTLP/GRPC port that isn't supported by OpenTelemetry plugin yet.`?
OpenTelemetry is spec, and the OpenTelemetry plugin is the implemetation.

2022-07-27 04:17 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +The OpenTelemetry plugin implemented the [OTLP/HTTP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp) exporter, which uses Protobuf pay
Yes! Thanks!

2022-07-27 20:42 UTC, cloudjumpercat requested changes

2022-07-27 20:42 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/_index.md
> +        The full HTTP(S) endpoint that {{site.base_gateway}} should send OpenTelemetry spans to.
```suggestion
        The full HTTP(S) endpoint that Kong Gateway should send OpenTelemetry spans to.
```

2022-07-27 20:42 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/_index.md
> +        {{site.company_name}} follows the OpenTelemetry specification for [Semantic Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic
```suggestion
        Kong follows the OpenTelemetry specification for [Semantic Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service).
```

2022-07-27 20:42 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/_index.md
> +        - `service.version`: The version of {{site.base_gateway}}.
```suggestion
        - `service.version`: The version of Kong Gateway.
```

2022-07-27 20:42 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/_index.md
> +        - `service.instance.id`: The node id of {{site.base_gateway}}.
```suggestion
        - `service.instance.id`: The node id of Kong Gateway.
```

2022-07-27 20:42 UTC, cloudjumpercat commented on app/_hub/kong-inc/opentelemetry/_index.md
> +- `opentelemetry_tracing = all`, Valid values can be found in the [Kong's configuration](/gateway/latest/reference/configuration/#opentelemetry_tracing).
It looks like the autodocs will be generated automatically with the 3.0 release, so that section should be published then.

2022-07-27 20:43 UTC, cloudjumpercat approved these changes

2022-07-28 09:25 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +2. Using the OpenTelemetry Collector, which is middleware that can be used to proxy OpenTelemetry spans to a compatible backend.
```suggestion
* Using the OpenTelemetry Collector, which is middleware that can be used to proxy OpenTelemetry spans to a compatible backend.
```

2022-07-28 09:27 UTC, mayocream commented on app/_hub/kong-inc/opentelemetry/_index.md
> +- `datadog`: [Datadog headers](https://docs.datadoghq.com/tracing/agent/propagation/)
```suggestion
- `datadog`: [Datadog headers](https://docs.datadoghq.com/tracing/agent/propagation/) (Enterprise only)
```

2022-07-28 13:19 UTC, merged