docs(perf) update perf test framework API
Kong/docs.konghq.com pull request #4158
Opened 2022-07-27 08:33 UTC by fffonion

### Summary
Update perf test framework to latest API

2022-07-27 11:32 UTC, mayocream approved these changes
LGTM

2022-07-27 15:12 UTC, cloudjumpercat requested changes

2022-07-27 15:12 UTC, cloudjumpercat commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +Otherwise, the chart will treat results in same test file as independent tests
```suggestion
If there are no correlations, the chart treats results in same test file as independent tests 
```

2022-07-27 15:12 UTC, cloudjumpercat commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +Otherwise, the chart will treat results in same test file as independent tests
@fffonion Is this an accurate revision?

2022-07-27 15:12 UTC, cloudjumpercat commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +and draw a bar chart.
```suggestion
and draws a bar chart.
```

2022-07-27 15:12 UTC, cloudjumpercat commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +The generated JSON results for creating charts are stored under `output` drectory.
```suggestion
The generated JSON results for creating charts are stored under the `output` directory.
```

2022-07-27 15:12 UTC, cloudjumpercat commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +data stored in `output` directory. Use the following commands to draw graph:
```suggestion
data stored in the `output` directory. Use the following commands to draw graphs:
```

2022-07-29 13:52 UTC, cloudjumpercat commented
@fffonion When you've added all the content you want to add, could you add the "review: copyedit" label and I'll review the changes? Thanks!

2022-08-04 14:07 UTC, cloudjumpercat commented
@fffonion When you have a chance, could you add the "review: copyedit" label if your changes are complete and I'll review the changes? Thanks!

2022-08-05 04:52 UTC, fffonion commented on src/gateway/plan-and-deploy/performance-testing-framework.md
> +Otherwise, the chart will treat results in same test file as independent tests
```suggestion
If this option is not set, the chart treats results in same test file as independent tests
```

2022-08-05 05:00 UTC, fffonion commented
just did, @cloudjumpercat thanks for the review!

2022-08-05 15:19 UTC, cloudjumpercat requested changes

2022-08-05 15:19 UTC, cloudjumpercat commented on src/gateway/reference/performance-testing-framework.md
> +like [gojira](https://github.com/kong/gojira) or [pongo](https://github.com/kong/kong-pongo), if they don't have development environment.
```suggestion
like [gojira](https://github.com/kong/gojira) or [Pongo](https://github.com/kong/kong-pongo), if they don't have development environment.
```

2022-08-05 15:26 UTC, cloudjumpercat approved these changes

2022-08-05 15:27 UTC, merged