Update allowing-multiple-authentication-methods.md
Kong/docs.konghq.com pull request #4181
Opened 2022-08-03 23:52 UTC by rkazak

missed a few more, but you may wish to change them all to kong-admin or kong-admin.mgr - once a standard is being followed internally we can add the name into our hosts file and then following along with 'C&P testing' should be easier.

### Summary

### Reason

### Testing

2022-08-04 13:52 UTC, cloudjumpercat requested changes

2022-08-04 13:52 UTC, cloudjumpercat commented on app/gateway/2.7.x/configure/auth/allowing-multiple-authentication-methods.md
> +curl -sX POST loclhost:8001/consumers/medvezhonok/basic-auth \
```suggestion
curl -sX POST localhost:8001/consumers/medvezhonok/basic-auth \
```

2022-08-04 13:52 UTC, cloudjumpercat approved these changes

2022-08-04 13:59 UTC, merged

2022-08-04 14:01 UTC, cloudjumpercat commented
@rkazak Thanks for fixing these! The docs team recently came up with a standard for these placeholder/example values. Here's our standard if you'd like to check it out: https://docs.konghq.com/contributing/style-guide/#placeholder-and-example-values

2022-08-15 21:36 UTC, rkazak commented
Like the style guide, I would also suggest that the https://developers.google.com/style/code-syntax be our standard too.