docs(prometheus) add new options for 3.0
Kong/docs.konghq.com pull request #4183
Opened 2022-08-04 08:46 UTC by fffonion

### Summary
docs(prometheus) add new options for 3.0

### Reason
From https://github.com/Kong/kong/pull/9028

2022-08-04 15:52 UTC, cloudjumpercat requested changes

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +desc: Expose metrics related to Kong and proxied Upstream services in Prometheus exposition format
```suggestion
desc: Expose metrics related to Kong and proxied upstream services in Prometheus exposition format
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +  Expose metrics related to Kong and proxied Upstream services in [Prometheus](https://prometheus.io/docs/introduction/overview/) exposition format, which can be scraped by a Prometheus Server.
```suggestion
  Expose metrics related to Kong and proxied upstream services in [Prometheus](https://prometheus.io/docs/introduction/overview/) exposition format, which can be scraped by a Prometheus Server.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +API at the `http://localhost:<port>/metrics`
```suggestion
API at the `http://localhost:PORT/metrics`
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +installation; see [Accessing the metrics](#accessing-the-metrics).
```suggestion
installation, see [Accessing the metrics](#accessing-the-metrics).
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +and consume data from each node's configured `/metrics` endpoint.
```suggestion
This plugin records and exposes metrics at the node level. Your Prometheus
server must discover all Kong nodes via a service discovery mechanism
and consume data from each node's configured `/metrics` endpoint.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +- **Status codes**: HTTP status codes returned by Upstream services.
```suggestion
- **Status codes**: HTTP status codes returned by upstream services.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +- **Latencies Histograms**: Latency in ms, as measured at Kong:
```suggestion
- **Latencies Histograms**: Latency (in ms), as measured at Kong:
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/1.6.0.md
> +   - **Request**: Total time taken by Kong and Upstream services to serve
```suggestion
   - **Request**: Total time taken by Kong and upstream services to serve
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
>  desc: Expose metrics related to Kong and proxied Upstream services in Prometheus exposition format
```suggestion
desc: Expose metrics related to Kong and proxied upstream services in Prometheus exposition format
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
>    Expose metrics related to Kong and proxied Upstream services in [Prometheus](https://prometheus.io/docs/introduction/overview/) exposition format, which can be scraped by a Prometheus Server.
```suggestion
  Expose metrics related to Kong and proxied upstream services in [Prometheus](https://prometheus.io/docs/introduction/overview/) exposition format, which can be scraped by a Prometheus Server.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +- **Status codes**: HTTP status codes returned by Upstream services.
```suggestion
- **Status codes**: HTTP status codes returned by upstream services.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +- **Latencies Histograms**: Latency in ms, as measured at Kong:
```suggestion
- **Latencies Histograms**: Latency (in ms), as measured at Kong:
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +   - **Request**: Total time taken by Kong and Upstream services to serve
```suggestion
   - **Request**: Total time taken by Kong and upstream services to serve
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +   - **Upstream**: Time taken by the Upstream service to respond to requests.
```suggestion
   - **Upstream**: Time taken by the upstream service to respond to requests.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +  belonging to a given Upstream as well as their subsystem (`http` or `stream`).
```suggestion
- **Target Health**: The healthiness status (`healthchecks_off`, `healthy`, `unhealthy`, or `dns_error`) of targets
  belonging to a given upstream as well as their subsystem (`http` or `stream`).
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +* Disable high cardinality metrics by default.
```suggestion
* High cardinality metrics are now disabled by default.
```

2022-08-04 15:52 UTC, cloudjumpercat commented on app/_hub/kong-inc/prometheus/_index.md
> +* Decreases performance penalty to proxy traffic when collecting metrics.
```suggestion
* Decreased performance penalty to proxy traffic when collecting metrics.
```

2022-08-04 16:03 UTC, cloudjumpercat approved these changes

2022-08-04 17:21 UTC, hfukada commented
shouldn't the prometheus 1.6.0 version be be moved to 3.0.0?

2022-08-08 14:36 UTC, cloudjumpercat approved these changes

2022-08-08 14:48 UTC, merged