Allow anonymous to be configured as the username of consumer
Kong/docs.konghq.com pull request #4404
Opened 2022-09-07 06:51 UTC by vm-001

…onsumer

### Summary

### Reason

### Testing

2022-09-15 13:28 UTC, cloudjumpercat requested changes

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/hmac-auth/_index.md
> +        An optional string (consumer UUID) value to use as an anonymous Consumer if authentication fails.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/hmac-auth/_index.md
> +        must refer to the Consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/jwt/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `4xx`. Please note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/jwt/_index.md
> +        An optional string (Consumer UUID) value to use as an anonymous Consumer if authentication fails.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/jwt/_index.md
> +        must refer to the Consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/key-auth-enc/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/key-auth-enc/_index.md
> +        must refer to the consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/key-auth/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/key-auth/_index.md
> +        must refer to the consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/ldap-auth-advanced/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/ldap-auth-advanced/_index.md
> +        must refer to the consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/ldap-auth/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/ldap-auth/_index.md
> +        must refer to the consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        If empty (default), the request fails with an authentication failure `4xx`. Note that this value
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/mtls-auth/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/oauth2-introspection/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/oauth2-introspection/_index.md
> +        An optional string (Consumer UUID) value to use as an anonymous Consumer if authentication fails. If empty (default), the request will fail with an authentication failure 4xx.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails. If empty (default), the request fails with an authentication failure `4xx`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/oauth2/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/oauth2/_index.md
> +        An optional string (Consumer UUID) value to use as an anonymous Consumer if authentication fails.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/oauth2/_index.md
> +        must refer to the Consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        If empty (default), the request fails with an authentication failure `4xx`. Note that this value
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/openid-connect/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/openid-connect/_index.md
> +        must refer to the Consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
        If empty (default), the request will fail with an authentication failure `4xx`. Note that this value
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/vault-auth/_index.md
> +        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `
```suggestion
        An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
```

2022-09-20 14:58 UTC, cloudjumpercat commented on app/_hub/kong-inc/vault-auth/_index.md
> +        must refer to the Consumer `id` attribute that is internal to Kong, and **not** its `custom_id`.
```suggestion
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
        If empty (default), the request fails with an authentication failure `4xx`. Note that this value
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
```

2022-09-20 15:00 UTC, cloudjumpercat approved these changes
LGTM!

2022-09-20 15:13 UTC, cloudjumpercat commented
Ignoring Vale errors because they are flagging Liquid syntax incorrectly.

2022-09-20 15:14 UTC, cloudjumpercat commented
@vm-001 Should this wait for the 3.1.x release to be merged?

2022-09-21 02:22 UTC, vm-001 commented
@cloudjumpercat Thanks! Yes, this PR should wait for 3.1.x release, that's why I add the 3.1 Milestone.

2022-10-17 14:50 UTC, cloudjumpercat commented
Ignoring Vale errors, those will be resolved when this is merged into main (because the Vale plugin changes aren't on this branch).

2022-10-18 14:45 UTC, merged