[DOCU-2462] Runtime Groups Dashboard
Kong/docs.konghq.com pull request #4436
Opened 2022-09-12 15:05 UTC by cloudjumpercat

### Summary

This documents the new runtime groups dashboard metrics feature. 
**Note to self**, this will probably conflict with #4412.

**For reviewers:**

- When I was testing this locally, the Dashboard page would only show up when I was on another page in the Runtime Groups section or when I took a link to the page. Any way I can fix this so it always shows up in the nav and search?
- Do you think we need screenshots? I was trying to match this page with the Vitals dashboard page and they had screenshots, but not sure if those are necessary or not. 
- Overall, do you think this was a good way to document this feature or should I have done something else? Or should we add info about it to another section as well?

### Reason

[DOCU-2462](https://konghq.atlassian.net/browse/DOCU-2462)
### Testing

- /konnect/runtime-manager/runtime-groups/dashboard/: New page
- Vitals dashboard page: just added a link to that page
- Runtime groups overview page: Added a small section about the dashboard

2022-09-14 16:24 UTC, Guaris requested changes

2022-09-14 16:24 UTC, Guaris commented on app/konnect/runtime-manager/runtime-groups/dashboard.md
> +Graphs can be interacted with, including hovering over chart items to display more details, and filtering options by clicking on items in the **legend**.
```suggestion
Graphs are interactive, including hovering over chart items to display more details, and filtering options by clicking on items in the **legend**.
```

2022-09-14 18:30 UTC, cloudjumpercat commented on app/konnect/runtime-manager/runtime-groups/dashboard.md
> +* **Errors**: This displays the total number of failed HTTP requests categorized by error response codes over the specified time interval. Error response codes include any **4xx-5xx** status codes.
@Guaris Yep! Is that something I should make clearer? I can't think of a good way to revise it at the moment.

2022-09-14 20:53 UTC, Guaris approved these changes

2022-09-15 13:27 UTC, cloudjumpercat commented
Note: Ignoring failing Vale tests because it's flagging pages that weren't changed.

2022-09-15 13:27 UTC, merged