[TDX-2195] Dev portal app reg with multi-runtime group support
Kong/docs.konghq.com pull request #4473
Opened 2022-09-16 18:13 UTC by Mierenga

### Summary

### Reason

https://konghq.atlassian.net/browse/TDX-2195
Application registration is opening support for any runtime group. Only compatible with Kong Gateway versions >= 3.0

### Testing

2022-09-23 15:39 UTC, cloudjumpercat commented
@Mierenga Will you be adding additional changes or is this ready for a copy edit? Thanks!

2022-09-23 17:15 UTC, Mierenga commented
@cloudjumpercat There will be additional changes in the next couple weeks before it is ready for docs review, thanks for checking in!

2022-10-20 18:54 UTC, cloudjumpercat commented
@Mierenga Hi! Just checking in to see if you have any more changes for this PR. Thanks!

2022-11-07 23:43 UTC, Mierenga commented
@cloudjumpercat This info is ready for review from the docs team, thanks!

2022-11-08 17:17 UTC, Guaris requested changes

2022-11-08 18:39 UTC, Mierenga commented on app/konnect/dev-portal/applications/enable-app-reg.md
> +If you need to use version of {{site.base_gateway}} less than 3.0, you must create your service version in the `default` runtime group. Non-default runtime groups are only compatible with {{site.base
updated in https://github.com/Kong/docs.konghq.com/pull/4473/commits/78fdf9479b4b741130cc9e3ae0f4d52339967cea

2022-11-08 18:39 UTC, Mierenga commented on app/konnect/dev-portal/applications/enable-app-reg.md
> +    read-only entries for the  `konnect-application-auth` and `openid-connect` plugins.
updated in https://github.com/Kong/docs.konghq.com/pull/4473/commits/78fdf9479b4b741130cc9e3ae0f4d52339967cea

2022-11-08 20:09 UTC, nateslo approved these changes
This looks good to me from a technical standpoint

2022-11-08 20:52 UTC, codelemur commented on app/konnect/dev-portal/applications/enable-app-reg.md
> +When you enable application registration, {{site.konnect_saas}} enables plugins automatically to support the desired mode, either key authentication or OpenID Connect.
Nit:
```suggestion
When you enable application registration, {{site.konnect_saas}} automatically enables plugins to support the desired mode, either [Key Authentication](https://docs.konghq.com/hub/kong-inc/key-auth/) with [ACL](https://docs.konghq.com/hub/kong-inc/acl/) or [OpenID Connect](https://docs.konghq.com/hub/kong-inc/openid-connect/).
```

I just want to be more explicit in the explanations, if that makes sense.

2022-11-08 20:53 UTC, codelemur commented on app/konnect/dev-portal/applications/enable-app-reg.md
> +When you enable application registration, {{site.konnect_saas}} enables plugins automatically to support the desired mode, either key authentication or OpenID Connect.
Please disregard!

2022-11-08 21:02 UTC, codelemur commented on app/konnect/dev-portal/applications/enable-app-reg.md
> +- The service version can be in any runtime group.
```suggestion
- The service version can be in any runtime group, as long as the following conditions are met:
```

2022-11-08 21:43 UTC, codelemur approved these changes
LGTM

2022-11-09 16:01 UTC, Guaris approved these changes

2022-11-09 16:02 UTC, Guaris commented
I'm pushing this to a feature branch with this PR
https://github.com/Kong/docs.konghq.com/pull/4716

So they can both go out together on Monday

2022-11-09 18:01 UTC, merged