fix: Added correct link to `kustomize` install and modifies `helm` install and note to show an option
Kong/docs.konghq.com pull request #4477
Opened 2022-09-19 04:12 UTC by afzal442

Signed-off-by: afzal442 <afzal442@gmail.com>

### Summary

Adds correct link to kustomize install and modifies helm install to add missing namespace
Adds a note to support hostname.
### Reason

### Testing

2022-09-20 16:03 UTC, cloudjumpercat requested changes

2022-09-20 16:03 UTC, cloudjumpercat commented on src/kubernetes-ingress-controller/deployment/k4k8s.md
> +>Note: You can also specify `ingress[0].hostname` alternatively depending on your environment.
```suggestion
> **Note:** Alternatively, you can also specify `ingress[0].hostname` depending on your environment.
```

2022-09-20 16:04 UTC, cloudjumpercat commented
@mheap Could you review the other changes in this PR?

2022-09-21 07:59 UTC, mheap requested changes

2022-09-21 07:59 UTC, mheap commented on src/kubernetes-ingress-controller/deployment/k4k8s.md
> +kustomize build github.com/Kong/kubernetes-ingress-controller/tree/main/config/base
The original line was correct here. This change breaks `kustomize`

2022-10-04 14:58 UTC, merged