Updated index.md for OAuth2 Authentication
Kong/docs.konghq.com pull request #4516
Opened 2022-09-26 16:29 UTC by RagunathInGIT

Change is to mention various ways of how we can call OAuth2/token endpoint to retrieve access_token for client_credentials grant_type.

Where is the problem?
https://docs.konghq.com/hub/kong-inc/oauth2/

What happened?
I dont see documentation of various ways of calling "/oauth2/token" call for client_credentials flow.

What did you expect to happen?
In Client credentials flow, there is a provision to make "oauth2/token" call by passing the client ID, client secret and grant_type as query param or a JSON body or in a url-encoded form data.

2022-09-28 16:24 UTC, lena-larionova requested changes

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +Below are the various ways we can consume "/oauth2/token" endpoint to retrieve the access_token.
```suggestion
You can access the `/oauth2/token` endpoint to retrieve the `access_token` in the following ways:.
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +_Content-Type set to application/x-www-form-urlencoded and sending the credentials as a form data in a POST call._
```suggestion
* Using a POST request, set `Content-Type` to `application/x-www-form-urlencoded` and send the credentials as form data:
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +curl --location --request POST 'https://your.service.com/oauth2/token' \
```suggestion
curl -i -X POST 'https://example.service.com/oauth2/token' \
```
Using formatting consistent with the rest of our documentation.

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +_Content-Type set to application/json and sending the credentials as a JSON body in a POST call._
```suggestion
* Using a POST request, set `_Content-Type` to `application/json` and send the credentials as a JSON body:
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +curl --location --request POST 'https://your.service.com/oauth2/token' \
```suggestion
curl -i -X POST 'https://example.service.com/oauth2/token' \
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +_Sending the credentials in URL query parameters in a POST call._
```suggestion
* Using a POST request, send the credentials in URL query parameters:
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +curl --location --request POST 'https://your.service.com/oauth2/token?client_id=XXXX&client_secret=XXXX&grant_type=client_credentials'
```suggestion
curl -i -X POST 'https://your.service.com/oauth2/token?client_id=XXXX&client_secret=XXXX&grant_type=client_credentials'
```

2022-09-28 16:24 UTC, lena-larionova commented on app/_hub/kong-inc/oauth2/_index.md
> +The [Client Credentials](https://tools.ietf.org/html/rfc6749#section-4.4) flow will work out of the box, without building any authorization page. The clients will need to use the `/oauth2/token` endp
```suggestion
The [Client Credentials](https://tools.ietf.org/html/rfc6749#section-4.4) flow works out of the box, without building any authorization page. The clients need to use the `/oauth2/token` endpoint to request an access token.  
```

2022-09-29 22:04 UTC, RagunathInGIT reviewed
This looks fine. Thank you for updating it.

2022-09-29 23:27 UTC, lena-larionova approved these changes
And thank you for the submission!

For reviewers: ignoring the failing linter check, as there's a fix for it on `main` already + there's issues when it runs on forks occasionally.

2022-09-29 23:27 UTC, merged