Correct limit_by service for rate-limiting plugin
Kong/docs.konghq.com pull request #4626
Opened 2022-10-20 11:46 UTC by Benny-Git

### Summary
The description for the rate-limiting plugin's `limit_by` parameter was incorrect.
Limiting by service does not use a (non-existent) config.service_id parameter, but instead uses the service.id the plugin is configured against.

### Reason
https://github.com/Kong/docs.konghq.com/issues/4580

### Testing
Tested behavior on local Kong 3.0 instance. The config.service_id parameter is invalid, and results in an error:
```json
{
    "fields": {
        "config": {
            "service_id": "unknown field"
        }
    },
    "name": "schema violation",
    "code": 2,
    "message": "schema violation (config.service_id: unknown field)"
}
```

Benjamin Bertow <benjamin.bertow@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH

2022-10-20 14:19 UTC, cloudjumpercat requested changes

2022-10-21 06:57 UTC, Benny-Git commented
Thanks for the suggestions, @cloudjumpercat. Sounds much better now.

As an alternate formatting, we could bring it to a similar list style as with `config.policy` further down the file. What's your opinion on that?

```yaml
      description: |
        The entity that is used when aggregating the limits. Available values are:
        - `consumer`
        - `credential`
        - `ip`
        - `service`: the `service.id` or `service.name` configuration must be provided if you're adding the plugin to a service through the top-level `/plugins` endpoint.
        - `header`: the `header_name` configuration must be provided.
        - `path`: the `path` configuration must be provided.

        If the entity value for aggregating the limits cannot be determined, the system falls back to `ip`.
       
```

2022-10-21 14:50 UTC, cloudjumpercat requested changes

2022-10-21 14:50 UTC, cloudjumpercat commented on app/_hub/kong-inc/rate-limiting/_index.md
> +        If the `path` value is chosen, the `path` configuration must be provided.
```suggestion
        The entity that is used when aggregating the limits. Available values are:
        - `consumer`
        - `credential`
        - `ip`
        - `service` (The `service.id` or `service.name` configuration must be provided if you're adding the plugin to a service through the top-level `/plugins` endpoint.)
        - `header` (The `header_name` configuration must be provided.)
        - `path` (The `path` configuration must be provided.)
        If the entity value for aggregating the limits cannot be determined, the system falls back to `ip`.
```

2022-10-21 14:51 UTC, cloudjumpercat commented
> Thanks for the suggestions, @cloudjumpercat. Sounds much better now.
> 
> As an alternate formatting, we could bring it to a similar list style as with `config.policy` further down the file. What's your opinion on that?
> 
> ```yaml
>       description: |
>         The entity that is used when aggregating the limits. Available values are:
>         - `consumer`
>         - `credential`
>         - `ip`
>         - `service`: the `service.id` or `service.name` configuration must be provided if you're adding the plugin to a service through the top-level `/plugins` endpoint.
>         - `header`: the `header_name` configuration must be provided.
>         - `path`: the `path` configuration must be provided.
> 
>         If the entity value for aggregating the limits cannot be determined, the system falls back to `ip`.
>        
> ```

That looks good to me! I've added a suggested edit with those changes. Thanks!

2022-10-24 13:38 UTC, cloudjumpercat approved these changes
LGTM!

2022-10-24 13:38 UTC, merged