feat(response-ratelimiting): add support for Redis SSL
Kong/docs.konghq.com pull request #4681
Opened 2022-11-01 05:50 UTC by vm-001

### Summary

### Reason

### Testing

2022-11-01 06:02 UTC, vm-001 commented
Target release version 3.1

2022-11-04 15:30 UTC, cloudjumpercat requested changes
Just one small edit, thanks for submitting this!

2022-11-04 15:30 UTC, cloudjumpercat commented on app/_hub/kong-inc/response-ratelimiting/_index.md
> +        When using the `redis` policy with `redis_ssl` set to `true`, this property specifies it server SSL certificate is validated. Note that you need to configure the lua_ssl_trusted_certificate t
```suggestion
        When using the `redis` policy with `redis_ssl` set to `true`, this property specifies if the server SSL certificate is validated. Note that you need to configure the `lua_ssl_trusted_certificate` to specify the CA (or server) certificate used by your Redis server. You may also need to configure `lua_ssl_verify_depth` accordingly.
```

2022-11-04 16:18 UTC, cloudjumpercat approved these changes
LGTM!

2022-11-04 16:21 UTC, merged