feat(acme): add support for Redis SSL
Kong/docs.konghq.com pull request #4682
Opened 2022-11-01 06:00 UTC by vm-001

### Summary

Add support for Redis SSL

!!! Only Kong employees can add labels due to a GitHub limitation. If you're an OSS contributor, thank you! The maintainers will label this PR for you !!!

When raising a pull request, it's useful to indicate what type of review you're looking for from the team. To help with this, we've added three labels that can be applied:

    review:copyedit: Request for writer review.
    review:general: Review for general accuracy and presentation. Does the doc work? Does it output correctly?
    review:tech: Request for technical review from an SME.

At least one of these labels must be applied to a PR or the build will fail.
-->

Internal ticket FTI-4432

2022-11-01 06:01 UTC, vm-001 commented
Target release version 3.1

2022-11-01 19:57 UTC, cloudjumpercat requested changes
@vm-001 Thanks for submitting this! Since this is for Gateway 3.1, could you change the base branch to `release/gateway-3.1`?

2022-11-01 19:57 UTC, cloudjumpercat commented on app/_hub/kong-inc/acme/_index.md
> +* Added the `config.storage_config.ssl`, `config.storage_config.ssl_verify`, and `config.storage_config.ssl_server_name`. configuration parameters.
```suggestion
* Added the `config.storage_config.ssl`, `config.storage_config.ssl_verify`, and `config.storage_config.ssl_server_name` configuration parameters.
```

2022-11-02 02:59 UTC, vm-001 commented
> @vm-001 Thanks for submitting this! Since this is for Gateway 3.1, could you change the base branch to `release/gateway-3.1`?

Done.

2022-11-02 16:32 UTC, cloudjumpercat approved these changes
LGTM! Thanks for submitting this!

2022-11-02 16:32 UTC, merged