Add Deck Windows installation instructions
Kong/docs.konghq.com pull request #4718
Opened 2022-11-04 14:57 UTC by stefancruz

### Summary

Add Deck Windows installation instructions using CMD.

As of [Windows 10 Build 17063](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows), tar and curl are now packaged by default in the OS.

Used PowerShell to add to environment path since SETX has a 1024 characters limit and could truncate the values.

### Reason
Make Deck setup on Windows easier

### Testing

```
curl -sL https://github.com/kong/deck/releases/download/v1.15.1/deck_1.15.1_windows_amd64.tar.gz -o deck.tar.gz
mkdir deck
tar -xvzf deck.tar.gz -C deck
```
The following command can be used to add the directory to the PATH. If this is not desired can be removed.
`powershell -command "[Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + [IO.Path]::PathSeparator + $pwd + '\deck', 'User')"`

2022-11-04 15:43 UTC, lena-larionova commented on src/deck/installation.md
> +{% if_version leq:1.12.x %}
```suggestion
{% if_version lte:1.12.x %}
```

2022-11-04 15:44 UTC, lena-larionova commented on src/deck/installation.md
> +## Windows
```suggestion
{% if_version lte:1.12.x %}

## Windows
```

2022-11-08 08:45 UTC, GGabriele commented on src/deck/installation.md
> +curl -sL https://github.com/kong/deck/releases/download/v{{page.version}}/deck_{{page.version}}_linux_amd64.tar.gz -o deck.tar.gz
```suggestion
curl -sL https://github.com/kong/deck/releases/download/v{{page.version}}/deck_{{page.version}}_windows_amd64.tar.gz -o deck.tar.gz
```

2022-11-08 08:45 UTC, GGabriele commented on src/deck/installation.md
> +If you are Windows, you can either use the compressed archive from
```suggestion
If you are on Windows, you can either use the compressed archive from
```

2022-11-14 16:12 UTC, lena-larionova commented
@mikefero could you please take a look at this doc submission for accuracy?

2022-11-14 16:31 UTC, mikefero commented
> @mikefero could you please take a look at this doc submission for accuracy?

I will take a look at this soon.

2022-11-16 00:33 UTC, mikefero requested changes
This is still very Linuxy, but will work correctly with the following changes.

2022-11-30 13:31 UTC, mikefero approved these changes

2022-11-30 18:46 UTC, lena-larionova approved these changes

2022-11-30 18:47 UTC, merged

2022-12-01 18:43 UTC, stefancruz commented on src/deck/installation.md
> +or install using **CMD** by entering the target installation folder and downloading a compressed archive, which contains the binary:
@mikefero, no particular reason, I agree that could be simpler. I can create another pr to update this.

2022-12-12 19:57 UTC, mikefero commented on src/deck/installation.md
> +or install using **CMD** by entering the target installation folder and downloading a compressed archive, which contains the binary:
No worries @stefancruz I was just curious as I also mix and match between bashisms and PowerShell isms when working with Windows and WSL. I would hold off on that change for now as we can hopefully do something in decK to make the installation for all binaries/OSes even simpler in the near future.