plugin(xml-threat) adds new plugin documentation
Kong/docs.konghq.com pull request #4740
Opened 2022-11-08 12:29 UTC by Tieske

### Summary
Adds new xml-threat-protection plugin

2022-11-08 17:09 UTC, cloudjumpercat commented
@Tieske Thanks for submitting this! Since this is for Gateway 3.1, could you change the base branch to `release/gateway-3.1`? Thanks!

2022-11-09 10:45 UTC, Tieske commented
@cloudjumpercat updated. Let me know if you need anything else.

2022-11-09 17:38 UTC, cloudjumpercat requested changes
Left a few copyedits

2022-11-09 17:46 UTC, cloudjumpercat commented on app/_hub/kong-inc/xml-threat-protection/_index.md
> +        If not parsing namespace aware, all prefixes and namesapce attributes will be counted as regular attributes and element names, and validated as such.
Not sure if my revision is accurate or not.

2022-11-14 20:02 UTC, cloudjumpercat approved these changes
LGTM!

2022-11-14 21:16 UTC, merged