docs(consumer_group): add delete api for consumer group configuration
Kong/docs.konghq.com pull request #4785
Opened 2022-11-17 01:38 UTC by yzyyi

### Summary

We'd like an API to support deleting the current consumer group configurations.

### Reason
[](https://konghq.atlassian.net/browse/FT-3564)

### Testing
Test by using curl -i -X DELETE http://{HOSTNAME}:8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced

2022-11-17 01:56 UTC, lena-larionova commented
@yzyyi Is this a 3.1 feature? If so, can you please rebase and open this PR against `release/gateway-3.1`?

2022-11-17 01:57 UTC, lena-larionova requested changes

2022-11-17 01:57 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +you can delete it. This removes configurations for the consumer group.
```suggestion
You can also clear the configuration of a consumer group without deleting the consumer group itself.
```

2022-11-17 01:57 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +The consumers in the group are not deleted and are still in the consumer group.
```suggestion

With this method, the consumers in the group aren't deleted and are still in the consumer group.
```

2022-11-17 01:57 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +    Response, notice the plugins object in the response is gone.
```suggestion
    Response, without a `plugins` object:
```

2022-11-17 01:57 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +{{ delete_consumer_group_config| indent | replace: " </code>", "</code>" }}
```suggestion
{{ delete_consumer_group_config | indent | replace: " </code>", "</code>" }}
```

2022-11-17 03:46 UTC, lena-larionova approved these changes
Fixed a couple of minor things (grammar, typos) and some minor rephrasing - applied it in the interest of time. Ready to merge if you're happy with the changes.

2022-11-17 03:46 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +curl -i -X DELETE http://{HOSTNAME}:8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced \
```suggestion
curl -i -X DELETE http://{HOSTNAME}:8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced
```

2022-11-17 03:46 UTC, lena-larionova commented on src/gateway/kong-enterprise/consumer-groups/index.md
> +http DELETE :8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced \
```suggestion
http DELETE :8001/consumer_groups/JL/overrides/plugins/rate-limiting-advanced
```

2022-11-17 17:25 UTC, lena-larionova requested changes
Accidentally approved before PR was moved to 3.1 - please move it so that we can merge.

2022-11-18 17:35 UTC, yzyyi reviewed
Thanks, yes we can merge.

2022-11-21 17:36 UTC, yzyyi commented
rebased to release/3.1

2022-11-21 19:15 UTC, lena-larionova approved these changes

2022-11-21 19:16 UTC, merged