fix(route): update route.protocols document
Kong/docs.konghq.com pull request #4888
Opened 2022-12-08 09:22 UTC by vm-001

### Summary

Kong accepts HTTPS requests when route.protocols is set to only ["http"].

### Reason

### Testing

[FTI-4566]

[FTI-4566]: https://konghq.atlassian.net/browse/FTI-4566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-03 15:57 UTC, cloudjumpercat commented
@vm-001 If this is for Gateway 3.2, could you change the base branch to `release/gateway-3.2`? Thanks!

2023-01-03 16:00 UTC, cloudjumpercat requested changes
Just left one small comment

2023-01-03 16:00 UTC, cloudjumpercat commented on src/gateway/admin-api/index.md
> +    `protocols` |  An array of the protocols this Route should allow. See the [Route Object](#route-object) section for a list of accepted protocols. When set to only `"https"`, HTTP requests are ans
```suggestion
    `protocols` |  An array of the protocols this Route should allow. See the [Route Object](#route-object) section for a list of accepted protocols. When set to only `"https"`, HTTP requests are answered with an upgrade error. When it is set to only `"http"`, this is essentially the same as `["http", "https"]` in that both HTTP and HTTPS requests are allowed. Default: `["http", "https"]`.
```

2023-01-04 02:43 UTC, vm-001 commented
> @vm-001 If this is for Gateway 3.2, could you change the base branch to `release/gateway-3.2`? Thanks!

Done.

2023-01-04 22:05 UTC, cloudjumpercat commented
@vm-001 Sorry for not catching this sooner, but I think since this is new as of 3.2 and the Admin API doc is autogenerated, I think you need to add your content to this file instead: https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua

2023-01-05 14:26 UTC, cloudjumpercat approved these changes
LGTM!

2023-01-05 14:26 UTC, merged

2023-01-11 08:57 UTC, vm-001 commented
@cloudjumpercat Sorry for not following up quicker since I'm in a heavy load.

Kong PR is here: https://github.com/Kong/kong/pull/10097