Revise KIC plugin and auth guides for GWAPI
Kong/docs.konghq.com pull request #4894
Opened 2022-12-09 01:12 UTC by rainest

### Summary
Continuing the addition of Gateway API content and reusable includes for common tasks from https://github.com/Kong/docs.konghq.com/pull/4766 onward, into the plugin and authentication guides.

### Reason
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/2878 and https://github.com/Kong/kubernetes-ingress-controller/issues/2966

### Testing
Pending, WIP.

2022-12-13 17:35 UTC, Guaris commented
When this is ready please feel free to remove the draft status so we can approve it.

2022-12-13 17:48 UTC, rainest commented
@Guaris this depends on https://github.com/Kong/docs.konghq.com/pull/4766; it needs to be merged, and this needs to be rebased, before this can proceed.

If it works better for ya'll I could make this the only PR, containing the commits and changes from both. I'd kept them separate since they're both fairly large on their own already.

2022-12-15 22:04 UTC, rainest commented
Still needs an E2E command validation pass from me, but going ahead and marking ready for review of the copy and templating.

2022-12-15 23:34 UTC, rainest commented
Vale is unhappy for reasons I cannot entirely determine. It's apparently detecting terminology issues on a bunch of content I _didn't_ edit. Didn't find any `app/_src/ku` in the log, so it looks like the content here is fine :shrug:

2023-01-03 22:18 UTC, cloudjumpercat requested changes
Left a few suggestions. I think Vale is failing because you made an update in the file, so Vale checks each file that is touched. I think if you just fix the "Preserving" text, it should pass.

2023-01-03 22:40 UTC, rainest commented on app/_src/kubernetes-ingress-controller/guides/cert-manager.md
> +Via: kong/3.1.1
There are tags for it, so AFAICT it is: https://hub.docker.com/_/kong/tags?page=1&name=3.1.1

2023-01-04 14:46 UTC, merged