feat(opa): support custom message from OPA server (FTI-4574)
Kong/docs.konghq.com pull request #5045
Opened 2023-01-16 09:11 UTC by outsinre

### Description

Support custom message from OPA server (FTI-4574). Related code PR is <https://github.com/Kong/kong-ee/pull/4362>.

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-01-17 17:10 UTC, acgoldsmith commented
@outsinre , this looks like a 3.2 change, correct?

2023-01-25 15:19 UTC, cloudjumpercat requested changes

2023-01-25 15:19 UTC, cloudjumpercat commented on app/_hub/kong-inc/opa/_index.md
> +If `result.status` is absent then the default *unauthorized* message is sent.
```suggestion
If `result.status` is absent, then the default *unauthorized* message is sent.
```

2023-01-25 15:20 UTC, cloudjumpercat approved these changes
LGTM! Thanks for updating this!

2023-01-25 17:41 UTC, merged