feat(plugins): add datadog tracing plugin
Kong/docs.konghq.com pull request #5046
Opened 2023-01-17 07:07 UTC by mayocream

### Description

What did you change and why?
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-01-17 13:43 UTC, colinh-kong commented
Needs a header image
![image](https://user-images.githubusercontent.com/120141901/212914568-8fe8421d-f948-4081-b3c8-5c2977902e5d.png)

2023-01-30 21:44 UTC, Guaris commented
@mayocream 

Hey mayo, after the parameters this doc is a copy of the open telemetry doc. Could you write a usage section specific to the datadog tracing plugin?

2023-02-02 07:28 UTC, mayocream commented
> @mayocream
> 
> Hey mayo, after the parameters this doc is a copy of the open telemetry doc. Could you write a usage section specific to the datadog tracing plugin?

It was a draft, I updated the PR and rebased it, it's ready for review.

2023-02-08 09:08 UTC, fffonion commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +    --data "name=Datadog-tracing"  \
```suggestion
    --data "name=datadog-tracing"  \
```

2023-02-09 18:15 UTC, lena-larionova requested changes

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +- `tracing_instrumentations = request`: valid values can be found in the [tracing instrumentations](/gateway/latest/reference/configuration/#tracing_instrumentations) section of the configuration doc
```suggestion
- `tracing_instrumentations = request`: Valid values can be found in the [tracing instrumentations](/gateway/latest/reference/configuration/#tracing_instrumentations) section of the configuration documentation.
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +- `tracing_sampling_rate = 1.0`: tracing instrumentation sampling rate.
```suggestion
- `tracing_sampling_rate = 1.0`: Tracing instrumentation sampling rate.
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +              gcr.io/datadoghq/agent:latest
```suggestion
docker run -d -p 8126:8126 \
  --cgroupns host \
  --pid host \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /proc/:/host/proc/:ro \
  -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
  -e DD_API_KEY=<example-api-key> \
  -e DD_APM_NON_LOCAL_TRAFFIC=true \
   -e DD_APM_ENABLED=true \
   gcr.io/datadoghq/agent:latest
```
No need for such deep indents.

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +
Needs an intro to the section. Something like:

```suggestion

Set up the Datadog Agent. You can use the following example Docker configuration, substituting the `example-api-key` with your own key:

```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +For more information about installing the Datadog Agent on Docker, see [Datadog's documentation](https://docs.datadoghq.com/agent/docker/apm/?tab=linux). If you want to install another container opti
```suggestion
For more information about installing the Datadog Agent on Docker, see [Datadog's documentation](https://docs.datadoghq.com/agent/docker/apm/?tab=linux). If you want to install another container option, you can find the instructions in [Datadog's container list](https://docs.datadoghq.com/containers/).
```
We should use less generic link titles for better SEO and accessibility.

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +## OpenTelemetry Functionality
```suggestion
## OpenTelemetry functionality
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +The OpenTelemetry plugin propagates the following headers:
```suggestion
The Datadog Tracing plugin propagates the following headers:
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +An example of debug logs output:
```suggestion
Here's an example of the debug log output:
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +- Datadog tracing Only supports the HTTP protocols (http/https) of {{site.base_gateway}}.
```suggestion
- Datadog Tracing only supports the HTTP protocols (`http`/`https`) of {{site.base_gateway}}.
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +- May impact the performance of {{site.base_gateway}}.
```suggestion
- This plugin may impact the performance of {{site.base_gateway}}.
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +  It's recommended to set the sampling rate (`tracing_sampling_rate`)
```suggestion
  We recommend setting the sampling rate (`tracing_sampling_rate`)
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/_index.md
> +  via Kong configuration file when using the Datadog Tracing plugin.
```suggestion
  in the {{site.base_gateway}} configuration file when using the Datadog Tracing plugin.
```

2023-02-09 18:15 UTC, lena-larionova commented on app/_hub/kong-inc/datadog-tracing/versions.yml
> +  3.2.x: 0.1.0
Why do we need an override for this plugin version? As far as I know, the plugin version _should_ match the Kong version starting in 3.0. If it doesn't, then something's wrong.

2023-02-10 18:18 UTC, lena-larionova approved these changes

2023-02-10 21:35 UTC, lena-larionova approved these changes

2023-02-13 19:22 UTC, Guaris approved these changes

2023-02-13 19:22 UTC, Guaris commented on app/_data/tables/plugin_index.yml
> +      plus: Yes
```suggestion
      plus: No
```

2023-02-13 19:32 UTC, merged