docs(log): improve docs on log serialization format
Kong/docs.konghq.com pull request #5050
Opened 2023-01-18 15:13 UTC by jschmid1

### Description

* Order example log entry for increased readability
* Align explanation paragraph with this order
* Fix and improve description of log fields
* Added missing fields

KAG-157, KAG-158

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-01-20 21:03 UTC, Guaris commented
Is this for 3.2?

2023-01-24 09:58 UTC, hanshuebner requested changes

2023-01-24 09:58 UTC, hanshuebner commented on app/_includes/md/plugins-hub/json-object-log.md
> +* `tries` contains a list of iterations made by the load balancer for this request.
"contains a" could be left out.

2023-01-24 09:58 UTC, hanshuebner commented on app/_includes/md/plugins-hub/json-object-log.md
> +  * `balancer_start` unix timestamp for when the balancer started
Apparently, we want full stops after each item in a bullet list, so add them here.

2023-02-03 19:57 UTC, Guaris commented
Changed the base of the branch to 3.2

2023-02-03 20:12 UTC, Guaris approved these changes

2023-02-03 21:11 UTC, Guaris approved these changes
LGTM
Checked it here https://deploy-preview-5050--kongdocs.netlify.app/hub/kong-inc/file-log/

2023-02-03 21:11 UTC, merged