DOCU-2926: DCR overview page and new authentication methods
Kong/docs.konghq.com pull request #5107
Opened 2023-01-31 23:36 UTC by acgoldsmith

### Description

* adds new overview page for DCR including summary of available methods w/ new items bearer tokens and session cookies.
* new images to show options including bearer token UI
* reference links to IdP bearer token endpoints
* sourced from https://github.com/Kong/khcp/pull/5468 
* ref DOCU-2926

### Testing instructions

* needs SME review from @sunnytoolsmiths 
* need to see how images render

### Checklist 

- [ x] Review label added 
- [ x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-02-01 14:48 UTC, Guaris commented on app/konnect/dev-portal/applications/dynamic-client-registration/overview.md
> +Dynamic Client Registration (DCR)support in {{site.konnect_short_name}} provides multiple methods by which applications can be authenticated using industry-standard protocols.
```suggestion
Dynamic Client Registration (DCR) support in {{site.konnect_short_name}} provides multiple methods by which applications can be authenticated using industry-standard protocols.
```

2023-02-01 17:09 UTC, sunnytoolsmiths reviewed
Please update the side nav bar from portal auth to portal RBAC

In the API reference, please update portal auth API to portal rbac API

2023-02-01 17:10 UTC, sunnytoolsmiths requested changes
Please replace portal auth with portal rbac in the nav bar and API reference doc.

2023-02-01 22:00 UTC, sunnytoolsmiths requested changes
can we please also add the section about client credentials and session cookie

2023-02-16 19:07 UTC, Mierenga reviewed
@acgoldsmith Thanks for putting this info together, I've added a few suggestions that hopefully could clarify some things

2023-02-23 16:25 UTC, acgoldsmith reviewed
merging SME review, thanks @Mierenga

2023-02-23 17:13 UTC, lena-larionova commented on app/_data/docs_nav_konnect.yml
> +              url: /dev-portal/applications/dynamic-client-registration/overview
Can you please rename the file from `overview.md` to `index.md`? Using "overview" lengthens the URL unnecessarily.

2023-02-23 17:14 UTC, cloudjumpercat commented on app/konnect/dev-portal/applications/dynamic-client-registration/overview.md
> +DCR support in {{site.konnect_short_name}} provides multiple methods by which applications can be authenticated using industry-standard protocols. These methods include:
```suggestion
{{site.konnect_short_name}} provides multiple methods by which applications can be authenticated using industry-standard protocols. These methods include:
```
Just a suggestion, I think either one gets the meaning across.

2023-02-23 17:15 UTC, cloudjumpercat commented on app/konnect/dev-portal/applications/dynamic-client-registration/overview.md
> +* **Session cookie**: Allow sessions from either client credentials or bearer tokens to persist via cookie until an expiration.
Is the expiration configured by the customer? Or is it a default set by the cookie/Konnect?

2023-02-23 17:15 UTC, lena-larionova commented on app/_data/docs_nav_konnect.yml
> +              url: /dev-portal/applications/dynamic-client-registration/overview
```suggestion
              url: /dev-portal/applications/dynamic-client-registration/
```
once the file is renamed, can shorten this URL.

2023-02-23 17:19 UTC, cloudjumpercat approved these changes
Left a few nitpick suggestions, but everything else looks really good!

2023-02-24 21:34 UTC, merged