[DOCU-3026][DOCU-3030] Consolidate "manage runtime groups" topics
Kong/docs.konghq.com pull request #5285
Opened 2023-03-14 17:45 UTC by lena-larionova

### Description

- Consolidating https://docs.konghq.com/konnect/runtime-manager/runtime-groups/manage/ and https://docs.konghq.com/konnect/runtime-manager/runtime-groups/declarative-config/.
  - ❗**Reviewers:** Does it look strange that the majority of the new combines topic is decK instructions? I don't really know how to make it better. Maybe expand the "Manage using Runtime Manager" section with.. something?
- New topic for backup and restore.

https://konghq.atlassian.net/browse/DOCU-3026
https://konghq.atlassian.net/browse/DOCU-3030

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-03-17 15:02 UTC, Guaris commented
> ❗Reviewers: Does it look strange that the majority of the new combines topic is decK instructions? I don't really know how to make it better. Maybe expand the "Manage using Runtime Manager" section with.. something?

If I look at the start of your doc: 

Through the Runtime Manager in Konnect - Using Konnect should be UI drive, and the dashboard screenshot will aid in uncovering possibilities. 
Using declarative configuration files and decK - Deck obviously needs docs. 
Using the Konnect [Runtime Groups API] - Actually using the API to manage Runtime groups needs docs. 

With that logic, I think for both discoverability and clarity, the Manage Runtime Groups doc should be about decK. 

The backup and restore doc I think is fine, though it may help to explain that decK is the best way to do it, or the only way to do it, in the first paragraph.

2023-03-17 15:04 UTC, Guaris requested changes
comment above.

2023-03-23 23:15 UTC, lena-larionova commented on app/_data/docs_nav_konnect.yml
> +      url: /runtime-manager/declarative-config
Moved this down because I don't know that we want "Manage Runtime Groups using decK" appearing above config & instances.

2023-03-27 14:35 UTC, Guaris approved these changes

2023-03-28 16:21 UTC, merged