[DOCU-3172] MinK: Overview + UI screenshot
Kong/docs.konghq.com pull request #5432
Opened 2023-04-12 21:15 UTC by cloudjumpercat

### Description

What did you change and why?

- Added content to the MinK overview page
- I'll also add a screenshot at some point, UI isn't quite there yet and doesn't have a robust example yet

 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.
DOCU-3172

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-06-13 21:01 UTC, cloudjumpercat commented on app/konnect/mesh-manager/service-mesh.md
> +* [Download the latest version of {{site.mesh_product_name}}](/mesh/latest/production/install-kumactl/)
```suggestion
* [The latest version of {{site.mesh_product_name}} installed](/mesh/latest/production/install-kumactl/)
```

2023-06-14 20:26 UTC, cloudjumpercat commented on app/konnect/mesh-manager/service-mesh.md
> +=======
```suggestion
* The latest version of [{{site.mesh_product_name}} installed](/mesh/latest/production/install-kumactl/)
```

2023-06-14 20:27 UTC, cloudjumpercat commented on app/konnect/mesh-manager/service-mesh.md
> +* [Download the latest version of {{site.mesh_product_name}}](/mesh/latest/production/install-kumactl/)
```suggestion
```

2023-06-14 20:49 UTC, cloudjumpercat commented on app/konnect/mesh-manager/service-mesh.md
> +>>>>>>> f4996ec469bff82b70f8e9b2a93f0b15c12f6c7b
```suggestion
```

2023-06-20 23:56 UTC, johnharris85 requested changes

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
> +Mesh Manager in {{site.konnect_product_name}} allows you to create and view your {{site.mesh_product_name}} [service meshes](/mesh/latest/introduction/what-is-a-service-mesh/) in the {{site.konnect_s
```suggestion
Mesh Manager in {{site.konnect_product_name}} allows you to create, manage and view your {{site.mesh_product_name}} [service meshes](/mesh/latest/introduction/what-is-a-service-mesh/) in the {{site.konnect_short_name}} UI and using the {{site.konnect_short_name}} platform.
```

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
> +Mesh Manager in {{site.konnect_product_name}} allows you to create and view your {{site.mesh_product_name}} [service meshes](/mesh/latest/introduction/what-is-a-service-mesh/) in the {{site.konnect_s
Those capabilities are coming but don't exist today / GA.

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
> +Mesh Manager is ideal for organizations who want to have a global control plane that allows you to run your service mesh in multiple zones. You can run a mix of Kubernetes and Universal zones. Your m
```suggestion
Mesh Manager is ideal for organizations who want to have one or more global control planes that allow you to run your service mesh across multiple zones. You can run a mix of Kubernetes and Universal zones. Your mesh deployment environments can include multiple isolated service meshes (for multi-tenancy) and workloads running in different regions, on different clouds, or in different data-centers.
```

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
> +* Data plane proxies
```suggestion
```

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
> +* Data plane proxies
DPPs already called out on the first line

2023-06-20 23:56 UTC, johnharris85 commented on app/konnect/mesh-manager/service-mesh.md
> +Creating a fully-functioning {{site.mesh_product_name}} global control plane in {{site.konnect_short_name}} involves the following steps:
```suggestion
Creating a fully-functioning {{site.mesh_product_name}} deployment in {{site.konnect_short_name}} involves the following steps:
```

2023-06-21 16:15 UTC, acgoldsmith approved these changes
LGTM - approving for merge into feature branch

2023-06-21 16:19 UTC, acgoldsmith commented
adding back DNM as we still need the final Mesh Manager icon

2023-06-21 16:55 UTC, acgoldsmith commented on app/konnect/mesh-manager/service-mesh.md
> +1. From the left navigation menu in {{site.konnect_short_name}}, open [MESH MANAGER ICON HERE] [**Mesh Manager**](https://cloud.konghq.com/mesh-manager).
```suggestion
1. From the left navigation menu in {{site.konnect_short_name}}, open [/assets/images/icons/konnect/icn-mesh-manager.svg] [**Mesh Manager**](https://cloud.konghq.com/mesh-manager).
```

2023-06-21 18:43 UTC, merged