docs(proxy-cache-advanced): add ignore_uri_case
Kong/docs.konghq.com pull request #5458
Opened 2023-04-18 19:36 UTC by samugi

### Description

Add `ignore_uri_case` configuration parameter to `proxy-cache-advanced`, similar to https://github.com/Kong/docs.konghq.com/pull/5270/files (for proxy-cache).

### Testing instructions

Netlify link: 

### Checklist 

- [X] Review label added
- [X] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-04-24 18:37 UTC, lena-larionova commented on app/_hub/kong-inc/proxy-cache-advanced/_index.md
> +        If set to `true`, requests will be cached while ignoring case sensitivity in the URI.
```suggestion
        Determines whether to treat URIs as case sensitive. By default, case sensitivity is enabled. If set to `true`, requests are cached while ignoring case sensitivity in the URI.
```
How about something like this? The initial description feels like it's missing some context.

2023-04-24 18:38 UTC, lena-larionova requested changes
Can you please add a changelog entry to the bottom of the same file?

2023-04-26 07:44 UTC, samugi commented
all done @lena-larionova, thank you!

2023-04-26 16:41 UTC, lena-larionova approved these changes
LGTM!

2023-04-26 16:41 UTC, lena-larionova commented on app/_hub/kong-inc/proxy-cache-advanced/_index.md
> +    - name: ignore_uri_case
```suggestion
    - name: ignore_uri_case
      minimum_version: "3.3.x"
```
Missed one thing.

2023-04-26 17:13 UTC, merged