[DOCU-3051] Auto docs 3.3
Kong/docs.konghq.com pull request #5549
Opened 2023-05-10 18:25 UTC by Guaris

https://konghq.atlassian.net/browse/DOCU-3051

Auto docs for EE and OSS.

2023-05-10 18:28 UTC, Guaris commented on app/_src/gateway/plugin-development/pdk/kong.request.md
> +{% if_version lte 3.2 %}
```suggestion
{% if_version lte:3.2.x %}
```

2023-05-10 18:28 UTC, Guaris commented on app/_src/gateway/plugin-development/pdk/kong.request.md
> +{% if_version gte 3.3 %}
```suggestion
{% if_version gte:3.3.x %}
```

2023-05-10 18:28 UTC, Guaris commented on app/_src/gateway/plugin-development/pdk/kong.response.md
> +{% if_version lte:3.2 %}
```suggestion
{% if_version lte:3.2.x %}
```

2023-05-10 18:28 UTC, Guaris commented on app/_src/gateway/plugin-development/pdk/kong.response.md
> +{% if_version lte:3.3 %}
```suggestion
{% if_version gte:3.3.x %}
```

2023-05-10 18:28 UTC, Guaris commented on app/_src/gateway/plugin-development/pdk/kong.tracing.md
> +{% if_version gte:3.2.x %}
```suggestion
{% if_version lte:3.2.x %}
```

2023-05-10 22:43 UTC, lena-larionova approved these changes
Looks good to me! You mentioned that CLI will come separately, right?

2023-05-10 23:28 UTC, lena-larionova requested changes
Never mind, something's off. There's a bunch of [changes to kong.conf.default](https://github.com/Kong/kong-ee/commits/next/3.3.x.x/kong.conf.default) that I don't see reflected here. Did you build from OSS or Enterprise? 

Or maybe the build image has an old copy of the file. Though it would have to be pretty old - I went looking for `cluster_dp_labels`, which was [added March 30th](https://github.com/Kong/kong/pull/10471/files), and didn't see it in this PR.

2023-05-11 16:39 UTC, Guaris commented
> Never mind, something's off. There's a bunch of [changes to kong.conf.default](https://github.com/Kong/kong-ee/commits/next/3.3.x.x/kong.conf.default) that I don't see reflected here. Did you build from OSS or Enterprise?
> 
> Or maybe the build image has an old copy of the file. Though it would have to be pretty old - for example, I went looking for `cluster_dp_labels`, which was [added March 30th](https://github.com/Kong/kong/pull/10471/files), and didn't see it in this PR.

Ready, added all of that stuff in. Checked the CLI and no changes in OSS and EE that affect docs.

2023-05-11 16:56 UTC, lena-larionova commented on app/_src/gateway/reference/configuration.md
> +---
This entry appears twice. Looks like the issue is the source file though, that'll need fixing.

```suggestion
```

2023-05-11 18:30 UTC, merged