[DOCU-3153] Contextual Developer Analytics
Kong/docs.konghq.com pull request #5683
Opened 2023-06-08 15:33 UTC by Guaris

Contextual Developer Analytics PR

https://konghq.atlassian.net/jira/software/c/projects/DOCU/boards/58?modal=detail&selectedIssue=DOCU-3153

https://deploy-preview-5683--kongdocs.netlify.app/konnect/dev-portal/
https://deploy-preview-5683--kongdocs.netlify.app/konnect/dev-portal/customization/
https://deploy-preview-5683--kongdocs.netlify.app/konnect/dev-portal/applications/application-overview/

2023-06-08 20:35 UTC, lena-larionova requested changes

2023-06-08 20:35 UTC, lena-larionova commented on app/konnect/dev-portal/index.md
> +The Developer Portal supports built-in analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This feature gives developers the ability to gain insights into all
```suggestion
You can view analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This gives developers the ability to gain insights into all of their applications and the relationships between applications and APIs using a fully customizable dashboard. 

Each application has its own dashboard, which provides a high-level summary of the **Number of Requests**, **Average Error Rate**, and **p99 Latency**, and charts for the following data points: 
```
Rephrased some repetitive wording.

 "Each application has its own dashboard that provides" doesn't work - Either:
* "Each application has a dashboard that provides"
* "Each application has its own dashboard, which provides"

I suggested the "which" phrasing, but you're welcome to go with the other option.

2023-06-08 20:35 UTC, lena-larionova commented on app/konnect/dev-portal/index.md
> +> Free accounts will only have access to a time range of 24 hours.
```suggestion
> Free accounts only have access to a time range of 24 hours.
```

2023-06-08 20:35 UTC, lena-larionova commented on app/konnect/dev-portal/index.md
> +* P99 Latency by version
```suggestion
* P99 latency by version
```

2023-06-20 08:57 UTC, sichvoge requested changes
Important comments before I can go ahead and approve this PR.

2023-06-20 08:57 UTC, sichvoge commented on app/konnect/dev-portal/index.md
> +You can view analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This gives developers the ability to gain insights into all of their applications and the rel
Fully customizable dashboards is not correct. Background and some headers change based on configurations made in the dev portal appearance but you can't change the tiles that host the visualizations. Those tiles stay with white background, black text, etc.

Example:
![image](https://github.com/Kong/docs.konghq.com/assets/498114/8a8eb33a-dd55-4be8-bfa4-0317a3b55c59)

Page background is blue(ish).
Header is red(ish)
Tile background is still white.

2023-06-20 08:57 UTC, sichvoge commented on app/konnect/dev-portal/index.md
> +All of these metrics can be configured across a time range up to **30 days**.
Relative timeframe is up to "Last 30 days" but you can go back up to 90 days with custom.

2023-06-20 08:57 UTC, sichvoge commented on app/konnect/dev-portal/customization/index.md
> +### Developer analytics dashboard
Please remove this section. You can't customize in this version.

2023-06-20 19:03 UTC, sichvoge requested changes
One last 💪

2023-06-20 19:03 UTC, sichvoge commented on app/konnect/dev-portal/index.md
> +You can view analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This gives developers the ability to gain insights into all of their applications and the rel
I think we should avoid saying "customizable" in this sentence. Readers may think that that they can add/remove charts from this dashboard (which is referred to as "customizable dashboard").

2023-06-20 20:33 UTC, Guaris commented on app/konnect/dev-portal/index.md
> +You can view analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This gives developers the ability to gain insights into all of their applications and the rel
```suggestion
You can view analytics for developer applications from within the {{site.konnect_short_name}} Dev Portal. This gives developers the ability to gain insights into all of their applications and the relationships between applications and APIs.
```

2023-06-21 14:41 UTC, sichvoge approved these changes
LGTM 👍

2023-06-28 21:22 UTC, acgoldsmith approved these changes
LGTM

2023-07-03 15:46 UTC, merged