Add advanced settings instructions
Kong/docs.konghq.com pull request #5752
Opened 2023-06-26 21:44 UTC by haydenlam

### Description

What did you change and why?
 
Added docs for advanced OIDC configuration settings. 
https://konghq.aha.io/epics/KP-E-313

### Testing instructions

Advanced settings are visible here: https://cloud.konghq.com/global/organization/idp-settings#authentication-scheme
Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-06-26 21:57 UTC, lena-larionova requested changes

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +You can configure customize IdP specific behaviors in the **Advanced Settings** of the OIDC configuration form. The following options are available:
```suggestion
You can configure custom IdP-specific behaviors in the **Advanced Settings** of the OIDC configuration form. The following options are available:
```

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +1. Scopes - Scopes allow you to specify the list of scopes Konnect will request from the IdP. By default, we request the `openid`, `email` and `profile` scopes. The `openid` scope is required and can
```suggestion
1. **Scopes**: Specify the list of scopes {{site.konnect_short_name}} requests from the IdP. By default, {{site.konnect_short_name}} requests the `openid`, `email`, and `profile` scopes. The `openid` scope is required and cannot be removed.
```

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +2. Claim Mappings - Claim mappings allows you to customize the mapping of required attributes to different claim in the id_token we receive from the IdP. By default, Konnect requires three attributes
```suggestion
2. **Claim Mappings**: Customize the mapping of required attributes to a different claim in the `id_token` {{site.konnect_short_name}} receives from the IdP. By default, {{site.konnect_short_name}} requires three attributes: Name, Email, and Groups. The values in these attributes are mapped as follows:
```

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +    - Name from `name` - used as the Konnect accounts `full_name`.
```suggestion
    - `name`: Used as the {{site.konnect_short_name}} account's `full_name`.
```
I'd say that repeating the value is redundant here.

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +    - Email from `email` - used as the Konnect account's `email`.
```suggestion
    - `email`: Used as the {{site.konnect_short_name}} account's `email`.
```

2023-06-26 21:57 UTC, lena-larionova commented on app/konnect/org-management/oidc-idp.md
> +    - Groups from `groups` - used to map users to teams defined in the team mappings upon login.
```suggestion
    - `groups`: Used to map users to teams defined in the team mappings upon login.
```

2023-06-26 22:13 UTC, haydenlam commented
Thanks @lena-larionova for the review and suggestions!

2023-06-26 22:23 UTC, lena-larionova approved these changes
Looks pretty good to me! 
https://deploy-preview-5752--kongdocs.netlify.app/konnect/org-management/oidc-idp/#advanced-settings

Feel free to merge whenever you need to.

2023-06-28 21:28 UTC, acgoldsmith commented
@haydenlam , This is part of DOCU-3061, so needs to release along with https://github.com/Kong/docs.konghq.com/pull/5376

2023-06-30 05:16 UTC, merged