API Products in Konnect
Kong/docs.konghq.com pull request #5760
Opened 2023-06-28 15:47 UTC by Guaris

2023-06-28 16:20 UTC, sichvoge requested changes
Few changes on the roles description.

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
> +| Admin | Admin of an existing {{site.konnect_short_name}} service. The admins have all write access related to a Gateway service and API product versions. |
```suggestion
| Admin | Admin of an existing API product. The admins have all write access permissions related to a API product, API product version, etc. |
```

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
> +| Creator | Access to create new API product to productize services in API Products. The creator becomes the owner of the API product they create, gaining admin access to the API product. <br><br>Thi
```suggestion
| Creator | Access to create new API product in API Products. The creator becomes the owner of the API product they create, gaining admin access to the API product. This role does not provide access to creating sub-entities in an API product such as API product versions or API specs, or link the API product version to a Gateway service. See the Admin or Maintaine role. |
```

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
> +| Deployer | Access to implement and associate a Gateway service to a runtime group. <br><br> Must also have the `Deployer` role for the associated runtime group. |
Please remove.

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
> +| Plugins Admin | Access to install plugins on the Gateway service, runtime group, consumers, and routes. <br><br> Must also have the `Admin` role in the associated runtime group. |
Please remove.

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
> +| Maintainer | Access to read, edit, and deploy a Gateway service and its corresponding API product version versions, and manage its plugins. |
```suggestion
| Maintainer | Access to fully manage an API product and its API product versions including app registration, publishing documentation, etc. |
```

2023-06-28 16:20 UTC, sichvoge commented on app/konnect/org-management/teams-and-roles/roles-reference.md
>  | Viewer | Read-only access to all the configurations of a {{site.konnect_short_name}} service, including attributes, versions, Analytics reports, and plugins. |
```suggestion
| Viewer | Read-only access on an API product including API product versions and its configuration, analytics, and documentation. |
```

2023-06-28 21:10 UTC, acgoldsmith commented
@sichvoge - this is ready for release next week, and internal release today. 

Please note: 

Before merging the PR please publish the spec:
https://cloud.konghq.com/us/servicehub/d420333f-01b0-464e-a87a-97acc92c2026/overview

2023-06-29 14:21 UTC, sichvoge commented
Please make the following changes on [this page](https://deploy-preview-5760--kongdocs.netlify.app/konnect/org-management/teams-and-roles/teams-reference/):

Both `Service Admin` and `Service Developer` become `API Product Admin` and `API Product Developer`. The descriptions changes also:

- `API Product Admin`: Allow creating and managing API products, including publishing API product versions to developer portal and enabling application registration.
- `API Product Develope`r: Allow creating and managing versions of API products.

2023-06-30 09:05 UTC, sichvoge approved these changes
LGTM 👍

2023-07-10 21:42 UTC, merged