DOCU-3314 Post-GA release of API Product Builder spec
Kong/docs.konghq.com pull request #5783
Opened 2023-07-07 19:46 UTC by acgoldsmith

### Description

Split from https://github.com/Kong/docs.konghq.com/pull/5760

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-07-11 14:21 UTC, cloudjumpercat approved these changes
LGTM! Looks like this is causing the broken link checker to fail, but I'm guessing that it's because the spec isn't published yet, not because the URL is wrong.

2023-07-11 14:24 UTC, acgoldsmith commented
@sichvoge , this PR is ready to merge for tomorrow's release. Please ensure the spec is live at https://developer.konghq.com/spec/d420333f-01b0-464e-a87a-97acc92c2026/941af975-8cfa-40f7-afea-e82d248489a0 ahead of merging this PR. Thanks!

2023-07-17 09:33 UTC, sichvoge requested changes
Adjust release notes to match mine.

2023-07-17 09:33 UTC, sichvoge commented on app/konnect/updates.md
> +: The API products API has been released to support the objective of making API consumption straightforward for developers. Explore the API spec on our [Dev Portal](https://developer.konghq.com/spec/
```suggestion
: A new Konnect API for managing API products and versions is now available for external consumption. This API allows you to create and manage API products and versions, upload documentation and spec, and link a version to an existing Gateway service to enable application registration. As a result, you can easily integrate this API into your automated pipeline to streamline publishing documentation for your products to your third party developers. Explore the API spec on our [Developer Portal](https://developer.konghq.com/spec/d420333f-01b0-464e-a87a-97acc92c2026/941af975-8cfa-40f7-afea-e82d248489a0)
```

2023-07-17 14:06 UTC, cloudjumpercat commented on app/konnect/updates.md
> +: A new Konnect API for managing API products and versions is now available for external consumption. This API allows you to create and manage API products and versions, upload documentation and spec
```suggestion
: A new {{site.konnect_short_name}} API for managing API products and versions is now available for external consumption. This API allows you to create and manage API products and versions, upload documentation and specs, and link a version to an existing Gateway service to enable application registration. As a result, you can integrate this API into your automated pipeline to streamline publishing documentation for your products to your third-party developers. Explore the API spec on our [Developer Portal](https://developer.konghq.com/spec/d420333f-01b0-464e-a87a-97acc92c2026/941af975-8cfa-40f7-afea-e82d248489a0)
```

2023-07-17 14:19 UTC, merged