Rename: Konnect Get Started section
Kong/docs.konghq.com pull request #5961
Opened 2023-08-17 13:49 UTC by cloudjumpercat

### Description

What did you change and why?
- **Why:** Konnect is renaming certain features to better align with industry standards, so our docs need to be updated to reflect the new names
- **What:** Renamed features in the Get Started section of the docs. See the linked ticket for more info about which names are changing. 
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.
DOCU-3370

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-08-17 13:50 UTC, cloudjumpercat commented on app/konnect/getting-started/configure-data-plane-node.md
> +title: Configure a Data Plane Node
❗ For reviewers: Here and throughout this PR, if you could make sure I used the correct words in place of "runtime" that would be great. I sometimes had a hard time deciding if it should be control plane, data plane node, or data plane.

2023-08-21 20:39 UTC, Guaris requested changes
Things I wasn't able to leave a comment on because of Github: 

Line 65 of `app/konnect/getting-started/deploy-service.md`

Runtime manager -> Gateway manager. 

Line 68 of `app/konnect/getting-started/deploy-service.md`

Runtime -> data plane


Let me know if I can help with anything.

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/configure-data-plane-node.md
>      {{site.base_gateway}} instance and connects it to your
```suggestion
    {{site.base_gateway}} and connects it to your
```

I can't add it as a suggestion but the "a" before KGW should be removed.

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/configure-data-plane-node.md
> +The default proxy URL for this control plane is `http://localhost:8000`. Take
```suggestion
The default proxy URL for the data plane is `http://localhost:8000`. Take
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/deploy-service.md
> +Create a {{site.konnect_short_name}} Gateaway service to proxy your APIs. In this guide, you will create, proxy, and test a gateway service using Gateway Manager in {{site.konnect_short_name}}.
```suggestion
Create a {{site.konnect_short_name}} Gateaway service to proxy your APIs. In this guide, you will create, proxy, and test a gateway service using the {{site.konnect_short_name}} Gateway Manager. 
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/deploy-service.md
> +your control plane's default proxy URL is `localhost:8000`.
```suggestion
your default proxy URL is `localhost:8000`.
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/deploy-service.md
> +[Configured a data plane node](/konnect/getting-started/configure-data-plane-node).
```suggestion
[configured a data plane node](/konnect/getting-started/configure-data-plane-node).
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/deploy-service.md
>  If you used the Docker script to create a container
```suggestion
If you used the Docker script to connect a data plane
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/index.md
>      and available for testing.
```suggestion

```
This doesn't really make sense to me ( I know you didn't write it). But I think this should be rewritten to talk about automatically connecting your data planes using the script in the Gateway manager.

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/index.md
> +    [Set up a data plane node &gt;](/konnect/getting-started/configure-data-plane-node/)
```suggestion
    [Create a data plane node &gt;](/konnect/getting-started/configure-data-plane-node/)
```

I think configure  or connect could also work here, it depends on your perspective. The node is already created you run a script on it and it's configured to connect and work on Konnect. 
set up works better with something ephemeral like runtime instance.

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/productize-service.md
> +    Choose a [control plane](/konnect/gateway-manager/control-plane-groups/) and [Gateway Service](/konnect/gateway-manager/configuration/#gateway-services) to
```suggestion
    Choose the [control plane](/konnect/gateway-manager/control-plane-groups/) and [Gateway Service](/konnect/gateway-manager/configuration/#gateway-services) to
```

2023-08-21 20:39 UTC, Guaris commented on app/konnect/getting-started/productize-service.md
> +    data planes in a specific environment.
It wont let me leave a suggestion here, but we should remove the use of specific twice here. Maybe "this lets you deploy your service across a data planes associated with the control plane"

2023-08-29 19:42 UTC, acgoldsmith approved these changes
LGTM

2023-08-29 19:43 UTC, merged