Rename Runtime Manager + update related terms
Kong/docs.konghq.com pull request #6071
Opened 2023-09-07 16:44 UTC by lena-larionova

### Description

Renaming the following, starting with the Runtime Manager section to a full Konnect doc cleanup:

* Runtime Manager to Gateway Manager
* Runtime Groups to Control Plane
* Composite Runtime Groups to Control Plane Group
* Runtime Instances to Data Plane Nodes

Based on those main names, we also get:
* "Composite" to "combined" (when referring to config)
* "Runtime", "instance", or "group" to "data plane node"
* "Data plane" to "data plane node"

No screenshots or diagrams in this one as the scope of this PR is already really big.
Will update any needed images separately.

https://konghq.atlassian.net/browse/DOCU-3371

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-09-08 15:54 UTC, Guaris requested changes
I don't think "combined" is the right word when referring to config, I think it should remain composite.



"Data plane" to "data plane node" - This can't be a blanket case, and in some cases its not appropriate. 

Data plane node refers to the specific, literal component within a network for lack of a better word, the machine. data plane refers to the broader concept that forwards and proxies traffic. Replacing every instance of data plane with data plane node, risks losing this differentiation. It also risks narrowing the focus of the reader . 

here is an example: 

"The data plane is responsible for efficiently forwarding traffic from the service to the KGWCP"

In this sentence data plane is not referring to the literal component, ie: the docker container, the aws instance, etc. But rather it emphasizes the overfall function of forwarding traffic within the network. 

You replace data plane with data plane node, but then the focus shifts towards the literal component. 
So in this sentence: 

"Each data plane node can be hosted by you on AWS, or even locally."

In this case the sentence is about the component, not about the function. 


This opens us up to write clear and complex sentences like: 

"In the Konnect architecture, the data plane, composed of a combination of self-hosted, and cloud-hosted data plane nodes is responsible for forwarding traffic to the Konnect control plane." 


"Runtime", "instance", or "group" to "data plane node"

This can't be a blanket either, instances and groups  are still a valid words with existing associations outside of Kong that we can use to communicate clearly information inside of Kong.

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
> +1. Open the `values.yaml` file for your data plane node and update it to point
```suggestion
1. Open the `values.yaml` file for the data plane node and update it to point
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/index.md
> +> _**Figure 1:** Example control plane configuration with three control planes: the default, a development plane, and a production plane. {{site.konnect_short_name}} is the SaaS-managed global manage
```suggestion
> _**Figure 1:** Example control plane group configuration for three control planes: the default, a development CP, and a production CP. {{site.konnect_short_name}} is the SaaS-managed global management plane that manages all of the control planes, while the control planes manage configuration for data plane nodes._
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/index.md
> +> _**Figure 1:** Example control plane configuration with three control planes: the default, a development plane, and a production plane. {{site.konnect_short_name}} is the SaaS-managed global manage
it feels odd to just use the word plane.

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/index.md
> +nodes in control plane the have been accounted for.
```suggestion
nodes in the control plane the have been accounted for.
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/index.md
> +initial configuration or setup.
```suggestion
Docker container running Linux, on MacOS, or on Windows. 
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/gateway-manager/kic.md
> +> **Figure 1:** This image shows a KIC data plane node dashboard. For each KIC data plane node, you can see details about the data plane node, analytics, and KIC status details.
```suggestion
> **Figure 1:** This image shows a KIC data plane node dashboard. For each KIC data plane node, you can see details about an individual data plane node, analytics, and KIC status details.
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/network-resiliency.md
> +  data plane nodes in the cluster.
```suggestion
  data plane node in the cluster.
```

2023-09-08 15:54 UTC, Guaris commented on app/konnect/network-resiliency.md
> +### How frequently does data travel between the control plane and data plane nodes?
```suggestion
### How frequently does data travel between the Konnect control plane and data plane nodes?
```

It feels like we have to be specific here. I think this coiuld either be "between the control plane and the data planes", or "....Konnect control plane and the data plane nodes".

2023-09-08 15:59 UTC, lena-larionova commented
@Guaris I hear you on data plane vs data plane node, but most of the time we are referring to nodes. I'll fix up the places where it wasn't obvious.

Re: Runtime", "instance", or "group" to "data plane node
- was not a blanket change, I went through them one by one. In our docs, we have historically used all three of those terms to refer to what we're now calling "data plane nodes". So, wherever appropriate, I changed them to data plane node or simply node. 
- composite to combined: I think there's only two instances of that term change. I went back and forth on it, wasn't sure if the word "composite" was clear now that there's no composite group. I can change them back.

2023-09-08 16:09 UTC, lena-larionova commented on app/konnect/gateway-manager/troubleshoot.md
> +a node running an older version of {{site.base_gateway}}, your data plane node
Why this change? I think it's clear to say "data plane node" in the previous sentence, then just use "node" here. I _don't_ think "data plane" is accurate, as we're talking about individual nodes specifically here.

2023-09-12 13:59 UTC, Guaris approved these changes

2023-09-12 13:59 UTC, merged