feat: Implement Mesh in Konnect feedback
Kong/docs.konghq.com pull request #6098
Opened 2023-09-13 19:41 UTC by cloudjumpercat

### Description

We had several misc bits of MinK feedback that needed to be implemented for GA, this PR makes changes based on that feedback.
 

DOCU-3469
### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-09-14 19:58 UTC, cloudjumpercat commented
@johnharris85 Hi! I had a couple questions:
- Do you have the non-beta API URL so I can add that?
- For the updates to [Network Resiliency and Availability](https://deploy-preview-5704--kongdocs.netlify.app/konnect/network-resiliency/), could you send a link of the Mesh doc that covers connection behavior? I couldn't find it.

2023-09-14 20:04 UTC, cloudjumpercat commented
@Guaris @lena-larionova John asked me to add Mesh to the [Konnect installation options page](https://docs.konghq.com/konnect/runtime-manager/runtime-instances), but since that's shared with runtime manager, that might be kind of confusing? Maybe less confusing after the rename, but it still feels like maybe the install options page shouldn't be shared between the Support and Runtime Manager sections if we want to add other things, like Mesh. Thoughts?

2023-09-14 20:08 UTC, lena-larionova commented
> John asked me to add Mesh to the [Konnect installation options page](https://docs.konghq.com/konnect/runtime-manager/runtime-instances), but since that's shared with runtime manager, that might be kind of confusing? Maybe less confusing after the rename, but it still feels like maybe the install options page shouldn't be shared between the Support and Runtime Manager sections if we want to add other things, like Mesh. Thoughts?

Agreed. Mesh doesn't belong on that page, that page is for installation options for Kong Gateway data plane nodes. Also, that page and the parallel page in Konnect are both nested under Runtime Manager/Gateway Manager. Mesh should have its own page.

2023-09-14 20:09 UTC, lena-larionova commented
> > John asked me to add Mesh to the [Konnect installation options page](https://docs.konghq.com/konnect/runtime-manager/runtime-instances), but since that's shared with runtime manager, that might be kind of confusing? Maybe less confusing after the rename, but it still feels like maybe the install options page shouldn't be shared between the Support and Runtime Manager sections if we want to add other things, like Mesh. Thoughts?
> 
> Agreed. Mesh doesn't belong on that page, that page is for installation options for Kong Gateway data plane nodes. Also, that page and the parallel page in Konnect are both nested under Runtime Manager/Gateway Manager. Mesh should have its own page.

To be completely honest, I don't know that a shared installation options page even makes sense. Mesh install vs Kong Gateway install are two different things.

2023-09-15 20:05 UTC, johnharris85 commented
I don't have preference whether it's on that page, or on a different page (and rename both to have one for gateway and one for mesh). Just think it needs to be there once Mesh Manager in Konnect goes live.

2023-09-15 22:40 UTC, johnharris85 requested changes
Added a few comments / changes but otherwise LGTM. Thanks!

2023-09-15 22:40 UTC, johnharris85 commented on app/assets/images/docs/konnect/konnect-intro.png
This new pic looks great. Technically it's zone control planes that connect to Kong Mesh in Konnect though, not Data Plane Nodes. Is this a docs-owned image or something by design? Or do we think it's even important enough to 'correct'?

2023-09-15 22:40 UTC, johnharris85 commented on app/konnect/getting-started/configure-mesh.md
> +<!--* (not sure if I removed the right line, so keeping in for easy swap
Yep this edit is great :+1:

2023-09-15 22:40 UTC, johnharris85 commented on app/konnect/getting-started/configure-mesh.md
> +?
The output for this command is actually not great today, I have an open issue to track. For now maybe let's just delete the `something like:` and following bash section and just say something like "you should see all 4 dataplanes show in the listed tabular output" or similiar?

2023-09-15 22:40 UTC, johnharris85 commented on app/konnect/network.md
> +If you plan to use [Mesh Manager](/konnect/mesh-manager/) to manage your Kong service mesh, you must add the `<region>.mesh.sync.konghq.com:443` hostname to your firewall allowlist.
Do we want to re-iterate the possible options for `<region>` here? E.g. `Region can be us, eu, or global.` in the same way that it's called out above for Gateway Manager.

2023-09-15 22:40 UTC, johnharris85 commented on app/konnect/org-management/deactivation.md
> +* {{site.product_mesh_name}} data planes continue to run.
```suggestion
* {{site.product_mesh_name}} local zone control planes and dataplanes (workloads) continue to run, but will not receive new updates to configuration.
```

2023-09-15 22:40 UTC, johnharris85 commented on app/konnect/org-management/deactivation.md
> +* The control plane (both the {{site.base_gateway}} and {{site.product_mesh_name}} control planes) associated with the organization is decommissioned.
```suggestion
* The control plane (both the {{site.base_gateway}} and {{site.product_mesh_name}} global control planes) associated with the organization is decommissioned.
```

2023-09-18 20:28 UTC, johnharris85 commented
This PR LGTM, thanks!

2023-09-20 15:19 UTC, cloudjumpercat commented on app/konnect/mesh-manager/index.md
> +* Redhat
```suggestion
* Red Hat
```

2023-09-20 17:42 UTC, lena-larionova requested changes

2023-09-20 17:42 UTC, lena-larionova commented on app/assets/images/diagrams/diagram-mesh-in-konnect.png
The spacing on this diagram needs some adjusting, mainly on the CP tiles, as well as some of the element overlap/ordering. I adjusted the diagram in the slide deck a bit, you should be able to grab that one now (although seriously, those arrows do not look like they were fun to deal with).

2023-09-20 17:42 UTC, lena-larionova commented on app/assets/images/docs/konnect/konnect-intro.png
You might want to rebase on main now, because this change is going to conflict. 

I would also check with John to see if this is actually how it works. Is a Mesh control plane supposed to be on the same level as the Gateway and KIC control planes? I think there's some interconnectedness here that's a bit more complicated - but I could be wrong.

2023-09-20 17:42 UTC, lena-larionova commented on app/assets/images/icons/konnect/icn-mesh-manager-nav.svg
You'll need to change the color of this icon to match the rest of our nav. 
*  `#A3B6D9` should be `#1155cb`
* `#D9D9D9` should be `#ffffff`

 You can edit the svg as code directly.

2023-09-20 17:42 UTC, lena-larionova commented on app/konnect/network.md
>  Depending on your Runtime Group type, you may need to add hostnames to your firewall allowlist.
```suggestion
### Control planes

Depending on your control plane type, you may need to add hostnames to your firewall allowlist.
```

2023-09-21 16:26 UTC, cloudjumpercat commented
Just an FYI, [the image here](https://deploy-preview-6098--kongdocs.netlify.app/konnect/mesh-manager/) is incorrect due to issues with merge conflicts with the Great Rename (accidentally had two files named the same thing), but this is corrected in https://github.com/Kong/docs.konghq.com/pull/6134/files.

2023-09-22 13:42 UTC, cloudjumpercat commented on app/konnect/mesh-manager/index.md
❗ For reviewers: When it goes GA, MinK will only be for Enterprise and new Plus customers. I mention this in the release notes, but I think I should also mention it on the various minK doc pages. Should I add Enterprise/Plus badges to the pages, or would it be better to leave a note on those pages since it's only **New** plus, not all plus? Or no comment at all since it will eventually (not sure the timeline) be for everyone?

2023-09-22 14:38 UTC, johnharris85 commented on app/konnect/mesh-manager/index.md
What's our strategy for other things that will only be 'new' plus? Or is this the only thing? I like the badges idea.

2023-09-22 15:45 UTC, Guaris requested changes

2023-09-22 15:45 UTC, Guaris commented on app/konnect/getting-started/configure-mesh.md
I think this could be removed from getting started, added tot he mesh section and titled something like "How to use  X". But right now it's mixing too many things in at once. There is info about mesh, and a tutorial.

2023-09-22 15:45 UTC, Guaris commented on app/konnect/network-resiliency.md
> +If the global {{site.mesh_product_name}} control plane and zone control plane become disconnected, configuration can't travel between them. You can see [Failure modes](/mesh/latest/production/deploym
```suggestion
If the global {{site.mesh_product_name}} control plane and zone control plane become disconnected, and configuration can't sync between them. You can see [Failure modes](/mesh/latest/production/deployment/multi-zone/#failure-modes) in the {{site.mesh_product_name}} documentation for more details on what happens when there are {{site.mesh_product_name}} connectivity issues.
```

2023-09-22 15:45 UTC, Guaris commented on app/konnect/network-resiliency.md
> +If the global {{site.mesh_product_name}} control plane and zone control plane become disconnected, configuration can't travel between them. You can see [Failure modes](/mesh/latest/production/deploym
I think? This is what you meant. 

Is the purpose to redirect them to the failure modes doc? Then I would do it sooner. 

###  What happens if there are connectivity issues with the Mesh global or zone control planes?

*Insert thing that is explicitly important to a Konnect user* For more information you can find a list of failure modes in the Mesh [failure modes](https://deploy-preview-6098--kongdocs.netlify.app/mesh/latest/production/deployment/multi-zone/#failure-modes) documentation.

2023-09-22 15:45 UTC, Guaris commented on app/konnect/org-management/deactivation.md
> +* The control plane (both the {{site.base_gateway}} and {{site.product_mesh_name}} global control planes) associated with the organization is decommissioned.
```suggestion
* The control plane (both the {{site.base_gateway}} and {{site.product_mesh_name}} global control planes) associated with the organization are decommissioned.
```

2023-09-22 15:45 UTC, Guaris commented on app/konnect/org-management/deactivation.md
> +* {{site.product_mesh_name}} local zone control planes and dataplanes (workloads) continue to run, but will not receive new updates to configuration.
```suggestion
* {{site.product_mesh_name}} local zone control planes and data plane nodes (workloads) continue to run, but will not receive new configuration updates.
```

2023-09-22 15:46 UTC, Guaris commented on app/konnect/mesh-manager/index.md
@johnharris85 I didn't see your comment earlier. Our policy is to establish the marketing pricing page as the single source of truth for this type of information.

2023-09-25 14:11 UTC, cloudjumpercat commented on app/konnect/mesh-manager/service-mesh.md
> +title: Configure a Mesh Global Control Plane and the Kubernetes demo app
```suggestion
title: Configure a Mesh Global Control Plane with the Kubernetes demo app
```

2023-09-25 15:10 UTC, Guaris approved these changes
I see the file gets a name change here
https://github.com/Kong/docs.konghq.com/pull/6134/files#diff-2a24c9876db3c9c7ac2e7789027572fe44a009324397c0a34bd59a50de92b6f9

Approved.

2023-09-25 16:42 UTC, lena-larionova approved these changes

2023-09-25 19:10 UTC, cloudjumpercat commented
Just a note: After talking with Angel, we decided it would be best to remove the doc from the getting started section and move it to the Mesh Manager section instead. In the current state, the getting started topic didn't fit the existing narrative in that section and we think Mesh Manager is more of an advanced use case (similar to KIC) that would be a better fit in the feature specific section.

2023-09-25 19:15 UTC, merged