feat: Mesh in Konnect changelog
Kong/docs.konghq.com pull request #6122
Opened 2023-09-18 21:22 UTC by cloudjumpercat

### Description

 MinK was missing a changelog, so I added one. 

DOCU-3479
### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-09-20 17:12 UTC, lena-larionova requested changes
You should use the [release note in Aha](https://konghq.aha.io/epics/KP-E-387) as the basis for the changelog entry (for example, you can take out things like the first sentence, which is clearly a marketing spin):

> Kong Konnect takes a major step forward, becoming the industry’s first unified API lifecycle management platform. Kong Mesh joins Kong Gateway and Kong Ingress Controller as the generally available runtime engines that are managed centrally by Kong Konnect’s management plane. Users can now identify mesh services, view relevant metadata (mesh, zone, etc.), and access the service's details in Mesh Manager through Konnect. This is the industry’s first unified API platform where all configuration management is in a single location with a clean and modern interface to manage services from Kong Gateway, Kong Ingress Controller, and Kong Mesh. 
>
> Konnect users can now navigate to a new Mesh Manager menu to create, modify, and delete mesh global control planes (MGCP). MGCP, as the name suggests, is a Control Plane mapped to different environments or business units. Each MGCP maps to a Kubernetes or Linux zone through a process that is similar to adding a Control Plane for gateway. The initial onboarding, management, and view will look similar in Mesh Manager to that of Gateway Manager.
>
> Organizations can lower their operational overhead and elevate their developers’ experience by streamlining the operation of Kong Gateways, Kong Ingress Controller and by simplifying the deployment of Kong Mesh with a hosted control plane that can be implemented across any cloud, virtual machines, or on-premises solution.

2023-09-22 13:52 UTC, cloudjumpercat commented on app/konnect/updates.md
> +**{{site.mesh_product_name}} in {{site.konnect_short_name}}**
```suggestion
**{{site.mesh_product_name}} in {{site.konnect_short_name}} (Enterprise and new Plus customers)**
```

2023-09-22 15:55 UTC, Guaris requested changes

2023-09-22 15:55 UTC, Guaris commented on app/konnect/updates.md
> +**{{site.mesh_product_name}} in {{site.konnect_short_name}} (Enterprise and new Plus customers)**
```suggestion
**{{site.mesh_product_name}} in {{site.konnect_short_name}}**
```

2023-09-22 15:55 UTC, Guaris commented on app/konnect/updates.md
> +**{{site.mesh_product_name}} in {{site.konnect_short_name}} (Enterprise and new Plus customers)**
I think this needs to be explicit and point to the pricing page. 
As in:
* Enterprise will be able to access mesh immediately and should contact their sales representative. 
* New customers can apply their trial credits towards mesh zones 
For more information view [pricing](pricing). 
Mesh is not available for existing plus customers, stay tuned for more information. 

I would clear this messaging with someone else but explicit is better than not.

2023-09-22 16:38 UTC, cloudjumpercat commented on app/konnect/updates.md
> +    Mesh Manager is not available for existing plus customers. Stay tuned for more information.
@johnharris85 Could you review the wording of this to make sure this is accurate/everything we want to say for the changelog?

2023-09-25 16:31 UTC, lena-larionova approved these changes

2023-09-25 18:19 UTC, Guaris approved these changes

2023-09-25 18:52 UTC, merged