feat: MinK zone consumption billing notes
Kong/docs.konghq.com pull request #6159
Opened 2023-09-22 16:08 UTC by cloudjumpercat

### Description

MinK zones will be billed based on consumption. We need to call this out in docs so that customers know when they will be billed for something and how much it will be.
 

DOCU-3418
### Testing instructions
Relates to https://github.com/Kong/docs.konghq.com/pull/6099. I chose to branch these changes off of the `mink-beta` branch since the changes needed to happen on the MinK docs. Let me know if you think I missed anything by doing this or if I should branch differently. I figured this is also okay since MinK billing will release at the same as MinK.

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-09-22 18:48 UTC, cloudjumpercat commented on app/konnect/getting-started/configure-mesh.md
> +> **Important:** Mesh zones are priced based on consumption. Your Konnect free trial provides enough credits for your first two zones. For more information about the pricing and consumption of additi
```suggestion
> **Important:** Mesh zones are priced based on consumption. For more information about the pricing and consumption of zones, see the [Pricing and Plans](/konnect/account-management/) documentation and Kong's [Pricing](https://konghq.com/pricing) page.
```

2023-09-25 14:28 UTC, Guaris requested changes

2023-09-25 14:28 UTC, Guaris commented on app/konnect/getting-started/configure-mesh.md
> +> **Important:** Mesh zones are priced based on consumption. For more information about the pricing and consumption of zones, see the [Pricing and Plans](/konnect/account-management/) documentation a
```suggestion
> **Important:** Mesh zones are priced based on consumption. For more information about the pricing and consumption of zones, see Kong's [Pricing](https://konghq.com/pricing) page.
```

2023-09-25 18:18 UTC, Guaris approved these changes

2023-09-25 18:53 UTC, merged