feat: kong gateway's aws vault backend now supports automatic IAM credential fetch and role assuming
Kong/docs.konghq.com pull request #6181
Opened 2023-09-27 06:52 UTC by windmgc

KAG-1542

This is a combination update of KAG-1991 and KAG-1993

### Description

 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-09-27 07:06 UTC, windmgc commented
Hmm, the smoke test seems to be broken for a long time(at least since the last time I raised a PR here)

is there anyway I can get a preview for this PR?

2023-09-27 10:00 UTC, hanshuebner requested changes
Just a couple of grammar changes, looks good to me otherwise.

2023-09-27 10:00 UTC, hanshuebner commented on app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
> +`vaults.config.assume_role_arn` | **Assume AWS IAM role ARN** | The target IAM role ARN that will be assumed to call AWS Secrets Manager service. If specified, Vault backend will do additional role a
```suggestion
`vaults.config.assume_role_arn` | **Assume AWS IAM role ARN** | The target IAM role ARN that will be assumed to call AWS Secrets Manager service. If specified, the Vault backend will do additional role assuming based on your current runtime's IAM Role. If you are not using assume role, do not specify this value.
```

2023-09-27 10:01 UTC, hanshuebner requested changes
Just a couple of grammar changes, looks good to me otherwise.

2023-09-27 12:06 UTC, windmgc commented
@hanshuebner Done! Thanks for the suggestions!

2023-09-27 22:50 UTC, zhongweiy approved these changes

2023-09-28 09:20 UTC, hanshuebner approved these changes

2023-10-25 20:15 UTC, merged

2023-10-25 20:16 UTC, Guaris reviewed
lgtm