Chore: Gateway Vale cleanup
Kong/docs.konghq.com pull request #6234
Opened 2023-10-04 16:55 UTC by lena-larionova

### Description

Ran Vale on `app/gateway` and `app/_src/gateway` and fixed everything that came up.

Also ran into a few spots where I missed standardizing the hostname, so fixed those as well.

Vale should pass on this PR.

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-10-04 16:56 UTC, lena-larionova commented
Note that I commented out the Developer Portal > Dev Portal rule and added rules for our existing variables instead. We can decide in the future if we should standardize on Dev Portal, but currently that rule only really applies to Konnect.

2023-10-05 08:02 UTC, fabianrbz commented on app/gateway/2.6.x/configure/auth/oidc-azuread.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 08:06 UTC, fabianrbz commented on app/gateway/2.6.x/configure/auth/oidc-azuread.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
totally unrelated to your changes, but It looks like this list is being rendered.
should it be a bullet list of links?

2023-10-05 08:07 UTC, fabianrbz commented on app/gateway/2.6.x/configure/auth/oidc-okta.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 08:25 UTC, fabianrbz commented on app/gateway/2.6.x/configure/graphql-quickstart.md
> +{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently e
```suggestion
{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently extends the features of your APIs. Some of the popular features deployed through {{site.base_gateway}} include authentication, security, traffic control, serverless, analytics & monitoring, request/response transformations, and logging. To learn more about these features, see the [Hub page](/hub/) for plugins. For more about the benefits of Kong in general, please see the [FAQ](https://konghq.com/faqs).
```

2023-10-05 08:31 UTC, fabianrbz commented on app/gateway/2.6.x/pdk/kong.ip.md
> + See [docs.konghq.com/latest/configuration/#trusted_ips](latest/configuration/#trusted_ips)
```suggestion
 See [docs.konghq.com/latest/configuration/#trusted_ips](/latest/configuration/#trusted_ips)
```

2023-10-05 08:32 UTC, fabianrbz commented on app/gateway/2.6.x/plan-and-deploy/dns-considerations.md
> +[oidc-plugin]: hub/kong-inc/openid-connect/
```suggestion
[oidc-plugin]: /hub/kong-inc/openid-connect/
```

2023-10-05 08:33 UTC, fabianrbz commented on app/gateway/2.6.x/plan-and-deploy/dns-considerations.md
> +[session-plugin]: hub/kong-inc/session/
```suggestion
[session-plugin]: /hub/kong-inc/session/
```

2023-10-05 08:36 UTC, fabianrbz commented on app/gateway/2.6.x/reference/external-plugins.md
> +[kong-pdk]: latest/plugin-development/
```suggestion
[kong-pdk]: /latest/plugin-development/
```

2023-10-05 08:39 UTC, fabianrbz commented on app/gateway/2.6.x/vitals/index.md
> +* PostgreSQLSQL 9.5+
```suggestion
* PostgreSQL 9.5+
```

2023-10-05 08:54 UTC, fabianrbz commented on app/gateway/2.7.x/configure/auth/oidc-azuread.md
> -[credential-claim]: https://docs.konghq.com/hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 08:54 UTC, fabianrbz commented on app/gateway/2.7.x/configure/auth/oidc-okta.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 08:55 UTC, fabianrbz commented on app/gateway/2.7.x/configure/graphql-quickstart.md
> +{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently e
```suggestion
{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently extends the features of your APIs. Some of the popular features deployed through {{site.base_gateway}} include authentication, security, traffic control, serverless, analytics & monitoring, request/response transformations, and logging. To learn more about these features, see the [Hub page](/hub/) for plugins. For more about the benefits of Kong in general, please see the [FAQ](https://konghq.com/faqs).
```

2023-10-05 09:01 UTC, fabianrbz commented on app/gateway/2.7.x/install-and-run/upgrade-oss.md
> +For more information, see [Developing Go plugins](gateway/2.6.x/reference/external-plugins/#developing-go-plugins).
```suggestion
For more information, see [Developing Go plugins](/gateway/2.6.x/reference/external-plugins/#developing-go-plugins).
```

2023-10-05 09:02 UTC, fabianrbz commented on app/gateway/2.7.x/install-and-run/upgrade-oss.md
> +[reload](gateway/2.7.x/reference/cli/#kong-reload) Kong:
```suggestion
[reload](/gateway/2.7.x/reference/cli/#kong-reload) Kong:
```

2023-10-05 09:03 UTC, fabianrbz commented on app/gateway/2.7.x/pdk/kong.ip.md
> + See [docs.konghq.com/latest/configuration/#trusted_ips](latest/configuration/#trusted_ips)
```suggestion
 See [docs.konghq.com/latest/configuration/#trusted_ips](/latest/configuration/#trusted_ips)
```

2023-10-05 09:05 UTC, fabianrbz commented on app/gateway/2.7.x/plan-and-deploy/dns-considerations.md
> +[oidc-plugin]: hub/kong-inc/openid-connect/
```suggestion
[oidc-plugin]: /hub/kong-inc/openid-connect/
```

2023-10-05 09:06 UTC, fabianrbz commented on app/gateway/2.7.x/plan-and-deploy/dns-considerations.md
> +[session-plugin]: hub/kong-inc/session/
```suggestion
[session-plugin]: /hub/kong-inc/session/
```

2023-10-05 09:11 UTC, fabianrbz commented on app/gateway/2.7.x/reference/external-plugins.md
> +[kong-pdk]: latest/plugin-development/
```suggestion
[kong-pdk]: /latest/plugin-development/
```

2023-10-05 09:13 UTC, fabianrbz commented on app/gateway/2.7.x/vitals/index.md
> +* PostgreSQLSQL 9.5+
```suggestion
* PostgreSQL 9.5+
```

2023-10-05 09:16 UTC, fabianrbz commented on app/gateway/2.8.x/configure/auth/oidc-azuread.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 09:17 UTC, fabianrbz commented on app/gateway/2.8.x/configure/auth/oidc-okta.md
> +[credential-claim]: hub/kong-inc/openid-connect/#configcredential_claim
```suggestion
[credential-claim]: /hub/kong-inc/openid-connect/#configcredential_claim
```

2023-10-05 09:18 UTC, fabianrbz commented on app/gateway/2.8.x/configure/graphql-quickstart.md
> +{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently e
```suggestion
{{site.base_gateway}} is an API gateway and platform. That means it is a form of middleware between computing clients and your API-based applications. {{site.base_gateway}} quickly and consistently extends the features of your APIs. Some of the popular features deployed through {{site.base_gateway}} include authentication, security, traffic control, serverless, analytics & monitoring, request/response transformations, and logging. To learn more about these features, see the [Hub page](/hub/) for plugins. For more about the benefits of Kong in general, please see the [FAQ](https://konghq.com/faqs).
```

2023-10-05 09:24 UTC, fabianrbz commented on app/gateway/2.8.x/install-and-run/helm-quickstart-enterprise.md
> +You can configure Kong via the Admin API with [decK](deck/latest/), [Insomnia](https://docs.insomnia.rest/insomnia/get-started), HTTPie, or cURL, at `https://kong.127-0-0-1.nip.io/api`:
```suggestion
You can configure Kong via the Admin API with [decK](/deck/latest/), [Insomnia](https://docs.insomnia.rest/insomnia/get-started), HTTPie, or cURL, at `https://kong.127-0-0-1.nip.io/api`:
```

2023-10-05 09:27 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.client.md
> + * [real\_ip\_header](gateway/latest/reference/configuration/#real_ip_header)
```suggestion
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
```

2023-10-05 09:28 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.client.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 09:29 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.client.md
> + * [trusted\_ips](gateway/latest/reference/configuration/#trusted_ips)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
```

2023-10-05 09:29 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.client.md
> + * [real\_ip\_header](gateway/latest/reference/configuration/#real_ip_header)
```suggestion
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
```

2023-10-05 09:30 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.client.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 09:32 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.ip.md
> + See the [documentation on trusted IPs](gateway/latest/reference/configuration/#trusted_ips).
```suggestion
 See the [documentation on trusted IPs](/gateway/latest/reference/configuration/#trusted_ips).
```

2023-10-05 09:35 UTC, fabianrbz commented on app/gateway/2.8.x/plan-and-deploy/dns-considerations.md
> +[oidc-plugin]: hub/kong-inc/openid-connect/
```suggestion
[oidc-plugin]: /hub/kong-inc/openid-connect/
```

2023-10-05 09:36 UTC, fabianrbz commented on app/gateway/2.8.x/plan-and-deploy/dns-considerations.md
> +[session-plugin]: hub/kong-inc/session/
```suggestion
[session-plugin]: /hub/kong-inc/session/
```

2023-10-05 09:41 UTC, fabianrbz commented on app/gateway/2.8.x/vitals/index.md
> +  * PostgreSQLSQL 9.5+
```suggestion
  * PostgreSQL 9.5+
```

2023-10-05 09:49 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 10:14 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 10:15 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [port\_maps](gateway/latest/reference/configuration/#port_maps)
```suggestion
 * [port\_maps](/gateway/latest/reference/configuration/#port_maps)
```

2023-10-05 10:16 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 10:18 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 10:19 UTC, fabianrbz commented on app/gateway/2.8.x/pdk/kong.request.md
> + * [real\_ip\_recursive](gateway/latest/reference/configuration/#real_ip_recursive)
```suggestion
 * [trusted\_ips](/gateway/latest/reference/configuration/#trusted_ips)
 * [real\_ip\_header](/gateway/latest/reference/configuration/#real_ip_header)
 * [real\_ip\_recursive](/gateway/latest/reference/configuration/#real_ip_recursive)
```

2023-10-05 10:23 UTC, fabianrbz requested changes
❤️ ❤️ ❤️ ❤️ Thanks!
I left a few comments and suggestions, but otherwise, it looks great! 🎉

2023-10-05 18:06 UTC, lena-larionova commented
Sorry for the mess of search & replace typos - two typos, but such far reach 😓

2023-10-05 20:05 UTC, lena-larionova commented
Fixed all the real broken links.

2023-10-06 07:39 UTC, fabianrbz approved these changes
LGTM 🎉

2023-10-06 14:27 UTC, merged