Add Overlays for tag description [skip-ci]
Kong/docs.konghq.com pull request #6271
Opened 2023-10-10 16:33 UTC by Guaris

I added support for overlays for the tag descriptions since those will not be generated through any form of automation.

2023-10-12 20:13 UTC, lena-larionova requested changes

2023-10-12 20:13 UTC, lena-larionova commented on api-specs/overlays/docs/docs.md
> +
```suggestion

1. Clone [this](https://github.com/lornajane/openapi-overlays-js) repo, `cd` into the directory where you cloned it. 
2. Run `npm install` to get the dependencies
3. Run `npm install -g` to get `overlayjs` as a command

```

2023-10-12 20:13 UTC, lena-larionova commented on api-specs/overlays/docs/docs.md
> +To apply an overlay to a spec use the following command:
```suggestion
To apply an overlay to a spec, run the following command from your clone of the docs directory: 
```
Or something like "cd into your clone of the docs directory, then run the command:"

2023-10-12 20:13 UTC, lena-larionova commented on api-specs/overlays/docs/docs.md
> +`overlayjs --openapi openapi.yml --overlay overlay.yaml`
What's the purpose of showing how to output to the console? Won't we always be piping this output to a file?

2023-10-12 20:13 UTC, lena-larionova commented on api-specs/overlays/oss/api-description.yaml
> +      OpenAPI 3.0 spec for Kong Gateway's Enterprise Admin API.
```suggestion
      OpenAPI 3.0 spec for Kong Gateway's Open Source Admin API.
```

2023-10-17 19:45 UTC, lena-larionova approved these changes

2023-10-18 08:19 UTC, fabianrbz commented
@Guaris let me know when you are planning to merge this, we need to prevent Jekyll from generating pages for the overlays

2023-10-18 14:59 UTC, merged