Feat: Portal Management API
Kong/docs.konghq.com pull request #6388
Opened 2023-10-27 16:20 UTC by acgoldsmith

### Description

Customers are able to integrate portal management operations with their automation systems (such as CI/CD pipelines) by utilizing a refactored and newly-published AIP-compliant Portal Management API.

### Testing instructions

Preview link: 
*  new spec URL /api/portal-managment/latest
* 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-10-27 18:23 UTC, cloudjumpercat requested changes
@acgoldsmith Just had one small comments about indentation, everything else looks good!

2023-10-27 18:23 UTC, cloudjumpercat commented on app/_data/docs_nav_konnect.yml
> +        target_blank: true
These rows need another indent

2023-10-27 19:09 UTC, cloudjumpercat approved these changes
LGTM!

2023-10-27 19:14 UTC, acgoldsmith commented
@c3pko , this is ready to release. Please ensure the API product and spec are published from devportal: https://cloud.konghq.com/us/api-products/f99f0f29-be4e-4fc8-8cec-64e5d3511bff/versions/43fca68c-f83d-4cf1-8c40-87574d423313

2023-10-30 21:52 UTC, acgoldsmith commented
note to self: in order to trigger the sync from /portal-api/ repo to populate the insomnia button, please merge https://github.com/Kong/docs.konghq.com/pull/6359 first

2023-10-31 17:38 UTC, acgoldsmith commented
@rosskukulinski , I've added the insomnia button as well and confirmed it's working. API Product and version at https://cloud.konghq.com/us/api-products/f99f0f29-be4e-4fc8-8cec-64e5d3511bff/versions/43fca68c-f83d-4cf1-8c40-87574d423313 need to be published ahead of this pr.

2023-11-02 22:54 UTC, merged