Add reference page for required permissions to install KIC
Kong/docs.konghq.com pull request #6524
Opened 2023-11-16 09:32 UTC by randmonkey

### Description

Add a reference page to list the permissions required to install KIC when user do not have the super admin permission.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5166. 
 

### Testing instructions

Preview link: 
https://deploy-preview-6524--kongdocs.netlify.app/kubernetes-ingress-controller/latest/reference/required-permissions/
### Checklist 

- [x] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-11-17 10:19 UTC, tao12345666333 commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +To install {{ site.kic_product_name }}, you need to have the perssion to WRITE (create, update, get, list, watch in Kubernetes's RBAC model) the following resources:
```suggestion
To install {{ site.kic_product_name }}, you need to have the permission to WRITE (create, update, get, list, watch in Kubernetes's RBAC model) the following resources:
```

2023-11-20 09:01 UTC, randmonkey commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +For creating RBAC rules to enable {{ site.kic_product_name }} to access requried resources, you need to have the permissions to create or update `ClusterRole`, `ClusterRoleBinding` in the cluster sco
done.

2023-11-20 09:01 UTC, randmonkey commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +To install {{ site.kic_product_name }}, you need to have the perssion to WRITE (create, update, get, list, watch in Kubernetes's RBAC model) the following resources:
done.

2023-11-20 09:29 UTC, randmonkey commented
I added `if ${{ failure() }}` condition, but logs are still uploaded. hold this.

2023-11-21 04:42 UTC, Rajakavitha1 approved these changes
LGTM

2023-11-21 04:42 UTC, Rajakavitha1 commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +To install {{ site.kic_product_name }}, you need to have the permissions to WRITE (create, update, get, list, watch in Kubernetes's RBAC model) the following resources:
```suggestion
To install {{ site.kic_product_name }}, you need to have the permissions to WRITE (create, update, get, list, watch in Kubernetes's RBAC model) these resources.
```

2023-11-30 19:56 UTC, lena-larionova requested changes

2023-11-30 19:56 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +title: Required Permissions to Use {{ site.kic_product_name }}
```suggestion
title: Required permissions to use Kong Ingress Controller
```
variables don't work right in front matter, unfortunately:
<img width="719" alt="Screenshot 2023-11-30 at 11 49 04 AM" src="https://github.com/Kong/docs.konghq.com/assets/54370747/66272246-489c-44ee-a1d4-ba1d3f1ea29d">

2023-11-30 19:56 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +  What permissions are required to install {{ site.kic_product_name }} if I am not a super admin of the cluster? What permissions are required to run {{ site.kic_product_name }}?
```suggestion
  What permissions are required to install Kong Ingress Controller if I am not a super admin of the cluster? What permissions are required to run Kong Ingress Controller?
```

2023-11-30 19:56 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/reference/required-permissions.md
> +For creating resources required for {{ site.kic_product_name }}, you need to have the permissions to create or update `Deployment`, `Service`, `ServiceAccount`, `Secret` or `ConfigMap` to create depl
```suggestion
* For creating resources required for {{ site.kic_product_name }}, you need to have the permissions to create or update `Deployment`, `Service`, `ServiceAccount`, `Secret`,  or `ConfigMap` to create deployments, services, and to specify their configurations. 

* If you run {{ site.kic_product_name }} with database-backed {{site.base_gateway}}, you also need to have the permissions to create or update `PersistentVolumeClaim` to set volumes used for the database, and `Job` to run migration jobs. 

* If you want to enable auto scaling, you also need permissions to create or update `HorizontalPodAutoscaler`.
```

2023-11-30 20:36 UTC, lena-larionova approved these changes

2023-11-30 20:36 UTC, merged