fix: add the missing part of kong gateway vault's secrets versioning description
Kong/docs.konghq.com pull request #6551
Opened 2023-11-23 07:15 UTC by windmgc

### Description

The PR adds the missing part of Kong Gateway Vault's secrets versioning description.

Gateway's vault supports accessing versioning secrets by specifying version number as a fragment in the vault reference URL.

Note that this is not a new feature added recently, it exists long time ago, only the doc part is missing.

https://konghq.atlassian.net/browse/FTI-5168

 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-11-27 23:16 UTC, lena-larionova requested changes

2023-11-27 23:16 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
> +# For AWSCURRENT, specifying version == 2
Should this be "AWSPREVIOUS"?

2023-11-27 23:16 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
> +Moreover, for an AWS Secrets Manager secret that has multiple versions, accessing the current version(labeled as `AWSCURRENT`) of the secret or the previous version(labeled as`AWSPREVIOUS`) of the se
```suggestion
If you have an AWS Secrets Manager secret with multiple versions, you can access the current version or any previous version of the secret by specifying a version in the reference. 

In the following example, `AWSCURRENT` refers to the latest secret version and `AWSPREVIOUS` refers to an older version:
```

2023-11-27 23:16 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
> +If you've configured a secret value in multiple versions, like this:
```suggestion
If you have configured a secret value in multiple versions:
```

2023-11-27 23:16 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
> +Access an older version of the secret will be like this:
```suggestion
Access an older version of the secret like this:
```

2023-11-27 23:16 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/secrets-management/reference-format.md
> +Version, which is the fragment part of the Vault URL, is used to identify the version number of the secret stored in the vault backends which supports versioning.
```suggestion
The version, specified as the fragment of the Vault URL, identifies the version number of the secret stored in a vault backend. Applies to any vault backend that supports versioning.
```

2023-11-28 08:34 UTC, windmgc commented on app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
> +# For AWSCURRENT, specifying version == 2
Nice catch!!

2023-11-28 08:42 UTC, windmgc commented on app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
> +# For AWSCURRENT, specifying version == 2
Fixed!

2023-11-30 17:20 UTC, lena-larionova approved these changes
LGTM! Thanks for the fix :)

2023-11-30 17:21 UTC, merged