fix: Deprecate markdown API docs
Kong/docs.konghq.com pull request #6628
Opened 2023-12-07 20:34 UTC by Guaris

Removes markdown API documentation from the 3.5 nav bar. 
Adds redirects for markdown documentation pointing to API spec
Changes links in documentation to point towards API documentation.

2024-01-05 19:05 UTC, lena-larionova requested changes

2024-01-05 19:05 UTC, lena-larionova commented on app/_redirects
> +/gateway/latest/admin-api/admins/reference/   /gateway/api/admine-ee/latest/#/admins/get-admins/
```suggestion
/gateway/latest/admin-api/audit-logs/        /gateway/api/admin-ee/latest/#/audit-logs/get-audit-requests/
/gateway/latest/admin-api/admins/reference/   /gateway/api/admin-ee/latest/#/admins/get-admins/
```

2024-01-05 19:05 UTC, lena-larionova commented on app/_redirects
> +# API deprecation
```suggestion
# API markdown doc deprecation
```
just in case anyone is looking at this file later and gets worried about a deprecated API.

2024-01-05 19:11 UTC, lena-larionova commented on app/_redirects
> +/gateway/latest/admin-api/#information-routes   /gateway/api/admin-ee/latest/#/Information/get-endpoints/
/gateway/latest/admin-api/ /gateway/api/admin-ee/latest/#/

2024-01-11 21:41 UTC, Guaris commented on app/_redirects
> +/gateway/latest/admin-api/#information-routes   /gateway/api/admin-ee/latest/#/Information/get-endpoints/
```suggestion
/gateway/latest/admin-api/ /gateway/api/admin-ee/latest/#/
```

2024-01-12 21:56 UTC, Guaris commented
@lena-larionova 
Now featuring this table 
![image](https://github.com/Kong/docs.konghq.com/assets/23319190/bd59c909-8073-4fe0-a504-740fec379a0d)

And I pulled a section out to create 
/gateway/latest/admin-api/declarative-configuration/

2024-01-25 17:55 UTC, Guaris commented
Closing in favor of 
https://github.com/Kong/docs.konghq.com/pull/6836

2024-01-25 17:55 UTC, closed without merging