feat: Create Benchmark Guide for Kong Gateway
Kong/docs.konghq.com pull request #6630
Opened 2023-12-07 22:06 UTC by cloudjumpercat

### Description

Harry created an internal KB about benchmark testing for Kong Gateway as well as some recommendations to improve benchmark performance, so this PR converts that into documentation.
 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2023-12-21 15:50 UTC, cloudjumpercat commented on app/_src/gateway/production/benchmark.md
> +<!--are we missing the third config variation?-->
Asked Harry these questions on the Confluence page.

2023-12-22 15:59 UTC, cloudjumpercat commented on app/_src/gateway/production/benchmark.md
> +<!--are we missing the third config variation?-->
```suggestion
1. Measure {{site.base_gateway}}’s performance without enabling any plugins. This provides a baseline for {{site.base_gateway}}’s performance.
1. Enable necessary bundled plugins (plugins that come with the product), and then measure {{site.base_gateway}}’s performance.
1. Next, enable custom plugins (in addition to bundled plugins), and then measure {{site.base_gateway}}’s performance once again.
```

2023-12-22 16:00 UTC, cloudjumpercat commented on app/_src/gateway/production/benchmark.md
> +Sometimes, measuring {{site.base_gateway}}'s baseline performance without any plugins enabled can help you find issues outside {{site.base_gateway}}.
```suggestion
If {{site.base_gateway}}’s baseline performance is poor, then it's likely that either {{site.base_gateway}}’s configuration needs tuning or external factors are affecting it. For external factors, see the other sections in this guide.
A large difference between the performance in the second and and third steps indicates that performance problems could be due to custom plugins.
```

2023-12-22 16:02 UTC, cloudjumpercat commented
Hi @hbagdi ! Thanks for writing up the Confluence page on benchmarking Kong! I turned it into documentation for our docs site. If you wouldn't mind looking everything over just to double check that everything sounds good, that would be great! Thanks!

2023-12-22 16:03 UTC, cloudjumpercat commented on app/_src/gateway/production/benchmark.md
> +A large difference between the performance in the second and and third steps indicates that performance problems could be due to custom plugins.
```suggestion
A large difference between the performance in the second and third steps indicates that performance problems could be due to custom plugins.
```

2024-01-04 21:45 UTC, lena-larionova requested changes

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +  If you run {{site.base_gateway}} pods on Kubernetes worker nodes with n CPUs, allocate n-2 or n-1 to {{site.base_gateway}}, and configure a worker process count equal to this number. This ensures t
```suggestion
  
  If you run {{site.base_gateway}} pods on Kubernetes worker nodes with n CPUs, allocate n-2 or n-1 to {{site.base_gateway}}, and configure a worker process count equal to this number. This ensures that any configured daemons and Kubernetes processes, like kubelet, don't contend for resources with {{site.base_gateway}}.  
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +  Each additional worker uses additional memory, so you must ensure that {{site.base_gateway}} isn't triggering the Linux Out-of-Memory Killer.
```suggestion
  
  Each additional worker uses additional memory, so you must ensure that {{site.base_gateway}} isn't triggering the Linux Out-of-Memory Killer.
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +* Ensure that the client (like Apache JMeter or k6), {{site.base_gateway}}, and the upstream servers run on different machines (VM or bare-metal). If these are all running in a Kubernetes cluster, en
```suggestion
* Ensure that the client (like Apache JMeter or k6), {{site.base_gateway}}, and the upstream servers run on different machines (VM or bare-metal). If these are all running in a Kubernetes cluster, ensure that the pods for these three systems are scheduled on dedicated nodes. Resource contention (usually CPU and network) between these can lead to suboptimal performance of any system. 
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +You must also ensure that upstream servers are not autoscaled.
```suggestion

You must also ensure that upstream servers are not autoscaled.
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +The client must also use keep-alive connections. For example, [k6](https://k6.io/docs/using-k6/k6-options/reference/#no-connection-reuse) enables keep-alive by default, and [HTTPClient4](https://hc.a
```suggestion

The client must also use keep-alive connections. For example, [k6](https://k6.io/docs/using-k6/k6-options/reference/#no-connection-reuse) and the [HTTPClient4](https://hc.apache.org/httpcomponents-client-4.5.x/index.html) implementation in Apache JMeter both enable keep-alive by default. 
Verify that this is set up appropriately for your test setup.
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +**Action:** Keep request bodies below eight KB and response bodies below 32 KB.
```suggestion
**Action:** Keep request bodies below 8 KB and response bodies below 32 KB.
```
I know we usually spell out a number when it's ten or lower, but I think we should revisit this and set some guidelines on when to use what. When it's a measurement (like KB in this instance), it makes more sense to use the numeral. Additionally, consistency/parallelism is important for clarity, and it's awkward to read "eight KB and 32 KB". 

Interestingly, the [Google style guide](https://developers.google.com/style/numbers#numbers-as-numerals) lists a fair number of exceptions here, including units, and the Mailchimp style guide tells writers to [use the numeral in most situations](https://styleguide.mailchimp.com/grammar-and-mechanics/#header-3-numbers).

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +Most benchmarking setups generally consist of an HTTP request with a small HTTP body and a corresponding HTTP response with a JSON or HTML response body. A request body of less than eight KB and a re
```suggestion
Most benchmarking setups generally consist of an HTTP request with a small HTTP body and a corresponding HTTP response with a JSON or HTML response body. 
A request body of less than 8 KB and a response body of less than 32 KB is considered small. If your request or response bodies are larger, {{site.base_gateway}} will buffer the request and response using the disk, which significantly impacts {{site.base_gateway}}'s performance.
```

2024-01-04 21:45 UTC, lena-larionova commented on app/_src/gateway/production/benchmark.md
> +```
Let's move these into tabs instead of headings: kong.conf, environment variables, and Helm chart values

2024-01-05 18:47 UTC, lena-larionova approved these changes

2024-01-05 19:09 UTC, merged