Feat: Added Konnect examples for Auth plugins related to Consumers
Kong/docs.konghq.com pull request #6742
Opened 2024-01-10 23:33 UTC by d19dotca

### Description

A customer of Kong Konnect discovered that we were missing data in our documentation on the API calls in Konnect to make for adding credentials to consumers.

Added example API calls to the documentation for plugins including HMAC, JWT, Basic Auth, Key Auth, and ACL.

I believe these will eventually be added elsewhere as part of the ongoing work in the API spec documents for Konnect, but as a stop-gap I am hoping it can exist in the individual plugin documentation for now.

Related: [Slack thread](https://kongstrong.slack.com/archives/C03NRECFJPM/p1704731546097239)

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2024-01-16 16:08 UTC, Guaris requested changes

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/acl/how-to/_index.md
> +curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER}/acls \
```suggestion
curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER_ID}/acls \
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/acl/how-to/_index.md
> +`CONSUMER`: The `username` property of the consumer entity to associate the credentials with.
```suggestion
`CONSUMER_ID`: The UUID of the consumer entity to associate the credentials with.
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/hmac-auth/overview/_index.md
> +You can provision new username/password credentials by making the following
```suggestion
You can provision new username and password credentials by making the following
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/jwt/overview/_index.md
> +curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER}/jwt -H "Content-Type: application/x-www-form-urlencoded" \
```suggestion
curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER_ID}/jwt -H "Content-Type: application/x-www-form-urlencoded" \
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/acl/how-to/_index.md
> +associate a group to a consumer using the following request:
```suggestion
After you have added an authentication plugin to a service or a route, and you have
created the [consumers object](/gateway/latest/admin-api/#consumer-object), you can now
associate a group to a consumer using the following request:
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/basic-auth/overview/_index.md
> +curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER}/basic-auth \
```suggestion
curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER_ID}/basic-auth \
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/hmac-auth/overview/_index.md
> +curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER}/hmac-auth \
```suggestion
curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER_ID}/hmac-auth \
```

2024-01-16 16:08 UTC, Guaris commented on app/_hub/kong-inc/key-auth/overview/_index.md
> +curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER}/key-auth
```suggestion
curl -X POST https://{us|eu}.api.konghq.com/v2/control-planes/{controlPlaneId}/core-entities/consumers/{CONSUMER_ID}/key-auth
```

2024-01-16 16:09 UTC, Guaris commented
@d19dotca Some changes to the URL's to explicitly state they require the UUID of the consumer in the Konnect API.

2024-01-16 19:03 UTC, d19dotca commented
Thanks @Guaris - I committed the suggested changes now. 👍

2024-01-16 21:37 UTC, Guaris approved these changes

2024-01-16 21:37 UTC, Guaris commented
I'll test this tomorrow morning and merge it!

2024-01-16 22:03 UTC, lena-larionova reviewed
@Guaris @d19dotca 
I think @mheap may have published a similar change already: https://github.com/Kong/docs.konghq.com/pull/6758

Does that satisfy the request, or is this PR still neccessary?

2024-01-23 21:26 UTC, cloudjumpercat commented
@lena-larionova @Guaris After looking at the content added in this PR and what was added in #6758, it looks like they cover most of the same information (Michael's PR doesn't include ACL though, it only includes auth plugins, and this PR does). However, because in the original plugin docs, sometimes consumers are talked about in both overview and the basic config examples pages, this PR updates the overview pages and Michael's updates the basic config pages. I think before we merge this PR we should:
* Remove any duplicate consumer content from the overview and maybe instead link to the basic config example page in it's place so the information is only in one place. 
* Make sure we reuse Michael's basic config examples consumer content in the ACL plugin page.

2024-01-23 22:25 UTC, Guaris commented
@d19dotca @cloudjumpercat Dustin, based on Diana's feedback would these changes still solve the initial customer concerns?

2024-01-29 17:56 UTC, d19dotca commented
Sorry for the late reply @Guaris, @cloudjumpercat, and @lena-larionova. 

I updated the data based on where they were at the time, but perhaps this is also a good opportunity to follow what I think Michael was trying to which is move these all from the Overview page to their own config example page for managing consumers and credentials for the plugin. 

It sounds like mine may contain more data (at least since ACL was also added in my PR), so perhaps it makes sense to just validate that Michael and I came to the same examples (and correct if any mismatches) but also move them to their own page in the Config Examples area at the same time as it sounds like Michael was doing? I'm not sure the best way forward since it sounds like we unfortunately duplicated efforts on that, not sure which path is the best path forward in this case.

2024-01-29 17:57 UTC, d19dotca commented
Actually if we're going to move to the Config Examples pages from Overview, then maybe it's easier to use Michael's PR and we can just update to also include ACL?

2024-02-01 21:31 UTC, d19dotca commented
Okay yeah I think this can be closed, and then Michael's can be approved and merged, and I'll add in afterwards the ACL one to that.

2024-02-01 21:31 UTC, closed without merging