Bootstrap 3.6 docs
Kong/docs.konghq.com pull request #6744
Opened 2024-01-11 09:15 UTC by StarlightIbuki

### Description

https://github.com/Kong/kong-ee/pull/7627

KAG-2949

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2024-01-16 18:47 UTC, lena-larionova requested changes

2024-01-17 02:45 UTC, StarlightIbuki commented on app/_src/gateway/kong-enterprise/cp-outage-handling.md
> +We do not recommend using backup nodes to proxy traffic though it's possible. The backup job enlarges the attack surface of a proxying DP, and contribute significantly to the P99 delay. You need to k
The risk also applies to versions before 3.5. Not sure if we should change the wording for older versions.

2024-01-17 02:48 UTC, StarlightIbuki commented on app/_src/gateway/kong-enterprise/cp-outage-handling.md
> +All the object keynames/prefixes mentioned in the following paragraphs are parametized with the prefix given in the config and the gateway version. Let's say the node has a version of `3.6.0.0`,
I've rephrased the paragraph and some of the sentences are moved below.

2024-01-17 02:58 UTC, StarlightIbuki commented on app/_src/gateway/kong-enterprise/cp-outage-handling.md
>  A backup node should not be used to proxy traffic. A single backup node is sufficient for all deployments. For more information about the data that is set in the environment variables, review the [AW
```suggestion
{:.important}
> We do not recommend using backup nodes to proxy traffic. The backup job enlarges the attack surface of a proxying DP and contributes significantly to the P99 delay. You need to know the risk if you want to deploy a node this way, and a DP acting as a backup node cannot be provisioned with backup configurations.
```

2024-01-17 22:13 UTC, lena-larionova commented on app/_src/gateway/kong-enterprise/cp-outage-handling.md
> +All the object keynames/prefixes mentioned in the following paragraphs are parametized with the prefix given in the config and the gateway version. Let's say the node has a version of `3.6.0.0`,
```suggestion
{% if_version lte:3.5.x %}
This node is responsible for writing to the S3 bucket when it receives new configuration. The file structure is automatically created inside of the bucket and should not be created manually. If the node version is `3.2.0.0`, using the example above, the key name will be `test-prefix/3.2.0.0/config.json`. 
{% endif_version %}

{% if_version gte:3.6.x %}
All the object keynames/prefixes mentioned in the following paragraphs are parameterized with the prefix given in the config and the gateway version. For example, let's say the node has a version of `3.6.0.0`.
```

2024-01-17 22:25 UTC, lena-larionova approved these changes
LGTM

2024-01-17 22:27 UTC, merged