docs(router): support net.src.* and net.dst.* in http route expression
Kong/docs.konghq.com pull request #6756
Opened 2024-01-15 06:06 UTC by chronolaw

### Description

In PR https://github.com/Kong/kong/pull/11950, we add support for `net.src.*` and `net.dst.*` in http route exepression.

It will be released in Kong gateway 3.6.0.
 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

2024-01-16 16:26 UTC, Guaris requested changes
Small changes

2024-01-16 16:26 UTC, Guaris commented on app/_src/gateway/key-concepts/routes/expressions.md
> +| `net.dst.ip`                          | `IpAddr`   | ✅                           | ✅                             | Listening IP address where {{site.base_gateway}} accepted the incoming connection.
```suggestion
| `net.dst.ip`                          | `IpAddr`   | ✅                           | ✅                             | Listening IP address where {{site.base_gateway}} accepts the incoming connection.                                                                                                                                                                                                                                                      |
```

2024-01-16 16:26 UTC, Guaris commented on app/_src/gateway/key-concepts/routes/expressions.md
> +| `net.dst.port`                        | `Int`      | ✅                           | ✅                             | Listening port number where {{site.base_gateway}} accepted the incoming connection
```suggestion
| `net.dst.port`                        | `Int`      | ✅                           | ✅                             | Listening port number where {{site.base_gateway}} accepts the incoming connection.                                                                                                                                                                                                                                                     |
```

2024-01-16 16:29 UTC, Guaris commented
@chronolaw Can you point this at `release/gateway-3.6` please

2024-01-16 21:16 UTC, Guaris commented
The conditional formatting I added may not render correctly until the branch is rebased over `release/gateway-3.6`

2024-01-17 02:38 UTC, chronolaw commented
I will create a new one since it changes too many files.

2024-01-17 02:55 UTC, chronolaw commented
replaced by #6765.

2024-01-17 02:55 UTC, closed without merging