Feat: Deprecate markdown API documentation
Kong/docs.konghq.com pull request #6836
Opened 2024-01-25 17:55 UTC by Guaris

Removes markdown API documentation from the 3.5 nav bar.
Adds redirects for markdown documentation pointing to API spec
Changes links in documentation to point to API documentation.

Re: https://github.com/Kong/docs.konghq.com/pull/6628

2024-01-26 20:31 UTC, acgoldsmith commented
@Guaris , can I suggest we utilize the same behavior as we do for linking to the specs from the Konnect nav, so they open in a new tab? 

```
        - text: API Spec
          url: /konnect/api/portal-management/latest/
          absolute_url: true
          generate: false
          target_blank: true
```

2024-01-31 17:52 UTC, Guaris commented on app/_data/docs_nav_gateway_3.5.x.yml
> +      - text: Declarative Configuration
```suggestion
        url: /admin-api/index_latest/
        src: /admin-api/index
      - text: Declarative Configuration
```

2024-01-31 18:09 UTC, lena-larionova commented on app/_data/docs_nav_gateway_3.5.x.yml
> +        src: /admin-api/index
```suggestion
        url: /admin-api/
        src: /gateway/admin-api/index_latest
```

2024-01-31 23:19 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +|        |   Endpoints        | |
```suggestion
| Endpoints | | |
```
Moving the label to the first column. In context with the specs table above it, it looks odd to have the text centered:
![Screenshot 2024-01-31 at 3 19 18 PM](https://github.com/Kong/docs.konghq.com/assets/54370747/e2652b32-c116-478a-b463-d1b971ff60a9)

Vs aligned to the left on both:
![Screenshot 2024-01-31 at 3 19 11 PM](https://github.com/Kong/docs.konghq.com/assets/54370747/4cdbf71a-9ba4-45f9-a454-3c5ac8244e35)

2024-01-31 23:23 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> + of methods to secure the Admin API.
```suggestion
 exposure of this API. See [Securing the Admin API](/gateway/{{page.release}}/production/running-kong/secure-admin-api/)
 for more information about security methods.
```

2024-01-31 23:32 UTC, lena-larionova requested changes
Minor formatting edits, might as well get them out of the way.

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +### Documentation
```suggestion
## Documentation
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +### DB-less Mode
```suggestion
## DB-less mode
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +In [DB-less mode](/gateway/{{page.kong_version}}/production/deployment-topologies/db-less-and-declarative-config/),
```suggestion
In [DB-less mode](/gateway/{{page.release}}/production/deployment-topologies/db-less-and-declarative-config/),
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +
```suggestion
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +### Supported Content Types
```suggestion
## Supported content types
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +- **application/json**
```suggestion
### application/json
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +Handy for complex bodies (ex: complex plugin configuration), in that case simply send
```suggestion
The `application/json` content type is useful for complex bodies (for example, complex plugin configuration).
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +a JSON representation of the data you want to send. Example:
```suggestion
Send a JSON representation of the data you want to send. For example:
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +An example adding a Route to a Service named `test-service`:
```suggestion
Here's an example of adding a route to a service named `test-service`:
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +- **application/x-www-form-urlencoded**
```suggestion
### application/x-www-form-urlencoded
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +Simple enough for basic request bodies, you will probably use it most of the time.
```suggestion
The content type `application/x-www-form-urlencoded` is useful for basic request bodies. 
You can use it in most situations.
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +consecutive). An example Route added to a Service named `test-service`:
```suggestion
consecutive). 

Here's an example route added to a service named `test-service`:
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +```
```suggestion
```sh
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +```
```suggestion
```sh
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +```
```suggestion
```sh
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +```
```suggestion
```sh
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +- **multipart/form-data**
```suggestion
### multipart/form-data
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +Similar to URL-encoded, this content type uses dotted keys to reference nested
```suggestion
The `multipart/form-data` content type is similar to URL-encoded. This content type uses dotted keys to reference nested
```

2024-01-31 23:32 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +An example Route added to a Service named `test-service`:
```suggestion
For example, here's a route added to a service named `test-service`:
```

2024-01-31 23:45 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +| [Event Hooks](/gateway/api/admin-ee/latest/#/Event-hooks/get-event-hooks) | [Keyring and Data Encryption](/gateway/api/admin-ee/latest/#/Keyring/get-keyring) | [Audit Logs](/gateway/api/admin-ee/la
```suggestion
The Kong Admin API is documented in OpenAPI format:

| Spec | Insomnia link |
|-------|---------------|
| [Enterprise beta API spec](/gateway/api/admin-ee/latest/) |<a href="https://insomnia.rest/run/?label=Kong%20Gateway%20Enterprise%203.4&uri=https%3A%2F%2Fraw.githubusercontent.com%2FKong%2Fdocs.konghq.com%2Fmain%2Fapi-specs%2FGateway-EE%2F3.4%2Fkong-ee-3.4.json" target="_blank"><img src="https://insomnia.rest/images/run.svg" alt="Run in Insomnia"></a>  |
|  [Open source beta API spec](/gateway/api/admin-oss/latest/) |  <a href="https://insomnia.rest/run/?label=Kong%20Gateway%20Open%20Source%203.4&uri=https%3A%2F%2Fraw.githubusercontent.com%2FKong%2Fdocs.konghq.com%2Fmain%2Fapi-specs%2FGateway-OSS%2F3.4%2Fkong-oss-3.4.json" target="_blank"><img src="https://insomnia.rest/images/run.svg" alt="Run in Insomnia"></a>|

See the following links for individual entity documentation:

{% navtabs %}
{% navtab Enterprise endpoints %}

| Endpoints    |           | |
| ------------------------------- | ------------------------------- | ----- | 
| [Information Routes](/gateway/api/admin-ee/latest/#/Information/get-endpoints) | [Health Routes](/gateway/api/admin-ee/latest/#/Information/get-status) | [Tags](/gateway/api/admin-ee/latest/#/tags/get-tags) |
| [Debug Routes](/gateway/api/admin-ee/latest/#/debug/put-debug-cluster-control-planes-nodes-log-level-log_level) | [Services](/gateway/api/admin-ee/latest/#/Services/list-service) | [Routes](/gateway/api/admin-ee/latest/#/Routes/list-route) |
| [Consumers](/gateway/api/admin-ee/latest/#/Consumers/list-consumer) | [Plugins](/gateway/api/admin-ee/latest/#/Plugins/list-plugins-with-consumer) | [Certificates](/gateway/api/admin-ee/latest/#/Certificates/list-certificate) |
| [CA Certificates](/gateway/api/admin-ee/latest/#/CA%20Certificates/list-ca_certificate) | [SNIs](/gateway/api/admin-ee/latest/#/SNIs/list-sni-with-certificate) | [Upstreams](/gateway/api/admin-ee/latest/#/Upstreams/list-upstream) |
| [Targets](/gateway/api/admin-ee/latest/#/Targets/list-target-with-upstream) | [Vaults](/gateway/api/admin-ee/latest/#/Vaults/list-vault) | [Keys](/gateway/api/admin-ee/latest/#/Keys/list-key) |
| [Filter Chains](/gateway/api/admin-ee/latest/#/filter-chains/get-filter-chains) | [Licenses](/gateway/api/admin-ee/latest/#/licenses/get-licenses) | [Workspaces](/gateway/api/admin-ee/latest/#/Workspaces/list-workspace) |
| [RBAC](/gateway/api/admin-ee/latest/#/rbac/get-rbac-users) | [Admins](/gateway/api/admin-ee/latest/#/admins/get-admins) | [Consumer Groups](/gateway/api/admin-ee/latest/#/consumer_groups/) |
| [Event Hooks](/gateway/api/admin-ee/latest/#/Event-hooks/get-event-hooks) | [Keyring and Data Encryption](/gateway/api/admin-ee/latest/#/Keyring/get-keyring) | [Audit Logs](/gateway/api/admin-ee/latest/#/audit-logs/get-audit-requests) |
{% endnavtab %}
{% navtab OSS endpoints %}
| Endpoints    |           | |
| ------------------------------- | ------------------------------- | ----- | 
| [Information Routes](/gateway/api/admin-oss/latest/#/Information/get-endpoints) | [Health Routes](/gateway/api/admin-oss/latest/#/Information/get-status) | [Tags](/gateway/api/admin-oss/latest/#/tags/get-tags) |
| [Debug Routes](/gateway/api/admin-oss/latest/#/debug/put-debug-cluster-control-planes-nodes-log-level-log_level) | [Services](/gateway/api/admin-oss/latest/#/Services/list-service) | [Routes](/gateway/api/admin-oss/latest/#/Routes/list-route) |
| [Consumers](/gateway/api/admin-oss/latest/#/Consumers/list-consumer) | [Plugins](/gateway/api/admin-oss/latest/#/Plugins/list-plugins-with-consumer) | [Certificates](/gateway/api/admin-oss/latest/#/Certificates/list-certificate) |
| [CA Certificates](/gateway/api/admin-oss/latest/#/CA%20Certificates/list-ca_certificate) | [SNIs](/gateway/api/admin-oss/latest/#/SNIs/list-sni-with-certificate) | [Upstreams](/gateway/api/admin-oss/latest/#/Upstreams/list-upstream) |
| [Targets](/gateway/api/admin-oss/latest/#/Targets/list-target-with-upstream) | [Vaults](/gateway/api/admin-oss/latest/#/Vaults/list-vault) | [Keys](/gateway/api/admin-oss/latest/#/Keys/list-key) |
{% endnavtab %}
{% endnavtabs %}
```
A few things happening here:

* Intro sentences for each table.
* We still need links to the OSS doc. How about tabs like this?
* Moving the `Endpoints` label to the first column to align the table. In context with the specs table above it, it looks odd to have the text centered:
![Screenshot 2024-01-31 at 3 19 18 PM](https://github.com/Kong/docs.konghq.com/assets/54370747/72640993-5b09-4f2a-8cc9-14be0a21d001)

Vs aligned to the left on both:
![Screenshot 2024-01-31 at 3 19 11 PM](https://github.com/Kong/docs.konghq.com/assets/54370747/cc2bb025-f249-4d94-8274-dd0a9de59b2f)

2024-01-31 23:47 UTC, lena-larionova commented on app/_src/gateway/admin-api/index_latest.md
> +| [Event Hooks](/gateway/api/admin-ee/latest/#/Event-hooks/get-event-hooks) | [Keyring and Data Encryption](/gateway/api/admin-ee/latest/#/Keyring/get-keyring) | [Audit Logs](/gateway/api/admin-ee/la
or, one more option: if we're adding tabs that already say "endpoints", how about removing the table header entirely: 
![Screenshot 2024-01-31 at 3 46 58 PM](https://github.com/Kong/docs.konghq.com/assets/54370747/cfeb8b04-8773-4f76-80ff-c4992c8fb104)

2024-02-01 19:44 UTC, merged