docs(mesh): update MeshGlobalRateLimit and MeshOPA targetref support table
Kong/docs.konghq.com pull request #6948
Opened 2024-02-14 10:23 UTC by slonka

### Description

Change the targetRef support table since 2.6 it has a different layout.
 

### Testing instructions

Preview link: 

### Checklist 

- [X] Review label added 
- [X] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

2024-02-14 10:24 UTC, slonka commented on app/_src/mesh/features/meshglobalratelimit.md
> +| `targetRef.kind`        | `Mesh`, `MeshGateway`                                     |
do not merge, `MeshGateway` needs to be added to validator

2024-02-16 10:19 UTC, michaelbeaumont requested changes

2024-02-16 10:19 UTC, michaelbeaumont commented on app/_src/mesh/features/meshglobalratelimit.md
> +{% if_version gte:2.6.x %}
```suggestion
{% if_version gte:2.7.x %}
```

2024-02-16 10:20 UTC, michaelbeaumont commented on app/_src/mesh/features/meshglobalratelimit.md
> +| `from[].targetRef.kind` | `Mesh`                                                    |
```suggestion
| `to[].targetRef.kind` | `Mesh`                                                    |
```

2024-02-16 12:52 UTC, slonka commented
Thanks for reviewing @michaelbeaumont 👍

2024-02-16 14:49 UTC, michaelbeaumont approved these changes

2024-02-23 19:14 UTC, cloudjumpercat commented
Hi @slonka ! If you rebase this PR, that should fix the failing broken links test (another PR was merged recently that fixes the 404 errors on dev).

2024-02-28 07:02 UTC, slonka commented
Hi @cloudjumpercat ! Sorry for the delay, I've just updated the branch, let's see if it passes now.

2024-02-28 08:06 UTC, slonka commented
@cloudjumpercat smoke tests still don't pass - it errors out with "invalid url" :(

2024-02-28 15:39 UTC, cloudjumpercat commented
@slonka Thanks! The smoke tests are expected to fail since this is from a fork, so that's okay. I'll review it today

2024-02-28 17:57 UTC, cloudjumpercat approved these changes
LGTM! I'll ignore the failing smoke tests since that's an expected failure since this is from a forked repo.

2024-02-28 17:57 UTC, merged