DOCU-3662: improve plugin versioning
Kong/docs.konghq.com pull request #6999
Opened 2024-02-27 17:17 UTC by fabianrbz

### Description

Related [Jira ticket](https://konghq.atlassian.net/browse/DOCU-3662)

Add support for `minimum_version` and `maximum_version` in
the frontmatter of plugin pages.

* If a page has one of these set in frontmatter, it gets generated
for that version range, similar to versions.yml
* If a page doesn’t have any minimum or maximum version,
it defaults to the setting for the whole plugin, which is set in versions.yml

The only caveat is that we had to replace `_metadata.yml` with a specific
`_metadata` folder. If a file for a specific version exists, (e.g.
`_metadata/_2.6.x.yml`) it will be used for that specific release, if
not `_metadata/_index.yml` will be used.

I also fixed a bug in the releases dropdown.
When switching to an older version for which the current page does not exist, it redirected the user to the plugin's landing page in its latest version instead of the version selected by the user.

https://github.com/Kong/docs.konghq.com/assets/715229/526c0144-2fd2-40df-b433-3769d50805e1

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

2024-02-28 15:40 UTC, fabianrbz commented
@lena-larionova I updated some of the docs, but we should write about the new behavior somewhere. what do you think about a new section [here](https://docs.konghq.com/contributing/single-sourced-plugins/)?

2024-02-29 18:07 UTC, lena-larionova requested changes
Some minor content changes.

2024-02-29 18:07 UTC, lena-larionova commented on app/contributing/single-sourced-plugins.md
Should we also add something about putting `minimum_version` or `maximum_version` in doc front matter?

2024-02-29 18:08 UTC, lena-larionova commented on app/contributing/single-sourced-plugins.md
I just saw your comment 
>  I updated some of the docs, but we should write about the new behavior somew[here](https://docs.konghq.com/contributing/single-sourced-plugins/). what do you think about a new section here?

Let's add a new section there. I think that page needs an overhaul anyway, but we don't really have another place for it.

2024-02-29 18:17 UTC, lena-larionova commented
I had no issues with any of the versioning, it works! It seems far more intuitive this way. And I love to see this:
<img width="152" alt="Screenshot 2024-02-29 at 10 16 16 AM" src="https://github.com/Kong/docs.konghq.com/assets/54370747/339697ac-9741-415e-a582-fb3419c758f8">

I think @Guaris should also take a look at this, as he had to version one of the plugins the old way before and had trouble - so I'd love to see his feedback on this approach over the old.

2024-03-01 08:22 UTC, fabianrbz commented on app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
> +{% if_plugin_version gte:3.1.x %}
what about the `3.0.x` ones?

2024-03-01 20:19 UTC, Guaris commented
LGTM

2024-03-04 18:49 UTC, lena-larionova commented on app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
> +{% if_plugin_version gte:3.1.x %}
Ack - sorry I missed this. Same thing, they don't need to exist.

2024-03-04 19:00 UTC, lena-larionova approved these changes
LGTM

2024-03-05 08:03 UTC, merged