[DOCU-3685]: WIP Install page
Kong/docs.konghq.com pull request #7030
Opened 2024-03-04 15:59 UTC by fabianrbz

### Description

 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

2024-03-06 21:30 UTC, cloudjumpercat commented
@fabianrbz I opened a draft PR that adds the install pages back: https://github.com/kumahq/kuma-website/pull/1682. I was having problems viewing it locally, so I'm just going to check that everything works correctly before asking the Mesh team to approve and merge. I'm hoping I can get some predicted URLs to you soon once I'm able to view the preview docs.

2024-03-07 14:15 UTC, cloudjumpercat commented
@fabianrbz 
**Kuma predicted URLs:**

- Kubernetes: https://kuma.io/docs/latest/installation/kubernetes/
- Helm: https://kuma.io/docs/latest/installation/helm/
- OpenShift: https://kuma.io/docs/latest/installation/openshift/
- Docker: https://kuma.io/docs/latest/installation/docker/
- Amazon Linux: https://kuma.io/docs/latest/installation/amazonlinux/
- Amazon EKS: https://kuma.io/docs/latest/installation/kubernetes/
- CentOS: https://kuma.io/docs/latest/installation/centos/
- RedHat: https://kuma.io/docs/latest/installation/redhat/
- Debian: https://kuma.io/docs/latest/installation/debian/
- Ubuntu: https://kuma.io/docs/latest/installation/ubuntu/

**Kong Mesh predicted URLs:**

- Kubernetes: https://docs.konghq.com/mesh/latest/installation/kubernetes/
- Helm: https://docs.konghq.com/mesh/latest/installation/helm/
- OpenShift: https://docs.konghq.com/mesh/latest/installation/openshift/
- Docker: https://docs.konghq.com/mesh/latest/installation/docker/
- Amazon Linux: https://docs.konghq.com/mesh/latest/installation/amazonlinux/
- Amazon EKS: https://docs.konghq.com/mesh/latest/installation/kubernetes/
- CentOS: https://docs.konghq.com/mesh/latest/installation/centos/
- RedHat: https://docs.konghq.com/mesh/latest/installation/redhat/
- Debian: https://docs.konghq.com/mesh/latest/installation/debian/
- Ubuntu: https://docs.konghq.com/mesh/latest/installation/ubuntu/



I’ll let you know once the PR has merged and the links are live!

2024-03-08 14:22 UTC, cloudjumpercat commented
@fabianrbz I started a universal quickstart in the Kuma PR (and removed the old install docs per Charly's feedback), so the URLs I previously sent won't work. I'm hoping that between the Kubernetes and Universal quickstarts, we can use those URLs for the install landing page.

2024-03-12 21:07 UTC, acgoldsmith requested changes
updates to copy

2024-03-12 21:07 UTC, acgoldsmith commented on app/_data/install_page.yml
> +    description: Grains lemonade zest cilantro cozy cinnamon oatmeal comforting pumpkin spice latte.
Replacing placeholder text w/ reused copy from original /install/ page + @connorckong's suggested CTA from March 4th discussion & comment in JIRA.

Need to confirm the CTA URL, currently using link from /gateway/latest/install/docker/#prerequisites

2024-03-12 21:07 UTC, acgoldsmith commented on app/_data/install_page.yml
> +    description: Grains lemonade zest cilantro cozy cinnamon oatmeal comforting pumpkin spice latte.
```suggestion
    description: Built for hybrid and multi-cloud environments, optimized for microservices and distributed architectures. If you want to run Kuma as a part of a production-ready API platform, you can [get started with Konnect] (https://konghq.com/products/kong-konnect/register?utm_medium=referral&utm_source=docs&utm_campaign=gateway-konnect&utm_content=docker-install) in under 5 minutes.
```

2024-03-12 21:07 UTC, acgoldsmith commented on app/_data/install_page.yml
> +    description: Grains lemonade zest cilantro cozy cinnamon oatmeal comforting pumpkin spice latte.
Replacing placeholder text w/ reused copy from original /install/ page + @connorckong's suggested CTA from March 4th discussion & comment in JIRA.

Need to confirm the CTA URL, currently using link from /gateway/latest/install/docker/#prerequisites

2024-03-12 21:52 UTC, acgoldsmith commented on app/_data/install_page.yml
> +    description: Grains lemonade zest cilantro cozy cinnamon oatmeal comforting pumpkin spice latte.
@fabianrbz , you can disregard these suggestions, they'll be obsoleted by the new install plans coming from Connor.

2024-03-25 11:28 UTC, closed without merging