New AI Rate Limiting Advanced plugin
Kong/docs.konghq.com pull request #7214
Opened 2024-04-11 13:02 UTC by AntoineJac

### Description

 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

2024-04-11 14:23 UTC, lena-larionova commented
@AntoineJac the build will continue to fail until we have the plugin's schema, which we generate from an RC. Let me get a placeholder file up and you should be able to rebase after to make the build succeed.

2024-04-22 15:16 UTC, lena-larionova commented on app/_hub/kong-inc/ai-rate-limiting-advanced/_metadata/_index.yml
> +  - traffic-control
```suggestion
  - traffic-control
  - ai
```

2024-05-06 02:00 UTC, lena-larionova requested changes

2024-05-06 03:13 UTC, lena-larionova commented
@AntoineJac The AI Gateway general get started guide got split into guide + overview, so I moved your description of the new plugin there. I also added it to the nav and added an icon for the plugin. You can preview the docs here:

[AI Analytics](https://deploy-preview-7214--kongdocs.netlify.app/gateway/unreleased/production/logging/ai-analytics/)
[Landing page](https://deploy-preview-7214--kongdocs.netlify.app/gateway/unreleased/ai-gateway/)
[AI RLA plugin](https://deploy-preview-7214--kongdocs.netlify.app/hub/kong-inc/ai-rate-limiting-advanced/unreleased/)

2024-05-06 03:28 UTC, lena-larionova commented on app/_data/tables/version_errors_konnect.yml
> +      [Ai Rate Limiting Advanced plugin](/hub/kong-inc/ai-rate-limiting-advanced/)
```suggestion
```
Let's remove this for now. Konnect updates to this table get generated out of Koko and someone on that team usually updates the whole table right before release.

2024-05-06 08:44 UTC, AntoineJac commented on app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
> +
It is the tokens return by the llm plugins

2024-05-06 09:06 UTC, AntoineJac commented on app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
> +
I have just fixed it.

2024-05-06 09:07 UTC, AntoineJac commented
@lena-larionova , thanks I reviewed and accepted all your changes. You can add them in your docs. Thanks

2024-05-06 19:55 UTC, Guaris approved these changes

2024-05-06 19:59 UTC, Guaris approved these changes

2024-05-06 19:59 UTC, merged