update gateway part in splitting traffic page
Kong/docs.konghq.com pull request #7551
Opened 2024-06-19 09:27 UTC by randmonkey

### Description

 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

2024-07-23 00:16 UTC, lena-larionova requested changes

2024-07-23 00:16 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +For splitting traffics into different gateways using Kubernetes gateway API, you should create 2 `Gateway`s in the kubernetes cluster, where each reconciled by one {{ site.kic_product_name }} instanc
```suggestion
For splitting traffic into different gateways using the Kubernetes Gateway API, create two `Gateway`s in the Kubernetes cluster, where each is reconciled by one {{ site.kic_product_name }} instance:
```

2024-07-23 00:16 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +To split traffics to different `Gateway`s in Kubernetes gateway APIs, we could configure the environment variable `CONTROLLER_GATEWAY_TO_RECONCILE` to configure {{ site.kic_product_name }} to reconci
```suggestion
You can split traffic into different `Gateway`s in the Kubernetes Gateway APIs by using the environment variable `CONTROLLER_GATEWAY_TO_RECONCILE`. Configure the variable to instruct {{ site.kic_product_name }} to reconcile specific `Gateway` instances and routes attached to the gateway:
```

2024-07-23 00:16 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +Users can also split traffic into different gateways when they are using Gateway APIs with multiple {{ site.kic_product_name }} instances and multiple `Gateway`s.
```suggestion
Advanced users of {{ site.kic_product_name }} may want to split traffic into internal and external ingress definitions. This requires multiple {{ site.kic_product_name }} instances, each pointing to a different `IngressClass`.

You can also split traffic into different gateways when you are using Gateway APIs with multiple {{ site.kic_product_name }} instances and multiple `Gateway`s.
```

2024-07-23 00:16 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +For routes in Kubernetes gateway APIs (like `HTTPRoute`), you should refer to the corresponding `Gateway` in its `spec.parentRef`.
```suggestion
For routes in Kubernetes Gateway APIs (like `HTTPRoute`), refer to the corresponding `Gateway` in its `spec.parentRef`.
```

2024-07-23 00:16 UTC, lena-larionova commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +This is an example to create a `Ingress` or `HTTPRoute` for routing internal traffic.
```suggestion
For example, this is how you can create a `Ingress` or `HTTPRoute` for routing internal traffic:
```

2024-12-13 21:07 UTC, lena-larionova approved these changes

2024-12-16 10:33 UTC, pmalek approved these changes

2024-12-16 10:33 UTC, pmalek commented on app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
> +
```suggestion
```

2024-12-16 10:34 UTC, merged