fix: Convert to AI Semantic Cache LLM examples to `plugin_example`
Kong/docs.konghq.com pull request #7932
Opened 2024-09-16 20:11 UTC by cloudjumpercat

### Description

Converting the LLM examples to use `plugin_example` instead for better consistency.
 

DOCU-4060
### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

2024-09-16 20:25 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
> +name: ai_semantic-cache
```suggestion
name: ai-semantic-cache
```

2024-09-16 20:25 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
> +name: ai_semantic-cache
```suggestion
name: ai-semantic-cache
```

2024-09-16 20:25 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
> +name: ai_semantic-cache
```suggestion
plugin: kong-inc/ai-semantic-cache
name: ai-semantic-cache
```

2024-09-16 20:28 UTC, lena-larionova requested changes

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
> +{% plugin_example %}
```suggestion

<!--vale off-->
{% plugin_example %}
```

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
> +name: ai_semantic-cache
```suggestion
plugin: kong-inc/ai-semantic-cache
name: ai-semantic-cache
```

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
> +
```suggestion
<!--vale on-->

```

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
> +{% plugin_example %}
```suggestion

<!--vale off-->
{% plugin_example %}
```

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
> +{% endplugin_example %}
```suggestion
{% endplugin_example %}
<!--vale on-->

```

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
> +  - kubernetes
```suggestion
  - curl
  - konnect
  - yaml
  - kubernetes
  - terraform
```
Why just two formats? These should work in all.

2024-09-16 20:28 UTC, lena-larionova commented on app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
> +  - kubernetes
```suggestion
formats:
  - curl
  - konnect
  - yaml
  - kubernetes
  - terraform
```

2024-09-17 16:26 UTC, lena-larionova approved these changes
lgtm!

2024-09-17 18:41 UTC, cloudjumpercat commented
@lena-larionova Thanks for the review! I pushed a few extra changes that I noticed as well as an update about how to use `plugin_example` to the contributing docs if you wouldn't mind taking a look at that.

2024-09-19 16:51 UTC, lena-larionova commented on app/contributing/kong-plugins.md
> +
```suggestion

The example accepts all plugin config, and you can configure it to output any combination of targets and formats that you need.

Possible targets:
* `service`
* `route`
* `consumer`
* `consumer_group`
* `global`

Possible formats:
* `curl`
* `konnect`
* `yaml`
* `kubernetes`
* `terrafrom`

```
Let's add this info as well.

2024-09-19 19:41 UTC, merged