Feat: Jump to explorer
Kong/docs.konghq.com pull request #8241
Opened 2024-12-09 21:13 UTC by Guaris

- Missing new images

https://konghq.atlassian.net/browse/DOCU-4179

2024-12-10 15:59 UTC, sichvoge requested changes

2024-12-10 15:59 UTC, sichvoge commented on app/konnect/analytics/dashboard.md
> +* **Explore**: This function opens the chart in the [explorer](/konnect/analytics/explorer/) where you can seamlessly drill-down into the data you are seeing from the analytics dashboard.
```suggestion
* **Explore**: This function opens the chart in the [Explorer](/konnect/analytics/explorer/) where you can seamlessly drill-down into the data you are seeing from the analytics dashboard.
```

2024-12-10 15:59 UTC, sichvoge commented on app/assets/images/products/konnect/analytics/konnect-summary-dashboard.png
Is that an image from Helen? There is no hover over effect, every chart should display the kebab menu.

2024-12-10 16:21 UTC, Guaris commented on app/assets/images/products/konnect/analytics/konnect-summary-dashboard.png
yes

2024-12-13 19:04 UTC, Guaris commented on app/konnect/analytics/dashboard.md
> +* **Explore**: This function opens the chart in the [explorer](/konnect/analytics/explorer/) where you can seamlessly drill-down into the data you are seeing from the analytics dashboard.
done

2024-12-19 09:48 UTC, lmilan approved these changes

2024-12-19 15:21 UTC, merged